// Service data for sas.xyz
const RuntimePosture = {
  LOCAL_FIRST: 'Local-first',
  APPROVAL_GATED: 'Approval-gated',
  AUTONOMOUS: 'Autonomous',
  ISOLATED: 'Isolated',
};
const PricingModel = {
  SUBSCRIPTION: 'Subscription',
  PER_OUTCOME: 'Per Outcome',
  USAGE_BASED: 'Usage-based',
  FLAT_FEE: 'Flat Fee',
};

const SERVICES = [
  {
    id: 'inv-ops-001',
    seq: '001',
    name: 'Invoice Operations Service',
    provider: 'FinFlow Autonomous',
    description: 'Reconciles bookkeeping against incoming vendor communications. Matches line items to receipts with autonomous fallback and signed outcome proofs.',
    outcome: 'Reconciled books, tax-ready.',
    connects: ['QuickBooks', 'Gmail', 'Google Drive'],
    execution: RuntimePosture.APPROVAL_GATED,
    evidence: 'Verifiable Receipts + Audit Trace',
    settlement: 'Subscription + $0.50 / outcome',
    policy: 'Budget capped at $500 / month. Vendor allowlist only.',
    recourse: '24h challenge window, bonded service',
    pricing: PricingModel.USAGE_BASED,
    price: 1.20,
    priceUnit: '/ outcome',
    privacy: 'SOC2 Type II, zero-knowledge processing',
    status: 'available',
    tags: ['Finance', 'Automated'],
    postureKey: 'gated',
  },
  {
    id: 'ent-proc-002',
    seq: '002',
    name: 'Enterprise Procurement Handler',
    provider: 'Sager Systems',
    description: 'Manages incoming RFPs against procurement policy envelopes. Flags compliance drift and surfaces vendor pivots before a human reviews.',
    outcome: 'Decision-ready procurement briefs.',
    connects: ['Workday', 'Slack', 'SharePoint'],
    execution: RuntimePosture.LOCAL_FIRST,
    evidence: 'Policy Compliance Report',
    settlement: 'Monthly seat license',
    policy: 'Strict adherence to ISO 27001 procurement protocols.',
    recourse: 'Arbitration-gated, insurance backed',
    pricing: PricingModel.SUBSCRIPTION,
    price: 450,
    priceUnit: '/ month',
    privacy: 'Local VPC execution only',
    status: 'available',
    tags: ['Legal', 'Procurement'],
    postureKey: 'local',
  },
  {
    id: 'it-patch-003',
    seq: '003',
    name: 'Vulnerability Remediation Engine',
    provider: 'Sentinel Core',
    description: 'Autonomous patch orchestration for multi-cloud staging. Identifies CVEs, spins up shadow environments, and requests deployment approval.',
    outcome: 'Validated patch deployments.',
    connects: ['AWS', 'GitHub', 'Datadog'],
    execution: RuntimePosture.AUTONOMOUS,
    evidence: 'Red/green test summaries',
    settlement: 'Per remediation action',
    policy: 'Staging only. Production requires human MFA + two-eyes sign-off.',
    recourse: 'Full rollback liability',
    pricing: PricingModel.PER_OUTCOME,
    price: 12,
    priceUnit: '/ remediation',
    privacy: 'Encrypted runtime environment',
    status: 'available',
    tags: ['DevOps', 'Security'],
    postureKey: 'autonomous',
  },
  {
    id: 'mkt-extract-004',
    seq: '004',
    name: 'Competitive Intel Extractor',
    provider: 'Insight Labs',
    description: 'Monitors competitor pricing and quarterly filings. Extracts structured data points relevant to strategic positioning.',
    outcome: 'Structured market intel feed.',
    connects: ['SEC EDGAR', 'Crunchbase', 'Public Web'],
    execution: RuntimePosture.ISOLATED,
    evidence: 'Source-linked intelligence cards',
    settlement: 'Daily flat rate',
    policy: 'No direct crawling of competitor internal APIs.',
    recourse: 'Data correction window',
    pricing: PricingModel.FLAT_FEE,
    price: 80,
    priceUnit: '/ day',
    privacy: 'Anonymous proxy execution',
    status: 'available',
    tags: ['Marketing', 'Data'],
    postureKey: 'isolated',
  },
  {
    id: 'hr-onboard-005',
    seq: '005',
    name: 'Onboarding Orchestrator',
    provider: 'Cohort Labor',
    description: 'New-hire provisioning across identity, payroll, device, and compliance. Fires pre-approved workflows keyed to role and geography.',
    outcome: 'Day-one ready employees.',
    connects: ['Okta', 'Gusto', 'Jamf'],
    execution: RuntimePosture.APPROVAL_GATED,
    evidence: 'Provisioning chain-of-custody',
    settlement: '$120 per headcount',
    policy: 'Role templates pre-approved by HRBP. Geo-fencing enforced.',
    recourse: '72h rollback, cost absorbed by provider',
    pricing: PricingModel.PER_OUTCOME,
    price: 120,
    priceUnit: '/ hire',
    privacy: 'PII-redacted transit, HIPAA-equivalent at rest',
    status: 'available',
    tags: ['HR', 'Operations'],
    postureKey: 'gated',
  },
  {
    id: 'lgl-review-006',
    seq: '006',
    name: 'Contract First-Pass Review',
    provider: 'Paragraph Legal',
    description: 'Redlines inbound vendor agreements against your playbook. Produces a reviewed PDF with justifications and escalation flags.',
    outcome: 'Redlined contracts with counsel memo.',
    connects: ['Ironclad', 'Gmail', 'Box'],
    execution: RuntimePosture.LOCAL_FIRST,
    evidence: 'Clause-level diff + counsel memo',
    settlement: '$48 per document',
    policy: 'Playbook v3.1. No signing authority. Escalation to GC over $100k.',
    recourse: 'Provider indemnity up to $1M',
    pricing: PricingModel.PER_OUTCOME,
    price: 48,
    priceUnit: '/ document',
    privacy: 'Attorney-client privilege preserved',
    status: 'available',
    tags: ['Legal'],
    postureKey: 'local',
  },
];

const INSTANCES = [
  { id: 'inv-ops-001', name: 'Invoice Operations Service', provider: 'FinFlow Autonomous', outcomes: 1041, spend: 520.50, health: 'Nominal', lastSync: '2m ago', postureKey: 'gated' },
  { id: 'ent-proc-002', name: 'Enterprise Procurement Handler', provider: 'Sager Systems', outcomes: 3, spend: 450.00, health: 'Nominal', lastSync: 'Just now', postureKey: 'local' },
  { id: 'hr-onboard-005', name: 'Onboarding Orchestrator', provider: 'Cohort Labor', outcomes: 7, spend: 840.00, health: 'Monitoring', lastSync: '41m ago', postureKey: 'gated' },
];

const AUDIT_ROWS = [
  { date: 'Apr 18, 2026', time: '14:44:05 UTC', name: 'Invoice Ops Service', proof: 'recon_trace_v1.pdf', hash: '0x7a2c9f…df82', state: 'Verified' },
  { date: 'Apr 18, 2026', time: '14:42:12 UTC', name: 'Invoice Ops Service', proof: 'recon_trace_v0.pdf', hash: '0x4b1a3e…e921', state: 'Verified' },
  { date: 'Apr 18, 2026', time: '11:15:30 UTC', name: 'Procurement Handler', proof: 'rfp_eval_brief.pdf', hash: '0x9c3d77…a834', state: 'Verified' },
  { date: 'Apr 18, 2026', time: '09:02:41 UTC', name: 'Onboarding Orchestrator', proof: 'provision_chain_21.pdf', hash: '0x2e5f88…1c44', state: 'Verified' },
  { date: 'Apr 17, 2026', time: '22:18:09 UTC', name: 'Invoice Ops Service', proof: 'recon_trace_weekly.pdf', hash: '0x8d1b2c…7789', state: 'Verified' },
  { date: 'Apr 17, 2026', time: '16:30:12 UTC', name: 'Procurement Handler', proof: 'policy_check_q2.pdf', hash: '0x3a4e66…b2a1', state: 'Verified' },
];

window.SERVICES = SERVICES;
window.INSTANCES = INSTANCES;
window.AUDIT_ROWS = AUDIT_ROWS;
window.RuntimePosture = RuntimePosture;
window.PricingModel = PricingModel;

// Evidence sample per service — what a completed outcome artifact looks like.
// Body lines are rendered monospace; the drawer frames this as a signed PDF preview.
const EVIDENCE_SAMPLES = {
  'inv-ops-001': {
    title: 'Reconciliation Trace',
    filename: 'recon_trace_v142.pdf',
    ts: 'Apr 18, 2026 · 14:44:05 UTC',
    hash: '0x7a2c9f04b91d3e2a7c4f8ddf82',
    signer: 'FinFlow Autonomous · key 0x8f…22a1',
    lines: [
      { k: 'INV-22841',  v: 'matched → PO-8812',      s: '$4,218.00', ok: true },
      { k: 'INV-22842',  v: 'matched → receipt-9031', s: '$612.50',   ok: true },
      { k: 'INV-22843',  v: 'flagged · no PO',         s: '$87.14',    ok: false },
      { k: 'INV-22844',  v: 'matched → PO-8814',      s: '$1,930.00', ok: true },
    ],
    summary: '4 line items · 3 auto-matched · 1 flagged for human review',
  },
  'ent-proc-002': {
    title: 'RFP Evaluation Brief',
    filename: 'rfp_eval_q2_brief.pdf',
    ts: 'Apr 18, 2026 · 11:15:30 UTC',
    hash: '0x9c3d7714f288a02bd1e4a7a834',
    signer: 'Sager Systems · key 0x4e…118c',
    lines: [
      { k: 'ISO 27001',  v: 'compliant · all 14 controls',   s: 'PASS',   ok: true },
      { k: 'Data residency', v: 'EU-only · verified',       s: 'PASS',   ok: true },
      { k: 'SLA parity', v: 'vendor offers 99.5 vs req 99.9', s: 'GAP',   ok: false },
      { k: 'Insurance',  v: '$5M cyber liability filed',     s: 'PASS',   ok: true },
    ],
    summary: '3 of 4 criteria met · 1 negotiable gap · recommend shortlist',
  },
  'it-patch-003': {
    title: 'Red / Green Test Summary',
    filename: 'remediation_log_cve_44219.pdf',
    ts: 'Apr 17, 2026 · 22:18:09 UTC',
    hash: '0x8d1b2c07af29b4e03c6a157789',
    signer: 'Sentinel Core · key 0x2f…9908',
    lines: [
      { k: 'CVE-2025-44219', v: 'patched · openssl→3.2.1', s: 'GREEN', ok: true },
      { k: 'Smoke suite',    v: '412 / 412 passed',       s: 'GREEN', ok: true },
      { k: 'Regression',     v: '0 new failures',         s: 'GREEN', ok: true },
      { k: 'Rollback ready', v: 'snapshot snap-9f22',     s: 'ARMED', ok: true },
    ],
    summary: 'Staging verified · awaiting two-eyes approval for production promote',
  },
  'mkt-extract-004': {
    title: 'Market Intel Card',
    filename: 'competitor_pricing_wk16.pdf',
    ts: 'Apr 17, 2026 · 08:04:22 UTC',
    hash: '0x3a4e66cc8b19fe7e2d27edb2a1',
    signer: 'Insight Labs · key 0x1a…7743',
    lines: [
      { k: 'Vendor A',   v: 'Pro plan · $99 → $119',   s: '+20%', ok: false },
      { k: 'Vendor B',   v: 'new tier · Team $49',      s: 'NEW',  ok: true },
      { k: 'Vendor C',   v: 'unchanged since wk 9',     s: 'FLAT', ok: true },
      { k: 'Source',     v: 'SEC 10-Q + public pricing', s: '4 refs', ok: true },
    ],
    summary: '3 vendors tracked · 1 price move · sources linked in appendix',
  },
  'hr-onboard-005': {
    title: 'Provisioning Chain-of-Custody',
    filename: 'provision_chain_21.pdf',
    ts: 'Apr 18, 2026 · 09:02:41 UTC',
    hash: '0x2e5f88bb0319dc4a80d4e41c44',
    signer: 'Cohort Labor · key 0x9c…0044',
    lines: [
      { k: 'Okta identity',  v: 'issued · SSO group EU-Sales', s: 'DONE', ok: true },
      { k: 'Gusto payroll',  v: 'enrolled · DE locale',        s: 'DONE', ok: true },
      { k: 'Jamf device',    v: 'M3 shipped to Munich',        s: 'DONE', ok: true },
      { k: 'Policy ack',     v: 'awaiting e-sign',             s: 'PEND', ok: false },
    ],
    summary: '3 of 4 steps sealed · policy acknowledgement pending new hire',
  },
  'lgl-review-006': {
    title: 'Counsel Redline Memo',
    filename: 'msa_redline_v3_1.pdf',
    ts: 'Apr 17, 2026 · 16:30:12 UTC',
    hash: '0x5c9a11ff3e80cd9711b8e42266',
    signer: 'Paragraph Legal · key 0x6d…ba12',
    lines: [
      { k: '§4 Liability cap', v: 'raised to 2× fees · accepted',   s: 'OK',     ok: true },
      { k: '§7 Auto-renew',    v: 'struck · opt-in required',       s: 'OK',     ok: true },
      { k: '§12 Indemnity',    v: 'vendor pushback · escalate GC',  s: 'FLAG',   ok: false },
      { k: '§19 Governing law', v: 'DE → NY · accepted',           s: 'OK',     ok: true },
    ],
    summary: '3 clauses accepted · 1 flagged for GC review · no signing authority exercised',
  },
};

window.EVIDENCE_SAMPLES = EVIDENCE_SAMPLES;

// Catalog deltas — recent governed changes since user last viewed.
// Tones: 'add' (sage), 'price' (accent), 'policy' (plum), 'pending' (coral).
const CATALOG_DELTAS = [
  {
    id: 'd1',
    when: '2d ago',
    actor: 'Cohort Labor',
    seq: '005',
    kind: 'price',
    glyph: '$',
    headline: 'Per-hire price reduced',
    detail: '$140 → $120 / hire · effective May 01',
    by: 'Vendor · auto-applied (no policy impact)',
  },
  {
    id: 'd2',
    when: '4d ago',
    actor: 'Sentinel Core',
    seq: '003',
    kind: 'policy',
    glyph: '◆',
    headline: 'Envelope tightened',
    detail: 'Production patches now require two-eyes sign-off',
    by: 'Infosec · Bravo + Charlie envelope merge',
  },
  {
    id: 'd3',
    when: '6d ago',
    actor: 'Paragraph Legal',
    seq: '006',
    kind: 'add',
    glyph: '+',
    headline: 'Added to catalog',
    detail: 'Contract First-Pass Review · indemnity to $1M',
    by: 'Legal · 24h Infosec sign-off pending',
  },
];

window.CATALOG_DELTAS = CATALOG_DELTAS;
