// Service data for sas.xyz
const RuntimePosture = {
  LOCAL_FIRST: 'Local-first',
  APPROVAL_GATED: 'Approval-gated',
  AUTONOMOUS: 'Autonomous',
  ISOLATED: 'Isolated',
};
const PricingModel = {
  SUBSCRIPTION: 'Subscription',
  PER_OUTCOME: 'Per Outcome',
  USAGE_BASED: 'Usage-based',
  FLAT_FEE: 'Flat Fee',
};

const SERVICES = [
  {
    id: 'inv-ops-001',
    seq: '001',
    name: 'Invoice Operations Service',
    provider: 'FinFlow Autonomous',
    description: 'Reconciles bookkeeping against incoming vendor communications. Matches line items to receipts with autonomous fallback and signed outcome proofs.',
    outcome: 'Reconciled books, tax-ready.',
    connects: ['QuickBooks', 'Gmail', 'Google Drive'],
    execution: RuntimePosture.APPROVAL_GATED,
    evidence: 'Verifiable Receipts + Audit Trace',
    settlement: 'Subscription + $0.50 / outcome',
    policy: 'Budget capped at $500 / month. Vendor allowlist only.',
    recourse: '24h challenge window, bonded service',
    pricing: PricingModel.USAGE_BASED,
    price: 1.20,
    priceUnit: '/ outcome',
    privacy: 'SOC2 Type II, zero-knowledge processing',
    status: 'available',
    tags: ['Finance', 'Automated'],
    postureKey: 'gated',
  },
  {
    id: 'ent-proc-002',
    seq: '002',
    name: 'Enterprise Procurement Handler',
    provider: 'Sager Systems',
    description: 'Manages incoming RFPs against procurement policy envelopes. Flags compliance drift and surfaces vendor pivots before a human reviews.',
    outcome: 'Decision-ready procurement briefs.',
    connects: ['Workday', 'Slack', 'SharePoint'],
    execution: RuntimePosture.LOCAL_FIRST,
    evidence: 'Policy Compliance Report',
    settlement: 'Monthly seat license',
    policy: 'Strict adherence to ISO 27001 procurement protocols.',
    recourse: 'Arbitration-gated, insurance backed',
    pricing: PricingModel.SUBSCRIPTION,
    price: 450,
    priceUnit: '/ month',
    privacy: 'Local VPC execution only',
    status: 'available',
    tags: ['Legal', 'Procurement'],
    postureKey: 'local',
  },
  {
    id: 'it-patch-003',
    seq: '003',
    name: 'Vulnerability Remediation Engine',
    provider: 'Sentinel Core',
    description: 'Autonomous patch orchestration for multi-cloud staging. Identifies CVEs, spins up shadow environments, and requests deployment approval.',
    outcome: 'Validated patch deployments.',
    connects: ['AWS', 'GitHub', 'Datadog'],
    execution: RuntimePosture.AUTONOMOUS,
    evidence: 'Red/green test summaries',
    settlement: 'Per remediation action',
    policy: 'Staging only. Production requires human MFA + two-eyes sign-off.',
    recourse: 'Full rollback liability',
    pricing: PricingModel.PER_OUTCOME,
    price: 12,
    priceUnit: '/ remediation',
    privacy: 'Encrypted runtime environment',
    status: 'available',
    tags: ['DevOps', 'Security'],
    postureKey: 'autonomous',
  },
  {
    id: 'mkt-extract-004',
    seq: '004',
    name: 'Competitive Intel Extractor',
    provider: 'Insight Labs',
    description: 'Monitors competitor pricing and quarterly filings. Extracts structured data points relevant to strategic positioning.',
    outcome: 'Structured market intel feed.',
    connects: ['SEC EDGAR', 'Crunchbase', 'Public Web'],
    execution: RuntimePosture.ISOLATED,
    evidence: 'Source-linked intelligence cards',
    settlement: 'Daily flat rate',
    policy: 'No direct crawling of competitor internal APIs.',
    recourse: 'Data correction window',
    pricing: PricingModel.FLAT_FEE,
    price: 80,
    priceUnit: '/ day',
    privacy: 'Anonymous proxy execution',
    status: 'available',
    tags: ['Marketing', 'Data'],
    postureKey: 'isolated',
  },
  {
    id: 'hr-onboard-005',
    seq: '005',
    name: 'Onboarding Orchestrator',
    provider: 'Cohort Labor',
    description: 'New-hire provisioning across identity, payroll, device, and compliance. Fires pre-approved workflows keyed to role and geography.',
    outcome: 'Day-one ready employees.',
    connects: ['Okta', 'Gusto', 'Jamf'],
    execution: RuntimePosture.APPROVAL_GATED,
    evidence: 'Provisioning chain-of-custody',
    settlement: '$120 per headcount',
    policy: 'Role templates pre-approved by HRBP. Geo-fencing enforced.',
    recourse: '72h rollback, cost absorbed by provider',
    pricing: PricingModel.PER_OUTCOME,
    price: 120,
    priceUnit: '/ hire',
    privacy: 'PII-redacted transit, HIPAA-equivalent at rest',
    status: 'available',
    tags: ['HR', 'Operations'],
    postureKey: 'gated',
  },
  {
    id: 'lgl-review-006',
    seq: '006',
    name: 'Contract First-Pass Review',
    provider: 'Paragraph Legal',
    description: 'Redlines inbound vendor agreements against your playbook. Produces a reviewed PDF with justifications and escalation flags.',
    outcome: 'Redlined contracts with counsel memo.',
    connects: ['Ironclad', 'Gmail', 'Box'],
    execution: RuntimePosture.LOCAL_FIRST,
    evidence: 'Clause-level diff + counsel memo',
    settlement: '$48 per document',
    policy: 'Playbook v3.1. No signing authority. Escalation to GC over $100k.',
    recourse: 'Provider indemnity up to $1M',
    pricing: PricingModel.PER_OUTCOME,
    price: 48,
    priceUnit: '/ document',
    privacy: 'Attorney-client privilege preserved',
    status: 'available',
    tags: ['Legal'],
    postureKey: 'local',
  },
];

const INSTANCES = [
  { id: 'inv-ops-001', name: 'Invoice Operations Service', provider: 'FinFlow Autonomous', outcomes: 1041, spend: 520.50, health: 'Nominal', lastSync: '2m ago', postureKey: 'gated' },
  { id: 'ent-proc-002', name: 'Enterprise Procurement Handler', provider: 'Sager Systems', outcomes: 3, spend: 450.00, health: 'Nominal', lastSync: 'Just now', postureKey: 'local' },
  { id: 'hr-onboard-005', name: 'Onboarding Orchestrator', provider: 'Cohort Labor', outcomes: 7, spend: 840.00, health: 'Monitoring', lastSync: '41m ago', postureKey: 'gated' },
];

const AUDIT_ROWS = [
  { date: 'Apr 18, 2026', time: '14:44:05 UTC', name: 'Invoice Ops Service', proof: 'recon_trace_v1.pdf', hash: '0x7a2c9f…df82', state: 'Verified' },
  { date: 'Apr 18, 2026', time: '14:42:12 UTC', name: 'Invoice Ops Service', proof: 'recon_trace_v0.pdf', hash: '0x4b1a3e…e921', state: 'Verified' },
  { date: 'Apr 18, 2026', time: '11:15:30 UTC', name: 'Procurement Handler', proof: 'rfp_eval_brief.pdf', hash: '0x9c3d77…a834', state: 'Verified' },
  { date: 'Apr 18, 2026', time: '09:02:41 UTC', name: 'Onboarding Orchestrator', proof: 'provision_chain_21.pdf', hash: '0x2e5f88…1c44', state: 'Verified' },
  { date: 'Apr 17, 2026', time: '22:18:09 UTC', name: 'Invoice Ops Service', proof: 'recon_trace_weekly.pdf', hash: '0x8d1b2c…7789', state: 'Verified' },
  { date: 'Apr 17, 2026', time: '16:30:12 UTC', name: 'Procurement Handler', proof: 'policy_check_q2.pdf', hash: '0x3a4e66…b2a1', state: 'Verified' },
];

window.SERVICES = SERVICES;
window.INSTANCES = INSTANCES;
window.AUDIT_ROWS = AUDIT_ROWS;
window.RuntimePosture = RuntimePosture;
window.PricingModel = PricingModel;
