#!/usr/bin/env python3
"""AFT-CB R13 — trace → TLA trace-replay module generator (C4a).

Reads a committed JSON-lines boundary-ring trace (header line with the
constants, then one applied event per line) and emits a TLC-checkable
module pair <Module>.tla/<Module>.cfg into the output directory.  The
generated module EXTENDS the kernel it replays against: every trace event
becomes the corresponding kernel ACTION at a fixed index, so TLC re-checks
each step's guard and every invariant along the way.

The replay MUST run with deadlock checking ON (no -deadlock flag): a
mid-trace disabled action — a step the code took that the model refuses —
deadlocks, and that deadlock IS the divergence signal this lane exists
for.  The terminal state self-loops, so a fully-replayed trace never
deadlocks.

Usage: gen_aft_trace_module.py <trace.jsonl> <module-name> <out-dir>
"""

import json
import re
import sys

MODEL_VALUE = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")

# Names owned by BoundaryRing.tla or this generator's output; a trace
# identifier colliding with one of these would shadow the model.
RESERVED = {
    "Ring", "HonestMembers", "Slots", "Roots", "Artifacts", "NoRoot",
    "delivered", "declared", "journal", "acks", "closes", "vars",
    "TypeOK", "Init", "Next", "Spec", "Inv", "Uniqueness",
    "Deliver", "HonestDeclare", "ByzantineDeclare", "HonestFinalAck",
    "ByzantineEmit", "CloseAct", "ConstantAssumptions",
    "idx", "TraceLen", "TraceStep", "TraceInit", "TraceNext",
}

ACTIONS = {
    "Deliver": ("artifact", "member"),
    "HonestDeclare": ("member", "slot", "artifacts"),
    "ByzantineDeclare": ("member", "slot", "artifacts"),
    "HonestFinalAck": ("member", "slot", "root"),
    "ByzantineEmit": ("member", "slot", "root"),
    "Close": ("slot", "root"),
}


def die(msg):
    print(f"gen_aft_trace_module: {msg}", file=sys.stderr)
    sys.exit(1)


def check_id(name):
    if not MODEL_VALUE.match(name):
        die(f"identifier is not a TLA model value: {name!r}")
    if name in RESERVED:
        die(f"identifier collides with a model name: {name!r}")
    return name


def main():
    if len(sys.argv) != 4:
        die("usage: gen_aft_trace_module.py <trace.jsonl> <module-name> <out-dir>")
    trace_path, module, out_dir = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(trace_path) as fh:
        lines = [json.loads(l) for l in fh if l.strip()]
    if not lines or "constants" not in lines[0]:
        die("first line must be the constants header")
    consts = lines[0]["constants"]
    events = lines[1:]
    if not events:
        die("trace has no events")

    ring = [check_id(m) for m in consts["ring"]]
    honest = [check_id(m) for m in consts["honest"]]
    slots = [check_id(s) for s in consts["slots"]]
    roots = [check_id(r) for r in consts["roots"]]
    artifacts = [check_id(a) for a in consts["artifacts"]]
    if consts.get("no_root") != "NoRoot":
        die("header no_root must be the sentinel name 'NoRoot'")
    if not set(honest) <= set(ring):
        die("honest is not a subset of ring")

    ids = []
    for group in (ring, slots, roots, artifacts):
        for i in group:
            if i not in ids:
                ids.append(i)

    steps = []
    for n, ev in enumerate(events, start=1):
        action = ev.get("action")
        if action not in ACTIONS:
            die(f"event {n}: unknown action {action!r}")
        fields = ACTIONS[action]
        extra = set(ev) - set(fields) - {"action"}
        if extra:
            die(f"event {n}: unexpected fields {sorted(extra)}")
        args = []
        for f in fields:
            if f not in ev:
                die(f"event {n}: {action} missing field {f!r}")
            v = ev[f]
            if f == "artifacts":
                if not isinstance(v, list):
                    die(f"event {n}: artifacts must be a list")
                for a in v:
                    if check_id(a) not in artifacts:
                        die(f"event {n}: undeclared artifact {a!r}")
                args.append("{" + ", ".join(v) + "}")
            else:
                if check_id(v) not in ids:
                    die(f"event {n}: undeclared identifier {v!r}")
                args.append(v)
        # Trace "Deliver" carries (artifact, member) but the kernel action
        # signature is Deliver(a, m) — same order.  "Close" maps to CloseAct.
        op = "CloseAct" if action == "Close" else action
        steps.append(f"{op}({', '.join(args)})")

    arms = "\n".join(
        f"  {'CASE' if i == 1 else '  []'} k = {i} -> {step}"
        for i, step in enumerate(steps, start=1)
    )

    tla = f"""---- MODULE {module} ----
(* GENERATED by gen_aft_trace_module.py from {trace_path.rsplit('/', 1)[-1]} — do not edit. *)
(* Replays a recorded behavior against the BoundaryRing kernel: each     *)
(* trace event must be the corresponding ENABLED kernel action at its    *)
(* index.  Run TLC with deadlock checking ON — a disabled mid-trace      *)
(* action deadlocks, which is the divergence signal.                     *)
EXTENDS BoundaryRing, Naturals

CONSTANTS {", ".join(ids)}

VARIABLE idx

TraceLen == {len(steps)}

TraceStep(k) ==
{arms}
    [] OTHER -> FALSE

TraceInit == Init /\\ idx = 1

TraceNext ==
  \\/ /\\ idx \\in 1..TraceLen
     /\\ TraceStep(idx)
     /\\ idx' = idx + 1
  \\/ /\\ idx = TraceLen + 1
     /\\ UNCHANGED vars
     /\\ idx' = idx
====
"""

    const_lines = [f"  {i} = {i}" for i in ids]
    const_lines += [
        f"  Ring = {{{', '.join(ring)}}}",
        f"  HonestMembers = {{{', '.join(honest)}}}",
        f"  Slots = {{{', '.join(slots)}}}",
        f"  Roots = {{{', '.join(roots)}}}",
        f"  Artifacts = {{{', '.join(artifacts)}}}",
        "  NoRoot = NoRoot",
    ]
    cfg = (
        "\\* GENERATED trace-replay configuration — do not edit.\n"
        "CONSTANTS\n" + "\n".join(const_lines) + "\n\n"
        "INIT TraceInit\nNEXT TraceNext\n\n"
        "INVARIANT TypeOK\nINVARIANT Inv\nINVARIANT Uniqueness\n"
    )

    with open(f"{out_dir}/{module}.tla", "w") as fh:
        fh.write(tla)
    with open(f"{out_dir}/{module}.cfg", "w") as fh:
        fh.write(cfg)
    print(f"generated {module}.tla/.cfg: {len(steps)} steps")


if __name__ == "__main__":
    main()
