function createInitialStudioRuntimeProjection({
  approvalId,
  executionMode,
  permissionMode,
  policyLeaseId,
  runtimeProfile,
} = {}) {
  return {
    schemaVersion: "ioi.agent-studio.operational-chat.projection.v1",
    threadId: null,
    sessionId: null,
    runId: null,
    turnId: null,
    status: "idle",
    pending: false,
    immediateSubmitSeen: false,
    pendingSeen: false,
    pendingStartedAtMs: null,
    pendingWorklog: [],
    runtimeEventSeenIds: [],
    lastError: null,
    lastModelStream: null,
    lastIntentFrame: null,
    executionMode,
    runtimeProfile,
    modelRoute: "route.local-first",
    selectedModel: "auto",
    reasoningEffort: "none",
    approvalMode: permissionMode,
    approvalId,
    hunkApprovalId: approvalId,
    policyLeaseId,
    hunkDecision: null,
    runtimeCockpit: {
      achieved: false,
      modelBackedStreamingObserved: false,
      realDaemonToolProposalObserved: false,
      policyLeaseDialogObserved: false,
      policyDeniedActionDidNotExecute: false,
      policyLeaseAllowOnceObserved: false,
      policyLeaseRevokeObserved: false,
      policyLeaseExpiryObserved: false,
      policyLeaseRevokedActionDidNotExecute: false,
      policyLeaseExpiredActionDidNotExecute: false,
      sandboxCommandOutputStreamObserved: false,
      sandboxCommandReceiptObserved: false,
      inlineDiffOverlayObserved: false,
      hunkNavigationObserved: false,
      hunkAcceptRejectReceiptsObserved: false,
      stopControlObserved: false,
      resumeControlObserved: false,
      stopResumeObserved: false,
      diagnosticsTestGateObserved: false,
      receiptTimelinePerStepObserved: false,
      replayStepDetailObserved: false,
      projectionOnlyRuntimeRejected: true,
      browserStatusObserved: false,
      workerStatusObserved: false,
      managedLiveViewportObserved: false,
      managedSessionLabelsObserved: false,
      conversationArtifactObserved: false,
    },
    runtimeUx: {
      denoised: true,
      tracingSeparationAchieved: true,
      compactStatusesHaveTraceLinks: true,
      modelProseNotAcceptedAsRuntimeTruth: true,
      verifiedBadgesRequireReceiptRefs: true,
    },
    runtimeEvents: [],
    actionCards: [],
    policyLeases: [],
    commandOutputs: [],
    diagnosticGates: [],
    engineReconnectBanners: [],
    trajectoryReplayPanels: [],
    sessionBrainPanels: [],
    chatResponsibilityContracts: [],
    securityScanPanels: [],
    workerContributionTraces: [],
    safeModeToolSuppressionPanels: [],
    onboardingDiagnosticsPanels: [],
    gatewayTokenHygienePanels: [],
    sandboxResourceLimitPanels: [],
    parentTrajectoryLinkagePanels: [],
    battleModePermissionImportPanels: [],
    importedStopHookGatePanels: [],
    importedBrowserActionEvidencePanels: [],
    importedExecutorConfigPanels: [],
    importedPolicyDraftPanels: [],
    importedGenerationMetadataPanels: [],
    importedErrorRenderInfoPanels: [],
    outputRenderers: [],
    replaySteps: [],
    browserCards: [],
    workerCards: [],
    computerUseSessions: [],
    conversationArtifacts: [],
    turns: [
      {
        role: "assistant",
        content:
          "Agent Studio is ready. Prompts run through daemon-owned sessions; Studio stays calm by default and links proof details into Tracing.",
        createdAt: new Date().toISOString(),
      },
    ],
    history: [
      {
        id: "studio-session-current",
        title: "Current daemon session",
        status: "idle",
      },
    ],
    timeline: [
      {
        label: "Studio surface opened",
        detail: "Awaiting prompt",
        status: "ready",
      },
    ],
    approvals: [],
    receipts: [],
    terminal: [
      {
        label: "No terminal job running",
        detail: "Terminal/test output will be projected from daemon-owned execution receipts.",
      },
    ],
    diffHunks: [],
  };
}

module.exports = {
  createInitialStudioRuntimeProjection,
};
