//! Contextual notification contracts — the owning Rust source for the notification
//! family exported to `apps/hypervisor/src/generated/hypervisor-contracts/`.
//!
//! # Why this module exists
//!
//! The generated notification contracts carried the ts-rs
//! "Do not edit this file manually" banner while **no Rust type in the repository
//! derived them**. They were orphaned artifacts: unrenameable through their stated
//! source, and unverifiable against any Rust definition. This module is that
//! missing source.
//!
//! # Naming
//!
//! Canon rules (`docs/architecture/foundations/term-boundaries.md`,
//! "Assistant Shapes: Ruling and Dispositions") that `Assistant` is a
//! Session-backed faculty, not a durable object. What the old
//! `AssistantNotificationRecord` names is a durable **Notification** — the
//! eight-state lifecycle belongs to the notification, not to an assistant — so the
//! canonical name is [`ContextualNotificationRecord`]. The deprecated
//! `Assistant*` spellings survive only as TypeScript compatibility aliases in
//! owned (non-generated) product code; they are aliases, not a second concept.
//!
//! # Scope
//!
//! These are **projection contracts**: the wire shape a notification takes when it
//! is rendered. Nothing here establishes a durable Assistant aggregate, and no
//! daemon route currently serves them. The types exist so the generated
//! TypeScript has a real owner to be renamed and evolved through.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Which rail a notification is delivered on. `control` is operator/runtime
/// signalling; `assistant` is the Session-backed faculty's own surface.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "snake_case")]
pub enum NotificationRail {
    Control,
    Assistant,
}

/// What kind of attention the notification is asking for.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "snake_case")]
pub enum ContextualNotificationClass {
    FollowUpRisk,
    DeadlineRisk,
    MeetingPrep,
    StalledWorkflow,
    ValuableCompletion,
    Digest,
    AutomationOpportunity,
    HabitualFriction,
    AuthAttention,
}

/// The notification lifecycle. Eight states, owned by the notification itself.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "snake_case")]
pub enum ContextualNotificationStatus {
    New,
    Seen,
    Acknowledged,
    Snoozed,
    Resolved,
    Dismissed,
    Expired,
    Archived,
}

/// Advisory ordering weight. Severity never grants authority; it only ranks.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "snake_case")]
pub enum NotificationSeverity {
    Informational,
    Low,
    Medium,
    High,
    Critical,
}

/// How much of the underlying content may be rendered in a preview surface.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "snake_case")]
pub enum NotificationPreviewMode {
    Redacted,
    Compact,
    Full,
}

/// The observation depth the notification's evidence was drawn from.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "snake_case")]
pub enum ObservationTier {
    WorkflowState,
    ConnectorMetadata,
    RedactedConnectorContent,
    CoarseHostContext,
    DeepAmbientBehavior,
}

/// Presentation weight of an offered action. Style is presentation only — it
/// carries no authority, and a `danger` style does not make an action privileged.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "snake_case")]
pub enum NotificationActionStyle {
    Primary,
    Secondary,
    Danger,
    Quiet,
}

/// An action offered on a notification. The identifier is what the surface
/// submits back; the label and style are presentation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct NotificationAction {
    pub id: String,
    pub label: String,
    pub style: Option<NotificationActionStyle>,
}

/// Which delivery surfaces this notification has actually reached. Every field is
/// a record of what happened, not a request for what should happen.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct NotificationDeliveryState {
    pub toast_sent: bool,
    pub inbox_visible: bool,
    pub badge_counted: bool,
    pub pill_visible: bool,
    pub last_toast_at_ms: Option<f64>,
}

/// Hashes of the policy and request that admitted this notification. Both are
/// optional because a notification may predate policy binding; a missing hash is
/// an absent claim, never an implied approval.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct NotificationPolicyRefs {
    pub policy_hash: Option<String>,
    pub request_hash: Option<String>,
}

/// Privacy posture of the notification's rendered content.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct NotificationPrivacy {
    pub preview_mode: NotificationPreviewMode,
    pub contains_sensitive_data: bool,
    pub observation_tier: ObservationTier,
}

/// Where the notification came from, in operator-readable terms.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct NotificationSource {
    pub service_name: String,
    pub workflow_name: String,
    pub step_name: String,
}

/// The kind of artifact a notification's evidence points at.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ArtifactType {
    Diff,
    File,
    Web,
    RunBundle,
    Report,
    Log,
}

/// A pointer to evidence. Snake-cased on the wire: this shape is shared with
/// contracts outside the notification family and its spelling is load-bearing.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
pub struct ArtifactRef {
    pub artifact_id: String,
    pub artifact_type: ArtifactType,
}

/// The concrete external thing a notification is about.
///
/// Snake-cased on the wire, and every variant carries a `connector_id`: a target
/// is only meaningful relative to the connector whose authority reaches it. A
/// target names a subject — it never itself authorizes acting on that subject.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum NotificationTarget {
    GmailThread {
        connector_id: String,
        thread_id: String,
        message_id: Option<String>,
    },
    CalendarEvent {
        connector_id: String,
        calendar_id: String,
        event_id: String,
    },
    ConnectorAuth {
        connector_id: String,
    },
    ConnectorSubscription {
        connector_id: String,
        subscription_id: String,
    },
}

/// A durable notification record.
///
/// Formerly `AssistantNotificationRecord`. The eight-state lifecycle in
/// [`ContextualNotificationStatus`] belongs to this record; the assistant is the
/// faculty that surfaces it, not the object that owns it.
///
/// `priority_score`, `confidence_score`, and `ranking_reason` are advisory
/// ordering signals. They rank what a person sees first; they never stand in for
/// an authority decision.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct ContextualNotificationRecord {
    pub item_id: String,
    pub rail: NotificationRail,
    pub notification_class: ContextualNotificationClass,
    pub status: ContextualNotificationStatus,
    pub severity: NotificationSeverity,
    pub title: String,
    pub summary: String,
    pub reason: Option<String>,
    pub recommended_action: Option<String>,
    pub consequence_if_ignored: Option<String>,
    pub created_at_ms: f64,
    pub updated_at_ms: f64,
    pub due_at_ms: Option<f64>,
    pub expires_at_ms: Option<f64>,
    pub snoozed_until_ms: Option<f64>,
    pub dedupe_key: String,
    pub thread_id: Option<String>,
    pub session_id: Option<String>,
    pub workflow_id: Option<String>,
    pub run_id: Option<String>,
    pub delivery_state: NotificationDeliveryState,
    pub privacy: NotificationPrivacy,
    pub source: NotificationSource,
    pub artifact_refs: Vec<ArtifactRef>,
    pub source_event_ids: Vec<String>,
    pub policy_refs: NotificationPolicyRefs,
    pub actions: Vec<NotificationAction>,
    pub target: Option<NotificationTarget>,
    pub priority_score: f64,
    pub confidence_score: f64,
    pub ranking_reason: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use ts_rs::{Config, TS};

    /// The generated TypeScript is consumed by product code that was written
    /// against the pre-existing orphaned contracts. These assertions pin the
    /// exported shape so a Rust-side edit cannot silently change the wire
    /// contract those consumers depend on.
    #[test]
    fn exported_bindings_match_the_consumed_wire_shape() {
        assert_eq!(
            ContextualNotificationStatus::inline(&Config::default()),
            r#""new" | "seen" | "acknowledged" | "snoozed" | "resolved" | "dismissed" | "expired" | "archived""#
        );
        assert_eq!(ObservationTier::inline(&Config::default()), r#""workflow_state" | "connector_metadata" | "redacted_connector_content" | "coarse_host_context" | "deep_ambient_behavior""#);
        assert_eq!(
            ArtifactRef::inline(&Config::default()),
            "{ artifact_id: string, artifact_type: ArtifactType, }"
        );
        // The record keeps its camelCase field spelling and its exported name.
        assert_eq!(
            ContextualNotificationRecord::ident(&Config::default()),
            "ContextualNotificationRecord"
        );
        // Shared with the artifact family; its member set is not ours to widen.
        assert_eq!(
            ArtifactType::inline(&Config::default()),
            r#""DIFF" | "FILE" | "WEB" | "RUN_BUNDLE" | "REPORT" | "LOG""#
        );
        let record = ContextualNotificationRecord::inline(&Config::default());
        assert!(record.contains("itemId: string"), "{record}");
        assert!(record.contains("artifactRefs: Array<ArtifactRef>"), "{record}");
        assert!(
            record.contains("target: NotificationTarget | null"),
            "{record}"
        );
    }

    /// A target names a subject and is inseparable from the connector whose
    /// authority reaches it. Serialization is tagged by `kind`, snake-cased, and
    /// always carries `connector_id`.
    #[test]
    fn every_notification_target_variant_names_its_connector() {
        let variants = vec![
            NotificationTarget::GmailThread {
                connector_id: "connector_gmail".to_string(),
                thread_id: "thread_1".to_string(),
                message_id: None,
            },
            NotificationTarget::CalendarEvent {
                connector_id: "connector_calendar".to_string(),
                calendar_id: "primary".to_string(),
                event_id: "event_1".to_string(),
            },
            NotificationTarget::ConnectorAuth {
                connector_id: "connector_gmail".to_string(),
            },
            NotificationTarget::ConnectorSubscription {
                connector_id: "connector_gmail".to_string(),
                subscription_id: "sub_1".to_string(),
            },
        ];
        let expected_kinds = [
            "gmail_thread",
            "calendar_event",
            "connector_auth",
            "connector_subscription",
        ];
        for (variant, expected) in variants.iter().zip(expected_kinds) {
            let value = serde_json::to_value(variant).expect("target serializes");
            assert_eq!(value.get("kind").and_then(|v| v.as_str()), Some(expected));
            assert!(
                value.get("connector_id").and_then(|v| v.as_str()).is_some(),
                "{expected} must name its connector: {value}"
            );
        }
    }

    /// Round-tripping proves the camelCase wire spelling the TypeScript consumes
    /// is the spelling this Rust type actually reads back.
    #[test]
    fn record_round_trips_through_its_camel_case_wire_form() {
        let record = ContextualNotificationRecord {
            item_id: "notification_1".to_string(),
            rail: NotificationRail::Assistant,
            notification_class: ContextualNotificationClass::FollowUpRisk,
            status: ContextualNotificationStatus::New,
            severity: NotificationSeverity::Medium,
            title: "Follow up".to_string(),
            summary: "A reply is outstanding.".to_string(),
            reason: Some("no reply in 5 days".to_string()),
            recommended_action: None,
            consequence_if_ignored: None,
            created_at_ms: 1_700_000_000_000.0,
            updated_at_ms: 1_700_000_000_000.0,
            due_at_ms: None,
            expires_at_ms: None,
            snoozed_until_ms: None,
            dedupe_key: "follow_up:thread_1".to_string(),
            thread_id: Some("thread_1".to_string()),
            session_id: None,
            workflow_id: None,
            run_id: None,
            delivery_state: NotificationDeliveryState {
                toast_sent: false,
                inbox_visible: true,
                badge_counted: true,
                pill_visible: false,
                last_toast_at_ms: None,
            },
            privacy: NotificationPrivacy {
                preview_mode: NotificationPreviewMode::Redacted,
                contains_sensitive_data: true,
                observation_tier: ObservationTier::ConnectorMetadata,
            },
            source: NotificationSource {
                service_name: "gmail".to_string(),
                workflow_name: "follow_up_watch".to_string(),
                step_name: "scan".to_string(),
            },
            artifact_refs: vec![ArtifactRef {
                artifact_id: "message_1".to_string(),
                artifact_type: ArtifactType::File,
            }],
            source_event_ids: vec!["event_1".to_string()],
            policy_refs: NotificationPolicyRefs {
                policy_hash: None,
                request_hash: None,
            },
            actions: vec![NotificationAction {
                id: "open".to_string(),
                label: "Open thread".to_string(),
                style: Some(NotificationActionStyle::Primary),
            }],
            target: Some(NotificationTarget::GmailThread {
                connector_id: "connector_gmail".to_string(),
                thread_id: "thread_1".to_string(),
                message_id: None,
            }),
            priority_score: 0.8,
            confidence_score: 0.6,
            ranking_reason: vec!["stale_thread".to_string()],
        };
        let value = serde_json::to_value(&record).expect("record serializes");
        assert!(value.get("itemId").is_some(), "{value}");
        assert!(value.get("artifactRefs").is_some(), "{value}");
        assert!(value.get("item_id").is_none(), "{value}");
        let back: ContextualNotificationRecord =
            serde_json::from_value(value).expect("record round-trips");
        assert_eq!(back, record);
    }
}
