#[derive(Debug, Clone, Default)]
pub(super) struct RenderedAnswerShapeFacts {
    pub(super) heading_present: bool,
    pub(super) rendered_required_section_label_count: usize,
    pub(super) rendered_required_section_label_floor_met: bool,
    pub(super) legacy_source_cluster_header_count: usize,
    pub(super) comparison_label_count: usize,
    pub(super) single_snapshot_heading_present: bool,
    pub(super) single_snapshot_metric_line_count: usize,
    pub(super) single_snapshot_support_url_count: usize,
    pub(super) single_snapshot_temporal_signal_present: bool,
}

#[derive(Debug, Clone, Default)]
pub(super) struct RenderedAnswerContractFacts {
    pub(super) rendered_required_section_count: usize,
    pub(super) query_grounded_required_section_count: usize,
    pub(super) required_narrative_sections: usize,
    pub(super) rendered_single_block_narrative_sections: usize,
    pub(super) required_evidence_sections: usize,
    pub(super) rendered_evidence_block_count: usize,
    pub(super) qualifying_evidence_sections: usize,
    pub(super) qualifying_aggregated_narrative_sections: usize,
    pub(super) standard_identifier_count: usize,
    pub(super) required_standard_identifier_count: usize,
    pub(super) standard_identifier_group_floor: usize,
    pub(super) authority_standard_identifier_count: usize,
    pub(super) required_authority_standard_identifier_count: usize,
    pub(super) summary_inventory_identifier_count: usize,
    pub(super) summary_inventory_required_identifier_count: usize,
    pub(super) summary_inventory_optional_identifier_count: usize,
    pub(super) summary_inventory_authority_identifier_count: usize,
    pub(super) standard_identifier_authority_source_count: usize,
    pub(super) available_standard_identifier_authority_source_count: usize,
    pub(super) primary_authority_source_count: usize,
    pub(super) required_primary_authority_source_count: usize,
    pub(super) citation_urls: Vec<String>,
    pub(super) successful_citation_url_count: usize,
    pub(super) unread_citation_url_count: usize,
    pub(super) run_date: Option<String>,
    pub(super) run_timestamp_iso_utc: Option<String>,
    pub(super) overall_confidence: Option<String>,
    pub(super) required_section_floor_met: bool,
    pub(super) query_grounding_floor_met: bool,
    pub(super) standard_identifier_floor_met: bool,
    pub(super) authority_standard_identifier_floor_met: bool,
    pub(super) summary_inventory_floor_met: bool,
    pub(super) narrative_aggregation_floor_met: bool,
    pub(super) evidence_block_floor_met: bool,
    pub(super) primary_authority_source_floor_met: bool,
    pub(super) citation_read_backing_floor_met: bool,
    pub(super) temporal_anchor_floor_met: bool,
    pub(super) postamble_floor_met: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum RenderedSummaryLayoutProfile {
    DocumentReport,
    SingleSnapshot,
    SourcedAnswer,
    SourceCollection,
    Other,
}

impl RenderedSummaryLayoutProfile {
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::DocumentReport => "document_report",
            Self::SingleSnapshot => "single_snapshot",
            Self::SourcedAnswer => "sourced_answer",
            Self::SourceCollection => "source_collection",
            Self::Other => "other",
        }
    }
}

#[derive(Debug, Clone)]
pub(crate) struct FinalWebCompletionFacts {
    pub selected_source_urls: Vec<String>,
    pub evidence_selected_source_total: usize,
    pub evidence_selected_source_compatible: usize,
    pub evidence_selected_source_quality_floor_met: bool,
    pub evidence_selected_source_identifier_coverage_floor_met: bool,
    pub selected_primary_authority_source_count: usize,
    pub available_primary_authority_source_count: usize,
    pub attempted_primary_authority_source_count: usize,
    pub local_business_targets: Vec<String>,
    pub matched_local_business_targets: Vec<String>,
    pub local_business_source_urls: Vec<String>,
    pub local_business_menu_surface_required: bool,
    pub local_business_menu_surface_source_urls: Vec<String>,
    pub local_business_menu_surface_floor_met: bool,
    pub local_business_menu_inventory_source_urls: Vec<String>,
    pub local_business_menu_inventory_items: Vec<String>,
    pub local_business_menu_inventory_total_item_count: usize,
    pub local_business_menu_inventory_floor_met: bool,
    pub required_source_cluster_floor: usize,
    pub required_citations_per_source_cluster: usize,
    pub answer_required_sections: Vec<String>,
    pub answer_required_section_count: usize,
    pub answer_rendered_required_section_count: usize,
    pub answer_query_grounded_required_section_count: usize,
    pub answer_required_narrative_sections: usize,
    pub answer_single_block_narrative_sections: usize,
    pub answer_required_evidence_sections: usize,
    pub answer_rendered_evidence_block_count: usize,
    pub answer_qualifying_evidence_sections: usize,
    pub answer_required_supporting_fragment_floor: usize,
    pub answer_aggregated_narrative_sections: usize,
    pub evidence_standard_identifier_count: usize,
    pub evidence_required_standard_identifier_count: usize,
    pub evidence_standard_identifier_group_floor: usize,
    pub evidence_authority_standard_identifier_count: usize,
    pub evidence_required_authority_standard_identifier_count: usize,
    pub evidence_inventory_identifier_count: usize,
    pub evidence_inventory_required_identifier_count: usize,
    pub evidence_inventory_optional_identifier_count: usize,
    pub evidence_inventory_authority_identifier_count: usize,
    pub evidence_standard_identifier_authority_source_count: usize,
    pub evidence_available_standard_identifier_authority_source_count: usize,
    pub answer_required_primary_authority_source_count: usize,
    pub evidence_successful_citation_url_count: usize,
    pub evidence_unread_citation_url_count: usize,
    pub trace_run_date: String,
    pub trace_run_timestamp_iso_utc: String,
    pub trace_overall_confidence: String,
    pub answer_query_layout_expected: bool,
    pub answer_layout_profile: String,
    pub answer_rendered_layout_profile: String,
    pub answer_render_heading_floor_met: bool,
    pub answer_rendered_required_section_label_count: usize,
    pub answer_rendered_required_section_label_floor_met: bool,
    pub answer_legacy_source_cluster_header_count: usize,
    pub answer_comparison_label_count: usize,
    pub observed_source_clusters: usize,
    pub source_cluster_floor_met: bool,
    pub source_cluster_citation_floor_met: bool,
    pub comparison_required: bool,
    pub comparison_ready: bool,
    pub answer_document_layout_met: bool,
    pub answer_legacy_source_cluster_headers_absent: bool,
    pub answer_comparison_absent: bool,
    pub answer_required_section_floor_met: bool,
    pub answer_query_grounding_floor_met: bool,
    pub evidence_standard_identifier_floor_met: bool,
    pub evidence_authority_standard_identifier_floor_met: bool,
    pub evidence_inventory_floor_met: bool,
    pub answer_narrative_aggregation_floor_met: bool,
    pub answer_evidence_block_floor_met: bool,
    pub evidence_primary_authority_source_floor_met: bool,
    pub evidence_citation_read_backing_floor_met: bool,
    pub trace_temporal_anchor_floor_met: bool,
    pub trace_metadata_floor_met: bool,
    pub single_snapshot_metric_grounding: bool,
    pub single_snapshot_required_citation_count: usize,
    pub single_snapshot_rendered_layout_met: bool,
    pub single_snapshot_rendered_metric_line_count: usize,
    pub single_snapshot_rendered_metric_line_floor_met: bool,
    pub single_snapshot_rendered_support_url_count: usize,
    pub single_snapshot_rendered_support_url_floor_met: bool,
    pub single_snapshot_rendered_read_backed_url_count: usize,
    pub single_snapshot_rendered_read_backed_url_floor_met: bool,
    pub single_snapshot_rendered_temporal_signal_present: bool,
    pub market_quote_grounding_required: bool,
    pub market_quote_grounding_source_count: usize,
    pub market_quote_grounding_floor_met: bool,
    pub rendered_summary_semantic_floor_met: bool,
}

#[derive(Debug, Clone)]
pub(crate) struct FinalWebSummaryCandidate {
    pub provider: &'static str,
    pub summary: String,
}

#[derive(Debug, Clone)]
pub(crate) struct FinalWebSummaryCandidateEvaluation {
    pub provider: &'static str,
    pub contract_ready: bool,
    pub facts: FinalWebCompletionFacts,
}

#[derive(Debug, Clone)]
pub(crate) struct FinalWebSummarySelection {
    pub provider: &'static str,
    pub summary: String,
    pub contract_ready: bool,
    pub facts: FinalWebCompletionFacts,
    pub evaluations: Vec<FinalWebSummaryCandidateEvaluation>,
}
