use super::facts::{
    final_web_completion_contract_ready, final_web_completion_facts,
    final_web_completion_facts_with_rendered_summary, FinalWebCompletionFacts,
};
use super::*;
use crate::agentic::runtime::service::tool_execution::emit_execution_contract_receipt_event_with_observation;
use crate::agentic::runtime::service::RuntimeAgentService;

fn append_final_web_completion_receipts_from_facts(
    facts: &FinalWebCompletionFacts,
    verification_checks: &mut Vec<String>,
) {
    verification_checks.push(format!(
        "web_final_output_contract_ready={}",
        final_web_completion_contract_ready(facts)
    ));
    if !facts.selected_source_urls.is_empty() {
        verification_checks.push(format!(
            "web_final_selected_source_url_values={}",
            facts.selected_source_urls.join(" | ")
        ));
    }
    verification_checks.push(format!(
        "web_final_selected_source_total={}",
        facts.evidence_selected_source_total
    ));
    verification_checks.push(format!(
        "web_final_selected_source_compatible={}",
        facts.evidence_selected_source_compatible
    ));
    verification_checks.push(format!(
        "web_final_selected_source_quality_floor_met={}",
        facts.evidence_selected_source_quality_floor_met
    ));
    verification_checks.push(format!(
        "web_final_selected_source_identifier_coverage_floor_met={}",
        facts.evidence_selected_source_identifier_coverage_floor_met
    ));
    if !facts.local_business_targets.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_entity_targets={}",
            facts.local_business_targets.join(" | ")
        ));
    }
    if !facts.matched_local_business_targets.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_entity_matched={}",
            facts.matched_local_business_targets.join(" | ")
        ));
    }
    if !facts.local_business_source_urls.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_entity_source_values={}",
            facts.local_business_source_urls.join(" | ")
        ));
    }
    verification_checks.push(format!(
        "web_final_local_business_menu_surface_required={}",
        facts.local_business_menu_surface_required
    ));
    verification_checks.push(format!(
        "web_final_local_business_menu_surface_floor_met={}",
        facts.local_business_menu_surface_floor_met
    ));
    if !facts.local_business_menu_surface_source_urls.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_menu_surface_source_values={}",
            facts.local_business_menu_surface_source_urls.join(" | ")
        ));
    }
    verification_checks.push(format!(
        "web_final_local_business_menu_inventory_total_item_count={}",
        facts.local_business_menu_inventory_total_item_count
    ));
    verification_checks.push(format!(
        "web_final_local_business_menu_inventory_floor_met={}",
        facts.local_business_menu_inventory_floor_met
    ));
    if !facts.local_business_menu_inventory_source_urls.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_menu_inventory_source_values={}",
            facts.local_business_menu_inventory_source_urls.join(" | ")
        ));
    }
    if !facts.local_business_menu_inventory_items.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_menu_inventory_item_values={}",
            facts.local_business_menu_inventory_items.join(" | ")
        ));
    }
    if !facts.answer_required_sections.is_empty() {
        verification_checks.push(format!(
            "web_final_answer_required_section_keys={}",
            facts.answer_required_sections.join(" | ")
        ));
    }
    if !facts.answer_document_layout_met {
        verification_checks.push(format!(
            "web_final_source_clusters_observed={}",
            facts.observed_source_clusters
        ));
        verification_checks.push(format!(
            "web_final_source_cluster_floor_met={}",
            facts.source_cluster_floor_met
        ));
        verification_checks.push(format!(
            "web_final_source_cluster_citation_floor_met={}",
            facts.source_cluster_citation_floor_met
        ));
    }
    verification_checks.push(format!(
        "web_final_comparison_required={}",
        facts.comparison_required
    ));
    verification_checks.push(format!(
        "web_final_comparison_ready={}",
        facts.comparison_ready
    ));
    verification_checks.push(format!(
        "web_final_answer_layout_profile={}",
        facts.answer_layout_profile
    ));
    verification_checks.push(format!(
        "web_final_answer_query_layout_expected={}",
        facts.answer_query_layout_expected
    ));
    verification_checks.push(format!(
        "web_final_answer_rendered_layout_profile={}",
        facts.answer_rendered_layout_profile
    ));
    verification_checks.push(format!(
        "web_final_answer_document_layout_met={}",
        facts.answer_document_layout_met
    ));
    verification_checks.push(format!(
        "web_final_answer_render_heading_floor_met={}",
        facts.answer_render_heading_floor_met
    ));
    verification_checks.push(format!(
        "web_final_answer_rendered_required_section_label_count={}",
        facts.answer_rendered_required_section_label_count
    ));
    verification_checks.push(format!(
        "web_final_answer_rendered_required_section_label_floor_met={}",
        facts.answer_rendered_required_section_label_floor_met
    ));
    verification_checks.push(format!(
        "web_final_answer_legacy_source_cluster_header_count={}",
        facts.answer_legacy_source_cluster_header_count
    ));
    verification_checks.push(format!(
        "web_final_answer_legacy_source_cluster_headers_absent={}",
        facts.answer_legacy_source_cluster_headers_absent
    ));
    verification_checks.push(format!(
        "web_final_answer_comparison_label_count={}",
        facts.answer_comparison_label_count
    ));
    verification_checks.push(format!(
        "web_final_answer_comparison_absent={}",
        facts.answer_comparison_absent
    ));
    verification_checks.push(format!(
        "web_final_answer_required_section_count={}",
        facts.answer_required_section_count
    ));
    verification_checks.push(format!(
        "web_final_answer_rendered_required_section_count={}",
        facts.answer_rendered_required_section_count
    ));
    verification_checks.push(format!(
        "web_final_answer_required_narrative_sections={}",
        facts.answer_required_narrative_sections
    ));
    verification_checks.push(format!(
        "web_final_answer_single_block_narrative_sections={}",
        facts.answer_single_block_narrative_sections
    ));
    verification_checks.push(format!(
        "web_final_answer_required_evidence_sections={}",
        facts.answer_required_evidence_sections
    ));
    verification_checks.push(format!(
        "web_final_answer_rendered_evidence_block_count={}",
        facts.answer_rendered_evidence_block_count
    ));
    verification_checks.push(format!(
        "web_final_answer_qualifying_evidence_sections={}",
        facts.answer_qualifying_evidence_sections
    ));
    verification_checks.push(format!(
        "web_final_answer_required_supporting_fragment_floor={}",
        facts.answer_required_supporting_fragment_floor
    ));
    verification_checks.push(format!(
        "web_final_answer_aggregated_narrative_sections={}",
        facts.answer_aggregated_narrative_sections
    ));
    verification_checks.push(format!(
        "web_final_answer_query_grounded_required_section_count={}",
        facts.answer_query_grounded_required_section_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_standard_identifier_count={}",
        facts.evidence_standard_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_required_standard_identifier_count={}",
        facts.evidence_required_standard_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_standard_identifier_group_floor={}",
        facts.evidence_standard_identifier_group_floor
    ));
    verification_checks.push(format!(
        "web_final_evidence_authority_standard_identifier_count={}",
        facts.evidence_authority_standard_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_required_authority_standard_identifier_count={}",
        facts.evidence_required_authority_standard_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_inventory_identifier_count={}",
        facts.evidence_inventory_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_inventory_required_identifier_count={}",
        facts.evidence_inventory_required_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_inventory_optional_identifier_count={}",
        facts.evidence_inventory_optional_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_inventory_authority_identifier_count={}",
        facts.evidence_inventory_authority_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_answer_required_section_floor_met={}",
        facts.answer_required_section_floor_met
    ));
    verification_checks.push(format!(
        "web_final_answer_query_grounding_floor_met={}",
        facts.answer_query_grounding_floor_met
    ));
    verification_checks.push(format!(
        "web_final_evidence_standard_identifier_floor_met={}",
        facts.evidence_standard_identifier_floor_met
    ));
    verification_checks.push(format!(
        "web_final_evidence_authority_standard_identifier_floor_met={}",
        facts.evidence_authority_standard_identifier_floor_met
    ));
    verification_checks.push(format!(
        "web_final_evidence_inventory_floor_met={}",
        facts.evidence_inventory_floor_met
    ));
    verification_checks.push(format!(
        "web_final_answer_narrative_aggregation_floor_met={}",
        facts.answer_narrative_aggregation_floor_met
    ));
    verification_checks.push(format!(
        "web_final_answer_evidence_block_floor_met={}",
        facts.answer_evidence_block_floor_met
    ));
    verification_checks.push(format!(
        "web_final_selected_primary_authority_source_count={}",
        facts.selected_primary_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_standard_identifier_authority_source_count={}",
        facts.evidence_standard_identifier_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_successful_citation_url_count={}",
        facts.evidence_successful_citation_url_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_unread_citation_url_count={}",
        facts.evidence_unread_citation_url_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_citation_read_backing_floor_met={}",
        facts.evidence_citation_read_backing_floor_met
    ));
    verification_checks.push(format!(
        "web_final_evidence_available_standard_identifier_authority_source_count={}",
        facts.evidence_available_standard_identifier_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_available_primary_authority_source_count={}",
        facts.available_primary_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_attempted_primary_authority_source_count={}",
        facts.attempted_primary_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_evidence_primary_authority_source_floor_met={}",
        facts.evidence_primary_authority_source_floor_met
    ));
    verification_checks.push(format!(
        "web_final_trace_temporal_anchor_floor_met={}",
        facts.trace_temporal_anchor_floor_met
    ));
    verification_checks.push(format!(
        "web_final_trace_metadata_floor_met={}",
        facts.trace_metadata_floor_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_metric_grounding={}",
        facts.single_snapshot_metric_grounding
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_required_citation_count={}",
        facts.single_snapshot_required_citation_count
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_layout_met={}",
        facts.single_snapshot_rendered_layout_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_metric_line_count={}",
        facts.single_snapshot_rendered_metric_line_count
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_metric_line_floor_met={}",
        facts.single_snapshot_rendered_metric_line_floor_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_support_url_count={}",
        facts.single_snapshot_rendered_support_url_count
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_support_url_floor_met={}",
        facts.single_snapshot_rendered_support_url_floor_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_read_backed_url_count={}",
        facts.single_snapshot_rendered_read_backed_url_count
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_read_backed_url_floor_met={}",
        facts.single_snapshot_rendered_read_backed_url_floor_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_temporal_signal_present={}",
        facts.single_snapshot_rendered_temporal_signal_present
    ));
}

pub(crate) fn append_final_web_completion_receipts(
    pending: &PendingSearchCompletion,
    reason: WebPipelineCompletionReason,
    verification_checks: &mut Vec<String>,
) {
    let facts = final_web_completion_facts(pending, reason);
    append_final_web_completion_receipts_from_facts(&facts, verification_checks);
}

pub(crate) fn append_final_web_completion_receipts_with_rendered_summary(
    pending: &PendingSearchCompletion,
    reason: WebPipelineCompletionReason,
    rendered_summary: &str,
    verification_checks: &mut Vec<String>,
) {
    let facts = final_web_completion_facts_with_rendered_summary(pending, reason, rendered_summary);
    append_final_web_completion_receipts_from_facts(&facts, verification_checks);
}

pub(crate) fn emit_final_web_completion_contract_receipts(
    service: &RuntimeAgentService,
    session_id: [u8; 32],
    step_index: u32,
    intent_id: &str,
    facts: &FinalWebCompletionFacts,
) {
    let emit_receipt = |key: &str,
                        satisfied: bool,
                        probe_source: &str,
                        observed_value: &str,
                        evidence_type: &str| {
        let evidence_material = format!(
            "probe_source={};observed_value={};evidence_type={}",
            probe_source, observed_value, evidence_type
        );
        emit_execution_contract_receipt_event_with_observation(
            service,
            session_id,
            step_index,
            intent_id,
            "verification",
            key,
            satisfied,
            &evidence_material,
            Some(probe_source),
            Some(observed_value),
            Some(evidence_type),
            None,
            None,
            None,
        );
    };
    let emit_unique_string_receipts =
        |key: &str, probe_source: &str, evidence_type: &str, values: &[String]| {
            let mut seen = BTreeSet::new();
            for value in values
                .iter()
                .map(|value| value.trim())
                .filter(|value| !value.is_empty())
            {
                if !seen.insert(value.to_string()) {
                    continue;
                }
                emit_receipt(key, true, probe_source, value, evidence_type);
            }
        };

    if !facts.answer_document_layout_met {
        emit_receipt(
            "source_clusters_observed",
            true,
            "web.pipeline.completion.source_clusters_observed.v1",
            &facts.observed_source_clusters.to_string(),
            "scalar",
        );
        emit_receipt(
            "source_cluster_floor",
            facts.source_cluster_floor_met,
            "web.pipeline.completion.source_clusters.v1",
            &facts.observed_source_clusters.to_string(),
            "scalar",
        );
        emit_receipt(
            "source_cluster_citation_floor",
            facts.source_cluster_citation_floor_met,
            "web.pipeline.completion.source_cluster_citations.v1",
            &facts.observed_source_clusters.to_string(),
            "scalar",
        );
    }
    emit_receipt(
        "local_business_menu_surface_required",
        true,
        "web.pipeline.completion.local_business_menu_surface_required.v1",
        &facts.local_business_menu_surface_required.to_string(),
        "scalar",
    );
    emit_receipt(
        "local_business_menu_surface_floor",
        facts.local_business_menu_surface_floor_met,
        "web.pipeline.completion.local_business_menu_surface.v1",
        &format!(
            "required={};selected_menu_surface_sources={};required_source_cluster_floor={}",
            facts.local_business_menu_surface_required,
            facts.local_business_menu_surface_source_urls.len(),
            facts.required_source_cluster_floor
        ),
        "summary",
    );
    emit_unique_string_receipts(
        "local_business_menu_surface_source_url",
        "web.pipeline.completion.local_business_menu_surface_sources.v1",
        "url",
        &facts.local_business_menu_surface_source_urls,
    );
    emit_receipt(
        "local_business_menu_inventory_floor",
        facts.local_business_menu_inventory_floor_met,
        "web.pipeline.completion.local_business_menu_inventory.v1",
        &format!(
            "selected_menu_inventory_sources={};total_menu_inventory_items={};required_source_cluster_floor={};required_items_per_source={}",
            facts.local_business_menu_inventory_source_urls.len(),
            facts.local_business_menu_inventory_total_item_count,
            facts.required_source_cluster_floor,
            2
        ),
        "summary",
    );
    emit_receipt(
        "local_business_menu_inventory_total_item_count",
        true,
        "web.pipeline.completion.local_business_menu_inventory_total.v1",
        &facts
            .local_business_menu_inventory_total_item_count
            .to_string(),
        "scalar",
    );
    emit_unique_string_receipts(
        "local_business_menu_inventory_source_url",
        "web.pipeline.completion.local_business_menu_inventory_sources.v1",
        "url",
        &facts.local_business_menu_inventory_source_urls,
    );
    emit_unique_string_receipts(
        "local_business_menu_inventory_item",
        "web.pipeline.completion.local_business_menu_inventory_items.v1",
        "label",
        &facts.local_business_menu_inventory_items,
    );
    emit_receipt(
        "final_output_contract_ready",
        final_web_completion_contract_ready(facts),
        "web.pipeline.completion.final_output.v1",
        &format!(
            "query_requires_document_report={};rendered_layout={};document_layout_met={};required_section_floor_met={};query_grounding_floor_met={};standard_identifier_floor_met={};authority_standard_identifier_floor_met={};summary_inventory_floor_met={};evidence_block_floor_met={};citation_read_backing_floor_met={};standard_identifier_count={};required_standard_identifier_count={};required_standard_identifier_group_floor={};authority_standard_identifier_count={};required_authority_standard_identifier_count={};summary_inventory_identifier_count={};summary_inventory_required_identifier_count={};summary_inventory_optional_identifier_count={};summary_inventory_authority_identifier_count={};rendered_evidence_block_count={};required_evidence_sections={};standard_identifier_authority_source_count={};successful_citation_url_count={};unread_citation_url_count={};narrative_aggregation_floor_met={};primary_authority_source_floor_met={};temporal_anchor_floor_met={};postamble_floor_met={};source_cluster_floor_met={};source_cluster_citation_floor_met={};local_business_menu_surface_floor_met={};local_business_menu_inventory_floor_met={};local_business_menu_inventory_total_item_count={};single_snapshot_required_citation_count={};single_snapshot_rendered_support_url_count={};single_snapshot_rendered_read_backed_url_count={};semantic_floor_met={}",
            facts.answer_query_layout_expected,
            facts.answer_rendered_layout_profile,
            facts.answer_document_layout_met,
            facts.answer_required_section_floor_met,
            facts.answer_query_grounding_floor_met,
            facts.evidence_standard_identifier_floor_met,
            facts.evidence_authority_standard_identifier_floor_met,
            facts.evidence_inventory_floor_met,
            facts.answer_evidence_block_floor_met,
            facts.evidence_citation_read_backing_floor_met,
            facts.evidence_standard_identifier_count,
            facts.evidence_required_standard_identifier_count,
            facts.evidence_standard_identifier_group_floor,
            facts.evidence_authority_standard_identifier_count,
            facts.evidence_required_authority_standard_identifier_count,
            facts.evidence_inventory_identifier_count,
            facts.evidence_inventory_required_identifier_count,
            facts.evidence_inventory_optional_identifier_count,
            facts.evidence_inventory_authority_identifier_count,
            facts.answer_rendered_evidence_block_count,
            facts.answer_required_evidence_sections,
            facts.evidence_standard_identifier_authority_source_count,
            facts.evidence_successful_citation_url_count,
            facts.evidence_unread_citation_url_count,
            facts.answer_narrative_aggregation_floor_met,
            facts.evidence_primary_authority_source_floor_met,
            facts.trace_temporal_anchor_floor_met,
            facts.trace_metadata_floor_met,
            facts.source_cluster_floor_met,
            facts.source_cluster_citation_floor_met,
            facts.local_business_menu_surface_floor_met,
            facts.local_business_menu_inventory_floor_met,
            facts.local_business_menu_inventory_total_item_count,
            facts.single_snapshot_required_citation_count,
            facts.single_snapshot_rendered_support_url_count,
            facts.single_snapshot_rendered_read_backed_url_count,
            facts.rendered_summary_semantic_floor_met
        ),
        "summary",
    );
    emit_receipt(
        "comparison_ready",
        facts.comparison_ready,
        "web.pipeline.completion.comparison.v1",
        &format!("comparison_required={}", facts.comparison_required),
        "summary",
    );
    emit_receipt(
        "answer_document_layout",
        facts.answer_document_layout_met,
        "web.pipeline.completion.document_report.layout.v1",
        &format!(
            "query_requires_document_report={};contract_layout={};rendered_layout={};heading_present={};rendered_required_section_label_count={};legacy_source_cluster_header_count={};comparison_label_count={}",
            facts.answer_query_layout_expected,
            facts.answer_layout_profile,
            facts.answer_rendered_layout_profile,
            facts.answer_render_heading_floor_met,
            facts.answer_rendered_required_section_label_count,
            facts.answer_legacy_source_cluster_header_count,
            facts.answer_comparison_label_count
        ),
        "summary",
    );
    emit_receipt(
        "answer_render_heading_floor",
        facts.answer_render_heading_floor_met,
        "web.pipeline.completion.document_report.heading.v1",
        &format!(
            "contract_layout={};rendered_layout={};heading_present={}",
            facts.answer_layout_profile,
            facts.answer_rendered_layout_profile,
            facts.answer_render_heading_floor_met
        ),
        "summary",
    );
    emit_receipt(
        "answer_rendered_required_section_label_floor",
        facts.answer_rendered_required_section_label_floor_met,
        "web.pipeline.completion.document_report.rendered_sections.v1",
        &format!(
            "rendered_required_section_label_count={};required_section_count={}",
            facts.answer_rendered_required_section_label_count, facts.answer_required_section_count
        ),
        "summary",
    );
    emit_receipt(
        "answer_legacy_source_cluster_headers_absent",
        facts.answer_legacy_source_cluster_headers_absent,
        "web.pipeline.completion.document_report.legacy_source_cluster_headers.v1",
        &format!(
            "contract_layout={};rendered_layout={};legacy_source_cluster_headers_rendered={};legacy_source_cluster_header_count={}",
            facts.answer_layout_profile,
            facts.answer_rendered_layout_profile,
            !facts.answer_legacy_source_cluster_headers_absent,
            facts.answer_legacy_source_cluster_header_count
        ),
        "summary",
    );
    emit_receipt(
        "answer_comparison_absent",
        facts.answer_comparison_absent,
        "web.pipeline.completion.document_report.comparison.v1",
        &format!(
            "contract_layout={};rendered_layout={};comparison_required={};comparison_rendered={};comparison_label_count={}",
            facts.answer_layout_profile,
            facts.answer_rendered_layout_profile,
            facts.comparison_required,
            !facts.answer_comparison_absent,
            facts.answer_comparison_label_count
        ),
        "summary",
    );
    emit_receipt(
        "answer_required_section_floor",
        facts.answer_required_section_floor_met,
        "web.pipeline.completion.document_report.sections.v2",
        &format!(
            "rendered_required_sections={};required_section_count={};required_sections={}",
            facts.answer_rendered_required_section_count,
            facts.answer_required_section_count,
            facts.answer_required_sections.join("|")
        ),
        "summary",
    );
    emit_receipt(
        "answer_query_grounding_floor",
        facts.answer_query_grounding_floor_met,
        "web.pipeline.completion.document_report.query_grounding.v1",
        &format!(
            "grounded_required_sections={};required_section_count={}",
            facts.answer_query_grounded_required_section_count, facts.answer_required_section_count
        ),
        "summary",
    );
    emit_receipt(
        "evidence_standard_identifier_floor",
        facts.evidence_standard_identifier_floor_met,
        "web.pipeline.completion.document_report.standard_identifiers.v1",
        &format!(
            "standard_identifier_count={};required_standard_identifier_count={};required_standard_identifier_group_floor={};standard_identifier_authority_source_count={};available_standard_identifier_authority_source_count={}",
            facts.evidence_standard_identifier_count,
            facts.evidence_required_standard_identifier_count,
            facts.evidence_standard_identifier_group_floor,
            facts.evidence_standard_identifier_authority_source_count,
            facts.evidence_available_standard_identifier_authority_source_count
        ),
        "summary",
    );
    emit_receipt(
        "evidence_authority_standard_identifier_floor",
        facts.evidence_authority_standard_identifier_floor_met,
        "web.pipeline.completion.document_report.authority_standard_identifiers.v1",
        &format!(
            "authority_standard_identifier_count={};required_authority_standard_identifier_count={};required_standard_identifier_group_floor={};standard_identifier_authority_source_count={};available_standard_identifier_authority_source_count={}",
            facts.evidence_authority_standard_identifier_count,
            facts.evidence_required_authority_standard_identifier_count,
            facts.evidence_standard_identifier_group_floor,
            facts.evidence_standard_identifier_authority_source_count,
            facts.evidence_available_standard_identifier_authority_source_count
        ),
        "summary",
    );
    emit_receipt(
        "evidence_inventory_floor",
        facts.evidence_inventory_floor_met,
        "web.pipeline.completion.document_report.summary_inventory.v1",
        &format!(
            "summary_inventory_identifier_count={};summary_inventory_required_identifier_count={};summary_inventory_optional_identifier_count={};summary_inventory_authority_identifier_count={};required_standard_identifier_group_floor={}",
            facts.evidence_inventory_identifier_count,
            facts.evidence_inventory_required_identifier_count,
            facts.evidence_inventory_optional_identifier_count,
            facts.evidence_inventory_authority_identifier_count,
            facts.evidence_standard_identifier_group_floor
        ),
        "summary",
    );
    emit_receipt(
        "answer_narrative_aggregation_floor",
        facts.answer_narrative_aggregation_floor_met,
        "web.pipeline.completion.document_report.narrative_aggregation.v1",
        &format!(
            "required_narrative_sections={};single_block_narrative_sections={};aggregated_narrative_sections={};required_supporting_fragment_floor={}",
            facts.answer_required_narrative_sections,
            facts.answer_single_block_narrative_sections,
            facts.answer_aggregated_narrative_sections,
            facts.answer_required_supporting_fragment_floor
        ),
        "summary",
    );
    emit_receipt(
        "answer_evidence_block_floor",
        facts.answer_evidence_block_floor_met,
        "web.pipeline.completion.document_report.evidence_blocks.v1",
        &format!(
            "rendered_evidence_block_count={};required_supporting_fragment_floor={};required_evidence_sections={};qualifying_evidence_sections={}",
            facts.answer_rendered_evidence_block_count,
            facts.answer_required_supporting_fragment_floor,
            facts.answer_required_evidence_sections,
            facts.answer_qualifying_evidence_sections
        ),
        "summary",
    );
    emit_receipt(
        "evidence_primary_authority_source_floor",
        facts.evidence_primary_authority_source_floor_met,
        "web.pipeline.completion.document_report.primary_authority.v1",
        &format!(
            "selected_primary_authority_sources={};required_primary_authority_sources={};available_primary_authority_sources={};attempted_primary_authority_sources={}",
            facts.selected_primary_authority_source_count,
            facts.answer_required_primary_authority_source_count,
            facts.available_primary_authority_source_count,
            facts.attempted_primary_authority_source_count
        ),
        "summary",
    );
    emit_receipt(
        "evidence_citation_read_backing_floor",
        facts.evidence_citation_read_backing_floor_met,
        "web.pipeline.completion.document_report.citation_backing.v1",
        &format!(
            "successful_citation_url_count={};unread_citation_url_count={};required_supporting_fragment_floor={}",
            facts.evidence_successful_citation_url_count,
            facts.evidence_unread_citation_url_count,
            facts.answer_required_supporting_fragment_floor
        ),
        "summary",
    );
    emit_receipt(
        "trace_temporal_anchor_floor",
        facts.trace_temporal_anchor_floor_met,
        "web.pipeline.completion.document_report.temporal_anchor.v1",
        &format!(
            "run_date={};run_timestamp_iso_utc={}",
            facts.trace_run_date, facts.trace_run_timestamp_iso_utc
        ),
        "summary",
    );
    emit_receipt(
        "trace_metadata_floor",
        facts.trace_metadata_floor_met,
        "web.pipeline.completion.document_report.postamble.v1",
        &format!(
            "temporal_anchor={};overall_confidence={};required_citations_per_source_cluster={}",
            facts.trace_temporal_anchor_floor_met,
            facts.trace_overall_confidence,
            facts.required_citations_per_source_cluster
        ),
        "summary",
    );
    emit_receipt(
        "single_snapshot_metric_grounding",
        facts.single_snapshot_metric_grounding,
        "web.pipeline.completion.single_snapshot_metric.v1",
        &facts.single_snapshot_metric_grounding.to_string(),
        "bool",
    );
    emit_receipt(
        "single_snapshot_rendered_layout",
        facts.single_snapshot_rendered_layout_met,
        "web.pipeline.completion.single_snapshot.layout.v1",
        &format!(
            "rendered_layout={};legacy_source_cluster_header_count={};comparison_label_count={}",
            facts.answer_rendered_layout_profile,
            facts.answer_legacy_source_cluster_header_count,
            facts.answer_comparison_label_count
        ),
        "summary",
    );
    emit_receipt(
        "single_snapshot_metric_line_floor",
        facts.single_snapshot_rendered_metric_line_floor_met,
        "web.pipeline.completion.single_snapshot.metric_lines.v1",
        &facts.single_snapshot_rendered_metric_line_count.to_string(),
        "scalar",
    );
    emit_receipt(
        "single_snapshot_support_url_floor",
        facts.single_snapshot_rendered_support_url_floor_met,
        "web.pipeline.completion.single_snapshot.support_urls.v1",
        &format!(
            "rendered_support_urls={};required_support_urls={}",
            facts.single_snapshot_rendered_support_url_count,
            facts.single_snapshot_required_citation_count
        ),
        "summary",
    );
    emit_receipt(
        "single_snapshot_read_backed_url_floor",
        facts.single_snapshot_rendered_read_backed_url_floor_met,
        "web.pipeline.completion.single_snapshot.read_backed_urls.v1",
        &format!(
            "read_backed_urls={};rendered_support_urls={};required_support_urls={}",
            facts.single_snapshot_rendered_read_backed_url_count,
            facts.single_snapshot_rendered_support_url_count,
            facts.single_snapshot_required_citation_count
        ),
        "summary",
    );
    emit_receipt(
        "single_snapshot_temporal_signal",
        facts.single_snapshot_rendered_temporal_signal_present,
        "web.pipeline.completion.single_snapshot.temporal_signal.v1",
        &facts
            .single_snapshot_rendered_temporal_signal_present
            .to_string(),
        "bool",
    );
    emit_unique_string_receipts(
        "selected_source_url",
        "web.pipeline.completion.selected_sources.v1",
        "url",
        &facts.selected_source_urls,
    );
    emit_unique_string_receipts(
        "local_business_entity_name",
        "web.pipeline.completion.local_business_entities.v1",
        "entity_name",
        &facts.matched_local_business_targets,
    );
    emit_unique_string_receipts(
        "local_business_entity_source_url",
        "web.pipeline.completion.local_business_entity_sources.v1",
        "url",
        &facts.local_business_source_urls,
    );
}
