use super::facts::{
    final_web_completion_contract_ready, final_web_completion_facts,
    final_web_completion_facts_with_rendered_summary, FinalWebCompletionFacts,
};
use super::*;
use crate::agentic::runtime::service::tool_execution::emit_execution_contract_receipt_event_with_observation;
use crate::agentic::runtime::service::RuntimeAgentService;

fn append_final_web_completion_receipts_from_facts(
    facts: &FinalWebCompletionFacts,
    verification_checks: &mut Vec<String>,
) {
    verification_checks.push(format!(
        "web_final_output_contract_ready={}",
        final_web_completion_contract_ready(facts)
    ));
    if !facts.selected_source_urls.is_empty() {
        verification_checks.push(format!(
            "web_final_selected_source_url_values={}",
            facts.selected_source_urls.join(" | ")
        ));
    }
    verification_checks.push(format!(
        "web_final_selected_source_total={}",
        facts.briefing_selected_source_total
    ));
    verification_checks.push(format!(
        "web_final_selected_source_compatible={}",
        facts.briefing_selected_source_compatible
    ));
    verification_checks.push(format!(
        "web_final_selected_source_quality_floor_met={}",
        facts.briefing_selected_source_quality_floor_met
    ));
    verification_checks.push(format!(
        "web_final_selected_source_identifier_coverage_floor_met={}",
        facts.briefing_selected_source_identifier_coverage_floor_met
    ));
    if !facts.local_business_targets.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_entity_targets={}",
            facts.local_business_targets.join(" | ")
        ));
    }
    if !facts.matched_local_business_targets.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_entity_matched={}",
            facts.matched_local_business_targets.join(" | ")
        ));
    }
    if !facts.local_business_source_urls.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_entity_source_values={}",
            facts.local_business_source_urls.join(" | ")
        ));
    }
    verification_checks.push(format!(
        "web_final_local_business_menu_surface_required={}",
        facts.local_business_menu_surface_required
    ));
    verification_checks.push(format!(
        "web_final_local_business_menu_surface_floor_met={}",
        facts.local_business_menu_surface_floor_met
    ));
    if !facts.local_business_menu_surface_source_urls.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_menu_surface_source_values={}",
            facts.local_business_menu_surface_source_urls.join(" | ")
        ));
    }
    verification_checks.push(format!(
        "web_final_local_business_menu_inventory_total_item_count={}",
        facts.local_business_menu_inventory_total_item_count
    ));
    verification_checks.push(format!(
        "web_final_local_business_menu_inventory_floor_met={}",
        facts.local_business_menu_inventory_floor_met
    ));
    if !facts.local_business_menu_inventory_source_urls.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_menu_inventory_source_values={}",
            facts.local_business_menu_inventory_source_urls.join(" | ")
        ));
    }
    if !facts.local_business_menu_inventory_items.is_empty() {
        verification_checks.push(format!(
            "web_final_local_business_menu_inventory_item_values={}",
            facts.local_business_menu_inventory_items.join(" | ")
        ));
    }
    if !facts.briefing_required_sections.is_empty() {
        verification_checks.push(format!(
            "web_final_briefing_required_section_keys={}",
            facts.briefing_required_sections.join(" | ")
        ));
    }
    if !facts.briefing_document_layout_met {
        verification_checks.push(format!(
            "web_final_story_slots_observed={}",
            facts.observed_story_slots
        ));
        verification_checks.push(format!(
            "web_final_story_slot_floor_met={}",
            facts.story_slot_floor_met
        ));
        verification_checks.push(format!(
            "web_final_story_citation_floor_met={}",
            facts.story_citation_floor_met
        ));
    }
    verification_checks.push(format!(
        "web_final_comparison_required={}",
        facts.comparison_required
    ));
    verification_checks.push(format!(
        "web_final_comparison_ready={}",
        facts.comparison_ready
    ));
    verification_checks.push(format!(
        "web_final_briefing_layout_profile={}",
        facts.briefing_layout_profile
    ));
    verification_checks.push(format!(
        "web_final_briefing_query_layout_expected={}",
        facts.briefing_query_layout_expected
    ));
    verification_checks.push(format!(
        "web_final_briefing_rendered_layout_profile={}",
        facts.briefing_rendered_layout_profile
    ));
    verification_checks.push(format!(
        "web_final_briefing_document_layout_met={}",
        facts.briefing_document_layout_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_render_heading_floor_met={}",
        facts.briefing_render_heading_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_rendered_required_section_label_count={}",
        facts.briefing_rendered_required_section_label_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_rendered_required_section_label_floor_met={}",
        facts.briefing_rendered_required_section_label_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_story_header_count={}",
        facts.briefing_story_header_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_story_headers_absent={}",
        facts.briefing_story_headers_absent
    ));
    verification_checks.push(format!(
        "web_final_briefing_comparison_label_count={}",
        facts.briefing_comparison_label_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_comparison_absent={}",
        facts.briefing_comparison_absent
    ));
    verification_checks.push(format!(
        "web_final_briefing_required_section_count={}",
        facts.briefing_required_section_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_rendered_required_section_count={}",
        facts.briefing_rendered_required_section_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_required_narrative_sections={}",
        facts.briefing_required_narrative_sections
    ));
    verification_checks.push(format!(
        "web_final_briefing_single_block_narrative_sections={}",
        facts.briefing_single_block_narrative_sections
    ));
    verification_checks.push(format!(
        "web_final_briefing_required_evidence_sections={}",
        facts.briefing_required_evidence_sections
    ));
    verification_checks.push(format!(
        "web_final_briefing_rendered_evidence_block_count={}",
        facts.briefing_rendered_evidence_block_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_qualifying_evidence_sections={}",
        facts.briefing_qualifying_evidence_sections
    ));
    verification_checks.push(format!(
        "web_final_briefing_required_supporting_fragment_floor={}",
        facts.briefing_required_supporting_fragment_floor
    ));
    verification_checks.push(format!(
        "web_final_briefing_aggregated_narrative_sections={}",
        facts.briefing_aggregated_narrative_sections
    ));
    verification_checks.push(format!(
        "web_final_briefing_query_grounded_required_section_count={}",
        facts.briefing_query_grounded_required_section_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_standard_identifier_count={}",
        facts.briefing_standard_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_required_standard_identifier_count={}",
        facts.briefing_required_standard_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_standard_identifier_group_floor={}",
        facts.briefing_standard_identifier_group_floor
    ));
    verification_checks.push(format!(
        "web_final_briefing_authority_standard_identifier_count={}",
        facts.briefing_authority_standard_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_required_authority_standard_identifier_count={}",
        facts.briefing_required_authority_standard_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_summary_inventory_identifier_count={}",
        facts.briefing_summary_inventory_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_summary_inventory_required_identifier_count={}",
        facts.briefing_summary_inventory_required_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_summary_inventory_optional_identifier_count={}",
        facts.briefing_summary_inventory_optional_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_summary_inventory_authority_identifier_count={}",
        facts.briefing_summary_inventory_authority_identifier_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_required_section_floor_met={}",
        facts.briefing_required_section_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_query_grounding_floor_met={}",
        facts.briefing_query_grounding_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_standard_identifier_floor_met={}",
        facts.briefing_standard_identifier_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_authority_standard_identifier_floor_met={}",
        facts.briefing_authority_standard_identifier_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_summary_inventory_floor_met={}",
        facts.briefing_summary_inventory_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_narrative_aggregation_floor_met={}",
        facts.briefing_narrative_aggregation_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_evidence_block_floor_met={}",
        facts.briefing_evidence_block_floor_met
    ));
    verification_checks.push(format!(
        "web_final_selected_primary_authority_source_count={}",
        facts.selected_primary_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_standard_identifier_authority_source_count={}",
        facts.briefing_standard_identifier_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_successful_citation_url_count={}",
        facts.briefing_successful_citation_url_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_unread_citation_url_count={}",
        facts.briefing_unread_citation_url_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_citation_read_backing_floor_met={}",
        facts.briefing_citation_read_backing_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_available_standard_identifier_authority_source_count={}",
        facts.briefing_available_standard_identifier_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_available_primary_authority_source_count={}",
        facts.available_primary_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_attempted_primary_authority_source_count={}",
        facts.attempted_primary_authority_source_count
    ));
    verification_checks.push(format!(
        "web_final_briefing_primary_authority_source_floor_met={}",
        facts.briefing_primary_authority_source_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_temporal_anchor_floor_met={}",
        facts.briefing_temporal_anchor_floor_met
    ));
    verification_checks.push(format!(
        "web_final_briefing_postamble_floor_met={}",
        facts.briefing_postamble_floor_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_metric_grounding={}",
        facts.single_snapshot_metric_grounding
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_required_citation_count={}",
        facts.single_snapshot_required_citation_count
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_layout_met={}",
        facts.single_snapshot_rendered_layout_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_metric_line_count={}",
        facts.single_snapshot_rendered_metric_line_count
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_metric_line_floor_met={}",
        facts.single_snapshot_rendered_metric_line_floor_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_support_url_count={}",
        facts.single_snapshot_rendered_support_url_count
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_support_url_floor_met={}",
        facts.single_snapshot_rendered_support_url_floor_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_read_backed_url_count={}",
        facts.single_snapshot_rendered_read_backed_url_count
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_read_backed_url_floor_met={}",
        facts.single_snapshot_rendered_read_backed_url_floor_met
    ));
    verification_checks.push(format!(
        "web_final_single_snapshot_rendered_temporal_signal_present={}",
        facts.single_snapshot_rendered_temporal_signal_present
    ));
}

pub(crate) fn append_final_web_completion_receipts(
    pending: &PendingSearchCompletion,
    reason: WebPipelineCompletionReason,
    verification_checks: &mut Vec<String>,
) {
    let facts = final_web_completion_facts(pending, reason);
    append_final_web_completion_receipts_from_facts(&facts, verification_checks);
}

pub(crate) fn append_final_web_completion_receipts_with_rendered_summary(
    pending: &PendingSearchCompletion,
    reason: WebPipelineCompletionReason,
    rendered_summary: &str,
    verification_checks: &mut Vec<String>,
) {
    let facts = final_web_completion_facts_with_rendered_summary(pending, reason, rendered_summary);
    append_final_web_completion_receipts_from_facts(&facts, verification_checks);
}

pub(crate) fn emit_final_web_completion_contract_receipts(
    service: &RuntimeAgentService,
    session_id: [u8; 32],
    step_index: u32,
    intent_id: &str,
    facts: &FinalWebCompletionFacts,
) {
    let emit_receipt = |key: &str,
                        satisfied: bool,
                        probe_source: &str,
                        observed_value: &str,
                        evidence_type: &str| {
        let evidence_material = format!(
            "probe_source={};observed_value={};evidence_type={}",
            probe_source, observed_value, evidence_type
        );
        emit_execution_contract_receipt_event_with_observation(
            service,
            session_id,
            step_index,
            intent_id,
            "verification",
            key,
            satisfied,
            &evidence_material,
            Some(probe_source),
            Some(observed_value),
            Some(evidence_type),
            None,
            None,
            None,
        );
    };
    let emit_unique_string_receipts =
        |key: &str, probe_source: &str, evidence_type: &str, values: &[String]| {
            let mut seen = BTreeSet::new();
            for value in values
                .iter()
                .map(|value| value.trim())
                .filter(|value| !value.is_empty())
            {
                if !seen.insert(value.to_string()) {
                    continue;
                }
                emit_receipt(key, true, probe_source, value, evidence_type);
            }
        };

    if !facts.briefing_document_layout_met {
        emit_receipt(
            "story_slots_observed",
            true,
            "web.pipeline.completion.story_slots_observed.v1",
            &facts.observed_story_slots.to_string(),
            "scalar",
        );
        emit_receipt(
            "story_slot_floor",
            facts.story_slot_floor_met,
            "web.pipeline.completion.story_slots.v1",
            &facts.observed_story_slots.to_string(),
            "scalar",
        );
        emit_receipt(
            "story_citation_floor",
            facts.story_citation_floor_met,
            "web.pipeline.completion.story_citations.v1",
            &facts.observed_story_slots.to_string(),
            "scalar",
        );
    }
    emit_receipt(
        "local_business_menu_surface_required",
        true,
        "web.pipeline.completion.local_business_menu_surface_required.v1",
        &facts.local_business_menu_surface_required.to_string(),
        "scalar",
    );
    emit_receipt(
        "local_business_menu_surface_floor",
        facts.local_business_menu_surface_floor_met,
        "web.pipeline.completion.local_business_menu_surface.v1",
        &format!(
            "required={};selected_menu_surface_sources={};required_story_floor={}",
            facts.local_business_menu_surface_required,
            facts.local_business_menu_surface_source_urls.len(),
            facts.required_story_floor
        ),
        "summary",
    );
    emit_unique_string_receipts(
        "local_business_menu_surface_source_url",
        "web.pipeline.completion.local_business_menu_surface_sources.v1",
        "url",
        &facts.local_business_menu_surface_source_urls,
    );
    emit_receipt(
        "local_business_menu_inventory_floor",
        facts.local_business_menu_inventory_floor_met,
        "web.pipeline.completion.local_business_menu_inventory.v1",
        &format!(
            "selected_menu_inventory_sources={};total_menu_inventory_items={};required_story_floor={};required_items_per_source={}",
            facts.local_business_menu_inventory_source_urls.len(),
            facts.local_business_menu_inventory_total_item_count,
            facts.required_story_floor,
            2
        ),
        "summary",
    );
    emit_receipt(
        "local_business_menu_inventory_total_item_count",
        true,
        "web.pipeline.completion.local_business_menu_inventory_total.v1",
        &facts
            .local_business_menu_inventory_total_item_count
            .to_string(),
        "scalar",
    );
    emit_unique_string_receipts(
        "local_business_menu_inventory_source_url",
        "web.pipeline.completion.local_business_menu_inventory_sources.v1",
        "url",
        &facts.local_business_menu_inventory_source_urls,
    );
    emit_unique_string_receipts(
        "local_business_menu_inventory_item",
        "web.pipeline.completion.local_business_menu_inventory_items.v1",
        "label",
        &facts.local_business_menu_inventory_items,
    );
    emit_receipt(
        "final_output_contract_ready",
        final_web_completion_contract_ready(facts),
        "web.pipeline.completion.final_output.v1",
        &format!(
            "query_requires_document_briefing={};rendered_layout={};document_layout_met={};required_section_floor_met={};query_grounding_floor_met={};standard_identifier_floor_met={};authority_standard_identifier_floor_met={};summary_inventory_floor_met={};evidence_block_floor_met={};citation_read_backing_floor_met={};standard_identifier_count={};required_standard_identifier_count={};required_standard_identifier_group_floor={};authority_standard_identifier_count={};required_authority_standard_identifier_count={};summary_inventory_identifier_count={};summary_inventory_required_identifier_count={};summary_inventory_optional_identifier_count={};summary_inventory_authority_identifier_count={};rendered_evidence_block_count={};required_evidence_sections={};standard_identifier_authority_source_count={};successful_citation_url_count={};unread_citation_url_count={};narrative_aggregation_floor_met={};primary_authority_source_floor_met={};temporal_anchor_floor_met={};postamble_floor_met={};story_slot_floor_met={};story_citation_floor_met={};local_business_menu_surface_floor_met={};local_business_menu_inventory_floor_met={};local_business_menu_inventory_total_item_count={};single_snapshot_required_citation_count={};single_snapshot_rendered_support_url_count={};single_snapshot_rendered_read_backed_url_count={}",
            facts.briefing_query_layout_expected,
            facts.briefing_rendered_layout_profile,
            facts.briefing_document_layout_met,
            facts.briefing_required_section_floor_met,
            facts.briefing_query_grounding_floor_met,
            facts.briefing_standard_identifier_floor_met,
            facts.briefing_authority_standard_identifier_floor_met,
            facts.briefing_summary_inventory_floor_met,
            facts.briefing_evidence_block_floor_met,
            facts.briefing_citation_read_backing_floor_met,
            facts.briefing_standard_identifier_count,
            facts.briefing_required_standard_identifier_count,
            facts.briefing_standard_identifier_group_floor,
            facts.briefing_authority_standard_identifier_count,
            facts.briefing_required_authority_standard_identifier_count,
            facts.briefing_summary_inventory_identifier_count,
            facts.briefing_summary_inventory_required_identifier_count,
            facts.briefing_summary_inventory_optional_identifier_count,
            facts.briefing_summary_inventory_authority_identifier_count,
            facts.briefing_rendered_evidence_block_count,
            facts.briefing_required_evidence_sections,
            facts.briefing_standard_identifier_authority_source_count,
            facts.briefing_successful_citation_url_count,
            facts.briefing_unread_citation_url_count,
            facts.briefing_narrative_aggregation_floor_met,
            facts.briefing_primary_authority_source_floor_met,
            facts.briefing_temporal_anchor_floor_met,
            facts.briefing_postamble_floor_met,
            facts.story_slot_floor_met,
            facts.story_citation_floor_met,
            facts.local_business_menu_surface_floor_met,
            facts.local_business_menu_inventory_floor_met,
            facts.local_business_menu_inventory_total_item_count,
            facts.single_snapshot_required_citation_count,
            facts.single_snapshot_rendered_support_url_count,
            facts.single_snapshot_rendered_read_backed_url_count
        ),
        "summary",
    );
    emit_receipt(
        "comparison_ready",
        facts.comparison_ready,
        "web.pipeline.completion.comparison.v1",
        &format!("comparison_required={}", facts.comparison_required),
        "summary",
    );
    emit_receipt(
        "briefing_document_layout",
        facts.briefing_document_layout_met,
        "web.pipeline.completion.briefing.layout.v1",
        &format!(
            "query_requires_document_briefing={};contract_layout={};rendered_layout={};heading_present={};rendered_required_section_label_count={};story_header_count={};comparison_label_count={}",
            facts.briefing_query_layout_expected,
            facts.briefing_layout_profile,
            facts.briefing_rendered_layout_profile,
            facts.briefing_render_heading_floor_met,
            facts.briefing_rendered_required_section_label_count,
            facts.briefing_story_header_count,
            facts.briefing_comparison_label_count
        ),
        "summary",
    );
    emit_receipt(
        "briefing_render_heading_floor",
        facts.briefing_render_heading_floor_met,
        "web.pipeline.completion.briefing.heading.v1",
        &format!(
            "contract_layout={};rendered_layout={};heading_present={}",
            facts.briefing_layout_profile,
            facts.briefing_rendered_layout_profile,
            facts.briefing_render_heading_floor_met
        ),
        "summary",
    );
    emit_receipt(
        "briefing_rendered_required_section_label_floor",
        facts.briefing_rendered_required_section_label_floor_met,
        "web.pipeline.completion.briefing.rendered_sections.v1",
        &format!(
            "rendered_required_section_label_count={};required_section_count={}",
            facts.briefing_rendered_required_section_label_count,
            facts.briefing_required_section_count
        ),
        "summary",
    );
    emit_receipt(
        "briefing_story_headers_absent",
        facts.briefing_story_headers_absent,
        "web.pipeline.completion.briefing.story_headers.v1",
        &format!(
            "contract_layout={};rendered_layout={};story_headers_rendered={};story_header_count={}",
            facts.briefing_layout_profile,
            facts.briefing_rendered_layout_profile,
            !facts.briefing_story_headers_absent,
            facts.briefing_story_header_count
        ),
        "summary",
    );
    emit_receipt(
        "briefing_comparison_absent",
        facts.briefing_comparison_absent,
        "web.pipeline.completion.briefing.comparison.v1",
        &format!(
            "contract_layout={};rendered_layout={};comparison_required={};comparison_rendered={};comparison_label_count={}",
            facts.briefing_layout_profile,
            facts.briefing_rendered_layout_profile,
            facts.comparison_required,
            !facts.briefing_comparison_absent,
            facts.briefing_comparison_label_count
        ),
        "summary",
    );
    emit_receipt(
        "briefing_required_section_floor",
        facts.briefing_required_section_floor_met,
        "web.pipeline.completion.briefing.sections.v2",
        &format!(
            "rendered_required_sections={};required_section_count={};required_sections={}",
            facts.briefing_rendered_required_section_count,
            facts.briefing_required_section_count,
            facts.briefing_required_sections.join("|")
        ),
        "summary",
    );
    emit_receipt(
        "briefing_query_grounding_floor",
        facts.briefing_query_grounding_floor_met,
        "web.pipeline.completion.briefing.query_grounding.v1",
        &format!(
            "grounded_required_sections={};required_section_count={}",
            facts.briefing_query_grounded_required_section_count,
            facts.briefing_required_section_count
        ),
        "summary",
    );
    emit_receipt(
        "briefing_standard_identifier_floor",
        facts.briefing_standard_identifier_floor_met,
        "web.pipeline.completion.briefing.standard_identifiers.v1",
        &format!(
            "standard_identifier_count={};required_standard_identifier_count={};required_standard_identifier_group_floor={};standard_identifier_authority_source_count={};available_standard_identifier_authority_source_count={}",
            facts.briefing_standard_identifier_count,
            facts.briefing_required_standard_identifier_count,
            facts.briefing_standard_identifier_group_floor,
            facts.briefing_standard_identifier_authority_source_count,
            facts.briefing_available_standard_identifier_authority_source_count
        ),
        "summary",
    );
    emit_receipt(
        "briefing_authority_standard_identifier_floor",
        facts.briefing_authority_standard_identifier_floor_met,
        "web.pipeline.completion.briefing.authority_standard_identifiers.v1",
        &format!(
            "authority_standard_identifier_count={};required_authority_standard_identifier_count={};required_standard_identifier_group_floor={};standard_identifier_authority_source_count={};available_standard_identifier_authority_source_count={}",
            facts.briefing_authority_standard_identifier_count,
            facts.briefing_required_authority_standard_identifier_count,
            facts.briefing_standard_identifier_group_floor,
            facts.briefing_standard_identifier_authority_source_count,
            facts.briefing_available_standard_identifier_authority_source_count
        ),
        "summary",
    );
    emit_receipt(
        "briefing_summary_inventory_floor",
        facts.briefing_summary_inventory_floor_met,
        "web.pipeline.completion.briefing.summary_inventory.v1",
        &format!(
            "summary_inventory_identifier_count={};summary_inventory_required_identifier_count={};summary_inventory_optional_identifier_count={};summary_inventory_authority_identifier_count={};required_standard_identifier_group_floor={}",
            facts.briefing_summary_inventory_identifier_count,
            facts.briefing_summary_inventory_required_identifier_count,
            facts.briefing_summary_inventory_optional_identifier_count,
            facts.briefing_summary_inventory_authority_identifier_count,
            facts.briefing_standard_identifier_group_floor
        ),
        "summary",
    );
    emit_receipt(
        "briefing_narrative_aggregation_floor",
        facts.briefing_narrative_aggregation_floor_met,
        "web.pipeline.completion.briefing.narrative_aggregation.v1",
        &format!(
            "required_narrative_sections={};single_block_narrative_sections={};aggregated_narrative_sections={};required_supporting_fragment_floor={}",
            facts.briefing_required_narrative_sections,
            facts.briefing_single_block_narrative_sections,
            facts.briefing_aggregated_narrative_sections,
            facts.briefing_required_supporting_fragment_floor
        ),
        "summary",
    );
    emit_receipt(
        "briefing_evidence_block_floor",
        facts.briefing_evidence_block_floor_met,
        "web.pipeline.completion.briefing.evidence_blocks.v1",
        &format!(
            "rendered_evidence_block_count={};required_supporting_fragment_floor={};required_evidence_sections={};qualifying_evidence_sections={}",
            facts.briefing_rendered_evidence_block_count,
            facts.briefing_required_supporting_fragment_floor,
            facts.briefing_required_evidence_sections,
            facts.briefing_qualifying_evidence_sections
        ),
        "summary",
    );
    emit_receipt(
        "briefing_primary_authority_source_floor",
        facts.briefing_primary_authority_source_floor_met,
        "web.pipeline.completion.briefing.primary_authority.v1",
        &format!(
            "selected_primary_authority_sources={};required_primary_authority_sources={};available_primary_authority_sources={};attempted_primary_authority_sources={}",
            facts.selected_primary_authority_source_count,
            facts.briefing_required_primary_authority_source_count,
            facts.available_primary_authority_source_count,
            facts.attempted_primary_authority_source_count
        ),
        "summary",
    );
    emit_receipt(
        "briefing_citation_read_backing_floor",
        facts.briefing_citation_read_backing_floor_met,
        "web.pipeline.completion.briefing.citation_backing.v1",
        &format!(
            "successful_citation_url_count={};unread_citation_url_count={};required_supporting_fragment_floor={}",
            facts.briefing_successful_citation_url_count,
            facts.briefing_unread_citation_url_count,
            facts.briefing_required_supporting_fragment_floor
        ),
        "summary",
    );
    emit_receipt(
        "briefing_temporal_anchor_floor",
        facts.briefing_temporal_anchor_floor_met,
        "web.pipeline.completion.briefing.temporal_anchor.v1",
        &format!(
            "run_date={};run_timestamp_iso_utc={}",
            facts.briefing_run_date, facts.briefing_run_timestamp_iso_utc
        ),
        "summary",
    );
    emit_receipt(
        "briefing_postamble_floor",
        facts.briefing_postamble_floor_met,
        "web.pipeline.completion.briefing.postamble.v1",
        &format!(
            "temporal_anchor={};overall_confidence={};required_citations_per_story={}",
            facts.briefing_temporal_anchor_floor_met,
            facts.briefing_overall_confidence,
            facts.required_citations_per_story
        ),
        "summary",
    );
    emit_receipt(
        "single_snapshot_metric_grounding",
        facts.single_snapshot_metric_grounding,
        "web.pipeline.completion.single_snapshot_metric.v1",
        &facts.single_snapshot_metric_grounding.to_string(),
        "bool",
    );
    emit_receipt(
        "single_snapshot_rendered_layout",
        facts.single_snapshot_rendered_layout_met,
        "web.pipeline.completion.single_snapshot.layout.v1",
        &format!(
            "rendered_layout={};story_header_count={};comparison_label_count={}",
            facts.briefing_rendered_layout_profile,
            facts.briefing_story_header_count,
            facts.briefing_comparison_label_count
        ),
        "summary",
    );
    emit_receipt(
        "single_snapshot_metric_line_floor",
        facts.single_snapshot_rendered_metric_line_floor_met,
        "web.pipeline.completion.single_snapshot.metric_lines.v1",
        &facts.single_snapshot_rendered_metric_line_count.to_string(),
        "scalar",
    );
    emit_receipt(
        "single_snapshot_support_url_floor",
        facts.single_snapshot_rendered_support_url_floor_met,
        "web.pipeline.completion.single_snapshot.support_urls.v1",
        &format!(
            "rendered_support_urls={};required_support_urls={}",
            facts.single_snapshot_rendered_support_url_count,
            facts.single_snapshot_required_citation_count
        ),
        "summary",
    );
    emit_receipt(
        "single_snapshot_read_backed_url_floor",
        facts.single_snapshot_rendered_read_backed_url_floor_met,
        "web.pipeline.completion.single_snapshot.read_backed_urls.v1",
        &format!(
            "read_backed_urls={};rendered_support_urls={};required_support_urls={}",
            facts.single_snapshot_rendered_read_backed_url_count,
            facts.single_snapshot_rendered_support_url_count,
            facts.single_snapshot_required_citation_count
        ),
        "summary",
    );
    emit_receipt(
        "single_snapshot_temporal_signal",
        facts.single_snapshot_rendered_temporal_signal_present,
        "web.pipeline.completion.single_snapshot.temporal_signal.v1",
        &facts
            .single_snapshot_rendered_temporal_signal_present
            .to_string(),
        "bool",
    );
    emit_unique_string_receipts(
        "selected_source_url",
        "web.pipeline.completion.selected_sources.v1",
        "url",
        &facts.selected_source_urls,
    );
    emit_unique_string_receipts(
        "local_business_entity_name",
        "web.pipeline.completion.local_business_entities.v1",
        "entity_name",
        &facts.matched_local_business_targets,
    );
    emit_unique_string_receipts(
        "local_business_entity_source_url",
        "web.pipeline.completion.local_business_entity_sources.v1",
        "url",
        &facts.local_business_source_urls,
    );
}
