pub(super) fn is_deterministic_tool_name(name: &str) -> bool {
    matches!(
        name,
        "computer"
            | "filesystem__write_file"
            | "filesystem__patch"
            | "filesystem__read_file"
            | "filesystem__list_directory"
            | "filesystem__search"
            | "filesystem__move_path"
            | "filesystem__copy_path"
            | "filesystem__delete_path"
            | "filesystem__create_directory"
            | "sys__exec"
            | "sys__exec_session"
            | "sys__exec_session_reset"
            | "sys__install_package"
            | "sys__change_directory"
            | "browser__navigate"
            | "browser__snapshot"
            | "browser__click"
            | "browser__click_element"
            | "browser__synthetic_click"
            | "browser__scroll"
            | "browser__type"
            | "browser__key"
            | "web__search"
            | "web__read"
            | "net__fetch"
            | "memory__search"
            | "memory__inspect"
            | "gui__click"
            | "gui__type"
            | "gui__scroll"
            | "gui__snapshot"
            | "gui__click_element"
            | "ui__find"
            | "os__focus_window"
            | "os__copy"
            | "os__paste"
            | "os__launch_app"
            | "chat__reply"
            | "agent__delegate"
            | "agent__await_result"
            | "agent__pause"
            | "agent__complete"
            | "commerce__checkout"
            | "system__fail"
    )
}
