fn google_connector_action_specs() -> Vec<GoogleConnectorActionSpec> {
    vec![
        GoogleConnectorActionSpec {
            id: "gmail.read_emails",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_read_emails",
            label: "Gmail Read Emails",
            description: "Read Gmail messages by query with sender, subject, preview, and labels.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["gmail.readonly", "gmail.modify"],
            capabilities: &[
                "mail.read.latest",
                "mail.list.recent",
                "filesystem.read",
                "gmail.read",
            ],
            fields: vec![
                number_field(
                    "max",
                    "Max messages",
                    20,
                    false,
                    Some("Maximum number of messages to return."),
                ),
                text_field(
                    "query",
                    "Search query",
                    Some("is:unread"),
                    false,
                    Some("Gmail search query such as `label:inbox newer_than:7d`."),
                ),
                select_field(
                    "includeLabels",
                    "Include labels",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    Some("Include label names in the output."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "gmail.send_email",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_send_email",
            label: "Gmail Send Email",
            description: "Send an email through Gmail using the connected Google account.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["gmail.modify"],
            capabilities: &[
                "mail.reply",
                "mail.send",
                "filesystem.read",
                "filesystem.write",
                "gmail.write",
            ],
            fields: vec![
                email_field("to", "Recipient", true, Some("alice@example.com")),
                text_field("subject", "Subject", None, true, None),
                textarea_field("body", "Body", None, true, Some("Plain text message body.")),
                text_field(
                    "threadId",
                    "Thread ID",
                    None,
                    false,
                    Some("Optional Gmail thread to keep the send bound to an existing conversation."),
                ),
                text_field(
                    "inReplyTo",
                    "In-Reply-To",
                    None,
                    false,
                    Some("Optional RFC Message-ID header for explicit reply threading."),
                ),
                text_field(
                    "references",
                    "References",
                    None,
                    false,
                    Some("Optional References header for explicit reply threading."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "gmail.draft_email",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_draft_email",
            label: "Gmail Draft Email",
            description: "Create a Gmail draft without sending it.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["gmail.modify"],
            capabilities: &[
                "mail.reply",
                "mail.send",
                "filesystem.read",
                "filesystem.write",
                "gmail.write",
            ],
            fields: vec![
                email_field("to", "Recipient", true, Some("alice@example.com")),
                text_field("subject", "Subject", None, true, None),
                textarea_field("body", "Body", None, true, Some("Plain text draft body.")),
                text_field(
                    "threadId",
                    "Thread ID",
                    None,
                    false,
                    Some("Optional Gmail thread to keep the draft bound to an existing conversation."),
                ),
                text_field(
                    "inReplyTo",
                    "In-Reply-To",
                    None,
                    false,
                    Some("Optional RFC Message-ID header for explicit reply threading."),
                ),
                text_field(
                    "references",
                    "References",
                    None,
                    false,
                    Some("Optional References header for explicit reply threading."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "gmail.mark_as_read",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_mark_as_read",
            label: "Gmail Mark As Read",
            description: "Remove the `UNREAD` label from a Gmail message.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["gmail.modify"],
            capabilities: &[
                "mail.read.latest",
                "filesystem.read",
                "filesystem.write",
                "gmail.write",
            ],
            fields: vec![text_field("messageId", "Message ID", None, true, None)],
        },
        GoogleConnectorActionSpec {
            id: "gmail.archive_email",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_archive_email",
            label: "Gmail Archive Email",
            description: "Archive a Gmail message by removing the `INBOX` label.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["gmail.modify"],
            capabilities: &[
                "mail.read.latest",
                "filesystem.read",
                "filesystem.write",
                "gmail.write",
            ],
            fields: vec![text_field("messageId", "Message ID", None, true, None)],
        },
        GoogleConnectorActionSpec {
            id: "gmail.apply_label",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_apply_label",
            label: "Gmail Apply Label",
            description: "Apply one or more Gmail labels to a message.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["gmail.modify"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "gmail.write",
            ],
            fields: vec![
                text_field("messageId", "Message ID", None, true, None),
                textarea_field(
                    "labelIds",
                    "Label IDs",
                    None,
                    true,
                    Some("Comma or newline separated label IDs."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "gmail.create_label",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_create_label",
            label: "Gmail Create Label",
            description: "Create a new Gmail label.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["gmail.modify"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "gmail.write",
            ],
            fields: vec![
                text_field("name", "Label name", None, true, None),
                select_field(
                    "messageListVisibility",
                    "Message list visibility",
                    "show",
                    vec![("Show", "show"), ("Hide", "hide")],
                    None,
                ),
                select_field(
                    "labelListVisibility",
                    "Label list visibility",
                    "labelShow",
                    vec![
                        ("Show", "labelShow"),
                        ("Show if unread", "labelShowIfUnread"),
                        ("Hide", "labelHide"),
                    ],
                    None,
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "gmail.get_thread",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_get_thread",
            label: "Gmail Get Thread",
            description: "Fetch a Gmail thread with its messages and metadata.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["gmail.readonly", "gmail.modify"],
            capabilities: &[
                "mail.read.latest",
                "mail.list.recent",
                "filesystem.read",
                "gmail.read",
            ],
            fields: vec![
                text_field("threadId", "Thread ID", None, true, None),
                select_field(
                    "format",
                    "Format",
                    "full",
                    vec![
                        ("Full", "full"),
                        ("Metadata", "metadata"),
                        ("Minimal", "minimal"),
                    ],
                    None,
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "gmail.list_labels",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_list_labels",
            label: "Gmail List Labels",
            description: "List Gmail labels for the connected account.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["gmail.readonly", "gmail.modify"],
            capabilities: &[
                "mail.read.latest",
                "mail.list.recent",
                "filesystem.read",
                "gmail.read",
            ],
            fields: vec![],
        },
        GoogleConnectorActionSpec {
            id: "gmail.watch_emails",
            service: "gmail",
            service_label: "Gmail",
            tool_name: "connector__google__gmail_watch_emails",
            label: "Gmail Watch Emails",
            description: "Start or reconnect a durable Gmail watch backed by Pub/Sub and the Autopilot runtime.",
            kind: "admin",
            confirm_before_run: true,
            required_scopes: &["gmail.modify", "pubsub", "cloud-platform"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "gmail.events",
                "events.manage",
            ],
            fields: vec![
                text_field(
                    "project",
                    "Project ID",
                    None,
                    false,
                    Some("Required when creating Pub/Sub resources."),
                ),
                text_field(
                    "subscription",
                    "Existing subscription",
                    None,
                    false,
                    Some("Reconnect to an existing Pub/Sub subscription."),
                ),
                text_field(
                    "topic",
                    "Existing topic",
                    None,
                    false,
                    Some("Use an existing Pub/Sub topic that already grants Gmail publish access."),
                ),
                text_field(
                    "labelIds",
                    "Label IDs",
                    Some("INBOX"),
                    false,
                    Some("Comma separated Gmail label IDs."),
                ),
                number_field("maxMessages", "Max messages", 10, false, None),
                number_field("pollInterval", "Poll interval seconds", 5, false, None),
                select_field(
                    "msgFormat",
                    "Message format",
                    "full",
                    vec![
                        ("Full", "full"),
                        ("Metadata", "metadata"),
                        ("Minimal", "minimal"),
                        ("Raw", "raw"),
                    ],
                    None,
                ),
                select_field(
                    "once",
                    "Pull once",
                    "false",
                    vec![("Yes", "true"), ("No", "false")],
                    Some("Default is `false` so the background runtime keeps consuming deliveries."),
                ),
                select_field(
                    "cleanup",
                    "Cleanup",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    Some("Delete created Pub/Sub resources when the watch exits."),
                ),
                text_field(
                    "outputDir",
                    "Output directory",
                    None,
                    false,
                    Some("Optional directory to write message JSON files."),
                ),
                text_field(
                    "automationActionId",
                    "Automation action ID",
                    None,
                    false,
                    Some("Optional connector action to run for each normalized Gmail delivery."),
                ),
                textarea_field(
                    "automationInputTemplate",
                    "Automation input template",
                    Some("{\"messageId\":\"{{message.messageId}}\",\"tasklist\":\"@default\"}"),
                    false,
                    Some("Optional JSON template rendered against the Gmail delivery context."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "bigquery.execute_query",
            service: "bigquery",
            service_label: "Google BigQuery",
            tool_name: BIGQUERY_TOOL_NAME,
            label: "BigQuery Execute Query",
            description: "Execute a BigQuery SQL statement using the connected Google account.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["cloud-platform"],
            capabilities: &[
                "filesystem.read",
                "bigquery.query",
            ],
            fields: vec![
                text_field(
                    "projectId",
                    "Project ID",
                    None,
                    false,
                    Some("Defaults to GOOGLE_CLOUD_PROJECT or GOOGLE_WORKSPACE_PROJECT_ID when set."),
                ),
                text_field("location", "Location", None, false, Some("Optional BigQuery location.")),
                textarea_field("query", "SQL query", None, true, None),
                number_field("maxResults", "Max results", 100, false, None),
                select_field(
                    "useLegacySql",
                    "Use legacy SQL",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    None,
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "calendar.get_event",
            service: "calendar",
            service_label: "Google Calendar",
            tool_name: "connector__google__calendar_get_event",
            label: "Google Calendar Get Event",
            description: "Fetch a single Google Calendar event by ID.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["calendar.readonly", "calendar"],
            capabilities: &[
                "filesystem.read",
                "calendar.read",
            ],
            fields: vec![
                text_field("calendarId", "Calendar ID", Some("primary"), false, None),
                text_field("eventId", "Event ID", None, true, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "calendar.list_events_for_date",
            service: "calendar",
            service_label: "Google Calendar",
            tool_name: "connector__google__calendar_list_events_for_date",
            label: "Google Calendar List Events For Date",
            description: "List calendar events for a specific calendar day.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["calendar.readonly", "calendar"],
            capabilities: &[
                "filesystem.read",
                "calendar.read",
            ],
            fields: vec![
                text_field("calendarId", "Calendar ID", Some("primary"), false, None),
                text_field(
                    "date",
                    "Date",
                    Some("2026-03-07"),
                    true,
                    Some("Date in YYYY-MM-DD format."),
                ),
                number_field("maxResults", "Max results", 25, false, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "calendar.create_event",
            service: "calendar",
            service_label: "Google Calendar",
            tool_name: "connector__google__calendar_create_event",
            label: "Google Calendar Create Event",
            description: "Create a new Google Calendar event.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["calendar"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "calendar.write",
            ],
            fields: vec![
                text_field("calendarId", "Calendar ID", Some("primary"), false, None),
                text_field("summary", "Summary", None, true, None),
                text_field(
                    "start",
                    "Start",
                    Some("2026-03-07T15:00:00-05:00"),
                    true,
                    Some("RFC3339 timestamp."),
                ),
                text_field(
                    "end",
                    "End",
                    Some("2026-03-07T15:30:00-05:00"),
                    true,
                    Some("RFC3339 timestamp."),
                ),
                text_field("location", "Location", None, false, None),
                textarea_field("description", "Description", None, false, None),
                textarea_field(
                    "attendees",
                    "Attendees",
                    None,
                    false,
                    Some("Comma or newline separated attendee emails."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "calendar.update_event",
            service: "calendar",
            service_label: "Google Calendar",
            tool_name: "connector__google__calendar_update_event",
            label: "Google Calendar Update Event",
            description: "Patch an existing Google Calendar event.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["calendar"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "calendar.write",
            ],
            fields: vec![
                text_field("calendarId", "Calendar ID", Some("primary"), false, None),
                text_field("eventId", "Event ID", None, true, None),
                text_field("summary", "Summary", None, false, None),
                text_field(
                    "start",
                    "Start",
                    Some("2026-03-07T15:00:00-05:00"),
                    false,
                    Some("Optional RFC3339 timestamp."),
                ),
                text_field(
                    "end",
                    "End",
                    Some("2026-03-07T15:30:00-05:00"),
                    false,
                    Some("Optional RFC3339 timestamp."),
                ),
                text_field("location", "Location", None, false, None),
                textarea_field("description", "Description", None, false, None),
                textarea_field(
                    "attendees",
                    "Attendees",
                    None,
                    false,
                    Some("Replaces the attendee list when provided."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "calendar.delete_event",
            service: "calendar",
            service_label: "Google Calendar",
            tool_name: "connector__google__calendar_delete_event",
            label: "Google Calendar Delete Event",
            description: "Delete a Google Calendar event.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["calendar"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "calendar.write",
            ],
            fields: vec![
                text_field("calendarId", "Calendar ID", Some("primary"), false, None),
                text_field("eventId", "Event ID", None, true, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "docs.create_document",
            service: "docs",
            service_label: "Google Docs",
            tool_name: "connector__google__docs_create_document",
            label: "Google Docs Create Document",
            description: "Create a new Google Doc.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["documents"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "docs.write",
            ],
            fields: vec![text_field("title", "Title", None, true, None)],
        },
        GoogleConnectorActionSpec {
            id: "docs.read_document",
            service: "docs",
            service_label: "Google Docs",
            tool_name: "connector__google__docs_read_document",
            label: "Google Docs Read Document",
            description: "Read a Google Doc.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["documents.readonly", "documents"],
            capabilities: &[
                "filesystem.read",
                "docs.read",
            ],
            fields: vec![text_field("documentId", "Document ID", None, true, None)],
        },
        GoogleConnectorActionSpec {
            id: "docs.append_text",
            service: "docs",
            service_label: "Google Docs",
            tool_name: "connector__google__docs_append_text",
            label: "Google Docs Append Text",
            description: "Append text to the end of a Google Doc body.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["documents"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "docs.write",
            ],
            fields: vec![
                text_field("documentId", "Document ID", None, true, None),
                textarea_field("text", "Text", None, true, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "docs.replace_text",
            service: "docs",
            service_label: "Google Docs",
            tool_name: "connector__google__docs_replace_text",
            label: "Google Docs Replace Text",
            description: "Replace matching text in a Google Doc using `replaceAllText`.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["documents"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "docs.write",
            ],
            fields: vec![
                text_field("documentId", "Document ID", None, true, None),
                text_field("searchText", "Search text", None, true, None),
                text_field("replaceText", "Replace with", None, true, None),
                select_field(
                    "matchCase",
                    "Match case",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    None,
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "sheets.read_range",
            service: "sheets",
            service_label: "Google Sheets",
            tool_name: "connector__google__sheets_read_range",
            label: "Google Sheets Read Range",
            description: "Read values from a Google Sheet range.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["spreadsheets.readonly", "spreadsheets"],
            capabilities: &[
                "filesystem.read",
                "sheets.read",
            ],
            fields: vec![
                text_field("spreadsheetId", "Spreadsheet ID", None, true, None),
                text_field("range", "Range", Some("Sheet1!A1:D10"), true, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "sheets.create_spreadsheet",
            service: "sheets",
            service_label: "Google Sheets",
            tool_name: "connector__google__sheets_create_spreadsheet",
            label: "Google Sheets Create Spreadsheet",
            description: "Create a new Google Spreadsheet.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["spreadsheets"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "sheets.write",
            ],
            fields: vec![text_field("title", "Title", None, true, None)],
        },
        GoogleConnectorActionSpec {
            id: "sheets.write_range",
            service: "sheets",
            service_label: "Google Sheets",
            tool_name: "connector__google__sheets_write_range",
            label: "Google Sheets Write Range",
            description: "Overwrite a Google Sheet range with JSON row data.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["spreadsheets"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "sheets.write",
            ],
            fields: vec![
                text_field("spreadsheetId", "Spreadsheet ID", None, true, None),
                text_field("range", "Range", Some("Sheet1!A1"), true, None),
                textarea_field(
                    "valuesJson",
                    "Values JSON",
                    Some("[[\"Deploy\",\"v1.0\"]]"),
                    true,
                    Some("JSON array of rows."),
                ),
                select_field(
                    "valueInputOption",
                    "Value input option",
                    "USER_ENTERED",
                    vec![
                        ("User entered", "USER_ENTERED"),
                        ("Raw", "RAW"),
                    ],
                    None,
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "sheets.append_rows",
            service: "sheets",
            service_label: "Google Sheets",
            tool_name: "connector__google__sheets_append_rows",
            label: "Google Sheets Append Rows",
            description: "Append JSON row data to a Google Sheet.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["spreadsheets"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "sheets.write",
            ],
            fields: vec![
                text_field("spreadsheetId", "Spreadsheet ID", None, true, None),
                textarea_field(
                    "valuesJson",
                    "Values JSON",
                    Some("[[\"Alice\",100,true]]"),
                    true,
                    Some("JSON array of rows."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "sheets.clear_range",
            service: "sheets",
            service_label: "Google Sheets",
            tool_name: "connector__google__sheets_clear_range",
            label: "Google Sheets Clear Range",
            description: "Clear values from a Google Sheet range.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["spreadsheets"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "sheets.write",
            ],
            fields: vec![
                text_field("spreadsheetId", "Spreadsheet ID", None, true, None),
                text_field("range", "Range", Some("Sheet1!A1:D10"), true, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "sheets.get_spreadsheet",
            service: "sheets",
            service_label: "Google Sheets",
            tool_name: "connector__google__sheets_get_spreadsheet",
            label: "Google Sheets Get Spreadsheet",
            description: "Fetch spreadsheet metadata and optional ranges.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["spreadsheets.readonly", "spreadsheets"],
            capabilities: &[
                "filesystem.read",
                "sheets.read",
            ],
            fields: vec![
                text_field("spreadsheetId", "Spreadsheet ID", None, true, None),
                textarea_field(
                    "ranges",
                    "Ranges",
                    None,
                    false,
                    Some("Optional comma or newline separated ranges."),
                ),
                select_field(
                    "includeGridData",
                    "Include grid data",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    None,
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "drive.upload_file",
            service: "drive",
            service_label: "Google Drive",
            tool_name: "connector__google__drive_upload_file",
            label: "Drive Upload File",
            description: "Upload a local file to Google Drive.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["drive"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "drive.write",
            ],
            fields: vec![
                text_field(
                    "filePath",
                    "Local file path",
                    None,
                    true,
                    Some("/absolute/path/to/file.pdf"),
                ),
                text_field("parentId", "Parent folder ID", None, false, None),
                text_field("name", "Target name", None, false, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "drive.share_file",
            service: "drive",
            service_label: "Google Drive",
            tool_name: "connector__google__drive_share_file",
            label: "Drive Share File",
            description: "Share a Google Drive file with a specific user and role.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["drive"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "drive.write",
            ],
            fields: vec![
                text_field("fileId", "File ID", None, true, None),
                email_field("email", "Share with", true, Some("alice@example.com")),
                select_field(
                    "role",
                    "Role",
                    "reader",
                    vec![
                        ("Viewer", "reader"),
                        ("Commenter", "commenter"),
                        ("Editor", "writer"),
                    ],
                    None,
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "tasks.list_tasks",
            service: "tasks",
            service_label: "Google Tasks",
            tool_name: "connector__google__tasks_list_tasks",
            label: "Google Tasks List Tasks",
            description: "List tasks from a Google Tasks list.",
            kind: "read",
            confirm_before_run: false,
            required_scopes: &["tasks.readonly", "tasks"],
            capabilities: &[
                "filesystem.read",
                "tasks.read",
            ],
            fields: vec![
                text_field("tasklist", "Task list", Some("@default"), false, None),
                select_field(
                    "showCompleted",
                    "Show completed",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    None,
                ),
                number_field("maxResults", "Max results", 20, false, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "tasks.create_task",
            service: "tasks",
            service_label: "Google Tasks",
            tool_name: "connector__google__tasks_create_task",
            label: "Google Tasks Create Task",
            description: "Create a task in Google Tasks.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["tasks"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "tasks.write",
            ],
            fields: vec![
                text_field("tasklist", "Task list", Some("@default"), false, None),
                text_field("title", "Title", None, true, None),
                textarea_field("notes", "Notes", None, false, None),
                text_field(
                    "due",
                    "Due",
                    Some("2026-03-07T17:00:00Z"),
                    false,
                    Some("Optional RFC3339 due timestamp."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "chat.send_message",
            service: "chat",
            service_label: "Google Chat",
            tool_name: "connector__google__chat_send_message",
            label: "Google Chat Send Message",
            description: "Send a text message to a Google Chat space.",
            kind: "write",
            confirm_before_run: true,
            required_scopes: &["chat.messages.create"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "chat.write",
            ],
            fields: vec![
                text_field("space", "Space", Some("spaces/AAAA..."), true, None),
                textarea_field("text", "Text", None, true, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "workflow.standup_report",
            service: "workflow",
            service_label: "Workflow",
            tool_name: "connector__google__workflow_standup_report",
            label: "Standup Report",
            description: "Summarize today's meetings and open tasks as a standup report.",
            kind: "workflow",
            confirm_before_run: false,
            required_scopes: &["calendar.readonly", "tasks.readonly"],
            capabilities: &[
                "filesystem.read",
                "workflow.execute",
            ],
            fields: vec![],
        },
        GoogleConnectorActionSpec {
            id: "workflow.meeting_prep",
            service: "workflow",
            service_label: "Workflow",
            tool_name: "connector__google__workflow_meeting_prep",
            label: "Meeting Prep",
            description: "Prepare for the next meeting with attendees, links, and context.",
            kind: "workflow",
            confirm_before_run: false,
            required_scopes: &["calendar.readonly"],
            capabilities: &[
                "filesystem.read",
                "workflow.execute",
            ],
            fields: vec![text_field("calendar", "Calendar", Some("primary"), false, None)],
        },
        GoogleConnectorActionSpec {
            id: "workflow.email_to_task",
            service: "workflow",
            service_label: "Workflow",
            tool_name: "connector__google__workflow_email_to_task",
            label: "Email To Task",
            description: "Create a task from a Gmail message subject and snippet.",
            kind: "workflow",
            confirm_before_run: true,
            required_scopes: &["gmail.readonly", "tasks"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "workflow.execute",
            ],
            fields: vec![
                text_field("messageId", "Gmail message ID", None, true, None),
                text_field("tasklist", "Task list", Some("@default"), false, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "workflow.weekly_digest",
            service: "workflow",
            service_label: "Workflow",
            tool_name: "connector__google__workflow_weekly_digest",
            label: "Weekly Digest",
            description: "Combine this week's meetings and unread email count.",
            kind: "workflow",
            confirm_before_run: false,
            required_scopes: &["calendar.readonly", "gmail.readonly"],
            capabilities: &[
                "filesystem.read",
                "workflow.execute",
            ],
            fields: vec![],
        },
        GoogleConnectorActionSpec {
            id: "workflow.file_announce",
            service: "workflow",
            service_label: "Workflow",
            tool_name: "connector__google__workflow_file_announce",
            label: "File Announce",
            description: "Announce a Drive file in a Google Chat space.",
            kind: "workflow",
            confirm_before_run: true,
            required_scopes: &["drive.readonly", "chat.messages.create"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "workflow.execute",
            ],
            fields: vec![
                text_field("fileId", "File ID", None, true, None),
                text_field("space", "Space", Some("spaces/AAAA..."), true, None),
                textarea_field("message", "Message", None, false, None),
            ],
        },
        GoogleConnectorActionSpec {
            id: "events.subscribe",
            service: "events",
            service_label: "Workspace Events",
            tool_name: "connector__google__events_subscribe",
            label: "Workspace Events Subscribe",
            description: "Start or reconnect durable Google Workspace event ingestion backed by Pub/Sub and the Autopilot runtime.",
            kind: "admin",
            confirm_before_run: true,
            required_scopes: &["pubsub", "cloud-platform", "chat.messages.readonly"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "events.manage",
            ],
            fields: vec![
                text_field(
                    "target",
                    "Target resource",
                    Some("//chat.googleapis.com/spaces/SPACE_ID"),
                    false,
                    Some("Required when creating a new Workspace Events subscription."),
                ),
                text_field(
                    "eventTypes",
                    "Event types",
                    Some("google.workspace.chat.message.v1.created"),
                    false,
                    Some("Comma separated CloudEvents types."),
                ),
                text_field(
                    "project",
                    "Project ID",
                    None,
                    false,
                    Some("Required when creating new Pub/Sub resources."),
                ),
                text_field(
                    "subscription",
                    "Existing subscription",
                    None,
                    false,
                    Some("Reconnect to an existing Pub/Sub subscription."),
                ),
                number_field("maxMessages", "Max messages", 10, false, None),
                number_field("pollInterval", "Poll interval seconds", 5, false, None),
                select_field(
                    "once",
                    "Pull once",
                    "false",
                    vec![("Yes", "true"), ("No", "false")],
                    Some("Default is `false` so the background runtime keeps consuming deliveries."),
                ),
                select_field(
                    "cleanup",
                    "Cleanup",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    None,
                ),
                select_field(
                    "noAck",
                    "No ack",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    Some("Leave pulled messages unacknowledged."),
                ),
                text_field("outputDir", "Output directory", None, false, None),
                text_field(
                    "automationActionId",
                    "Automation action ID",
                    None,
                    false,
                    Some("Optional connector action to run for each normalized Workspace event."),
                ),
                textarea_field(
                    "automationInputTemplate",
                    "Automation input template",
                    Some("{\"text\":\"Workspace event {{event.eventType}} on {{event.subject}}\"}"),
                    false,
                    Some("Optional JSON template rendered against the Workspace event context."),
                ),
            ],
        },
        GoogleConnectorActionSpec {
            id: "events.renew",
            service: "events",
            service_label: "Workspace Events",
            tool_name: "connector__google__events_renew",
            label: "Workspace Events Renew",
            description: "Reactivate one or more Workspace Events subscriptions.",
            kind: "admin",
            confirm_before_run: true,
            required_scopes: &["pubsub", "cloud-platform", "chat.messages.readonly"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "events.manage",
            ],
            fields: vec![
                text_field(
                    "name",
                    "Subscription name",
                    Some("subscriptions/SUB_ID"),
                    false,
                    Some("Use for a single subscription."),
                ),
                select_field(
                    "all",
                    "Renew all",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    Some("Renew all subscriptions expiring within the provided window."),
                ),
                text_field("within", "Within", Some("1h"), false, Some("Window for `--all`.")),
            ],
        },
        GoogleConnectorActionSpec {
            id: "expert.raw_request",
            service: "expert",
            service_label: "Expert Mode",
            tool_name: "connector__google__expert_raw_request",
            label: "Google Expert Raw Request",
            description: "Invoke an arbitrary Google API method through the Google connector.",
            kind: "expert",
            confirm_before_run: true,
            required_scopes: &["cloud-platform", "drive", "gmail.modify", "calendar", "documents", "spreadsheets"],
            capabilities: &[
                "filesystem.read",
                "filesystem.write",
                "google.expert",
            ],
            fields: vec![
                text_field(
                    "service",
                    "Service",
                    Some("drive"),
                    true,
                    Some("Known alias like `drive` or explicit `<api>:<version>` such as `bigquery:v2`."),
                ),
                text_field(
                    "resourcePath",
                    "Resource path",
                    Some("files"),
                    false,
                    Some("Space, slash, or dot separated resource path."),
                ),
                text_field("method", "Method", Some("list"), true, None),
                textarea_field(
                    "paramsJson",
                    "Params JSON",
                    Some("{\"pageSize\":10}"),
                    false,
                    Some("JSON object for request path and query parameters."),
                ),
                textarea_field(
                    "bodyJson",
                    "Body JSON",
                    Some("{\"name\":\"example\"}"),
                    false,
                    Some("JSON request body."),
                ),
                text_field("uploadPath", "Upload path", None, false, None),
                select_field(
                    "pageAll",
                    "Page all",
                    "false",
                    vec![("No", "false"), ("Yes", "true")],
                    None,
                ),
                number_field("pageLimit", "Page limit", 25, false, None),
                number_field("pageDelayMs", "Page delay ms", 100, false, None),
            ],
        },
    ]
}

fn find_action_by_id(action_id: &str) -> Option<GoogleConnectorActionSpec> {
    let normalized = action_id.trim().to_ascii_lowercase();
    google_connector_action_specs()
        .into_iter()
        .find(|spec| spec.id == normalized)
}

fn find_action_by_tool_name(tool_name: &str) -> Option<GoogleConnectorActionSpec> {
    let normalized = tool_name.trim().to_ascii_lowercase();
    google_connector_action_specs()
        .into_iter()
        .find(|spec| spec.tool_name == normalized)
}

fn connector_fields_to_schema(fields: &[ConnectorFieldDefinition]) -> Value {
    let mut properties = serde_json::Map::new();
    let mut required = Vec::new();

    for field in fields {
        let mut schema = serde_json::Map::new();
        match field.field_type.as_str() {
            "number" => {
                schema.insert("type".to_string(), json!("number"));
            }
            "select" => {
                schema.insert("type".to_string(), json!("string"));
                if let Some(options) = field.options.as_ref() {
                    schema.insert(
                        "enum".to_string(),
                        Value::Array(
                            options
                                .iter()
                                .map(|option| Value::String(option.value.clone()))
                                .collect(),
                        ),
                    );
                }
            }
            _ => {
                schema.insert("type".to_string(), json!("string"));
                if field.field_type == "email" {
                    schema.insert("format".to_string(), json!("email"));
                }
            }
        }

        schema.insert("title".to_string(), Value::String(field.label.clone()));
        if let Some(description) = field.description.as_ref() {
            schema.insert(
                "description".to_string(),
                Value::String(description.clone()),
            );
        }
        if let Some(default_value) = field.default_value.as_ref() {
            schema.insert("default".to_string(), default_value.clone());
        }
        properties.insert(field.id.clone(), Value::Object(schema));
        if field.required {
            required.push(Value::String(field.id.clone()));
        }
    }

    json!({
        "type": "object",
        "properties": properties,
        "required": required,
        "additionalProperties": false
    })
}

