// Domain barrel for Autopilot frontend contracts.

export type {
  Node,
  Edge,
  NodeLogic,
  FirewallPolicy,
  GraphGlobalConfig,
  AgentConfiguration,
  AssistantWorkbenchSession,
  CalendarAttendeeDetail,
  CalendarEventDetail,
  ConnectorSummary,
  GmailThreadDetail,
  GmailThreadMessageDetail,
  SessionClarificationOption,
  SessionClarificationRequest,
  SessionCredentialRequest,
  SessionGateInfo,
  ChatCapabilityDetailSection,
} from "./agent-ide";

export type {
  ExecutionMode,
  LiabilityLevel,
  ChatMessage,
} from "./base";

export type {
  ChatExecutionBudgetEnvelope,
  ChatExecutionBudgetExpansionPolicy,
  ChatExecutionModeDecision,
  ChatExecutionStrategy,
  ChatRuntimeProvenance,
  ChatRuntimeProvenanceKind,
  ExecutionBudgetSummary,
  ExecutionCompletionInvariant,
  ExecutionCompletionInvariantStatus,
  ExecutionDispatchBatch,
  ExecutionDomainKind,
  ExecutionEnvelope,
  ExecutionGraphMutationReceipt,
  ExecutionLivePreview,
  ExecutionLivePreviewKind,
  ExecutionRepairReceipt,
  ExecutionReplanReceipt,
  ExecutionStage,
  SwarmChangeReceipt,
  SwarmLeaseMode,
  SwarmLeaseRequirement,
  SwarmLeaseScopeKind,
  SwarmExecutionSummary,
  SwarmMergeReceipt,
  SwarmPlan,
  SwarmVerificationPolicy,
  SwarmVerificationReceipt,
  SwarmWorkItem,
  SwarmWorkItemStatus,
  SwarmWorkerResultKind,
  SwarmWorkerReceipt,
  SwarmWorkerRole,
} from "./execution";

export { executionStageForCurrentStage } from "./execution";

export type {
  ActiveContextItem,
  ArtifactRef,
  ArtifactType,
  AssistantNotificationClass,
  AssistantNotificationStatus,
  ContextConstraint,
  EventStatus,
  EventType,
  InterventionStatus,
  InterventionType,
  NotificationActionStyle,
  NotificationPreviewMode,
  NotificationRail,
  NotificationSeverity,
  ObservationTier,
  SkillCatalogEntry,
} from "./generated";

export type {
  AgentEvent,
} from "./events";

export type {
  Artifact,
  ArtifactContentPayload,
} from "./artifacts";

export type {
  ChatArtifactNavigatorNode,
  ChatArtifactMaterializationFileWrite,
  ChatArtifactMaterializationCommandIntent,
  ChatArtifactMaterializationPreviewIntent,
  ChatArtifactPipelineStep,
  ChatArtifactEditMode,
  ChatArtifactValidationStatus,
  ChatArtifactOutputOrigin,
  ChatArtifactFailureKind,
  ChatArtifactFailure,
  ChatArtifactRenderCaptureViewport,
  ChatArtifactRenderFindingSeverity,
  ChatArtifactRenderCapture,
  ChatArtifactRenderFinding,
  ChatArtifactExecutionWitnessStatus,
  ChatArtifactAcceptanceObligationStatus,
  ChatArtifactExecutionWitness,
  ChatArtifactAcceptanceObligation,
  ChatArtifactRenderPolicyMode,
  ChatArtifactRenderObservation,
  ChatArtifactRenderAcceptancePolicy,
  ChatArtifactRenderEvaluation,
  ChatArtifactUxLifecycle,
  ChatArtifactSelectionTarget,
  ChatArtifactTasteMemory,
  ChatArtifactExemplar,
  ChatArtifactBrief,
  ChatArtifactContentGoalKind,
  ChatArtifactInteractionGoalKind,
  ChatArtifactEvidenceGoalKind,
  ChatArtifactPresentationConstraintKind,
  ChatArtifactContentGoal,
  ChatArtifactInteractionGoal,
  ChatArtifactEvidenceGoal,
  ChatArtifactPresentationConstraint,
  ChatArtifactQueryProfile,
  ChatArtifactSkillNeedKind,
  ChatArtifactSkillNeedPriority,
  ChatArtifactSkillNeed,
  ChatArtifactPreparationNeeds,
  ChatArtifactPreparedContextResolution,
  ChatArtifactSkillDiscoveryResolution,
  ChatArtifactSectionPlan,
  ChatArtifactInteractionPlan,
  ChatArtifactEvidencePlanEntry,
  ChatArtifactDesignSystem,
  ChatArtifactComponentPlanEntry,
  ChatArtifactAccessibilityPlan,
  ChatArtifactAcceptanceTargets,
  ChatArtifactBlueprint,
  ChatArtifactIRNode,
  ChatArtifactIRInteractionEdge,
  ChatArtifactIREvidenceSurface,
  ChatArtifactDesignToken,
  ChatArtifactIR,
  ChatArtifactSelectedSkill,
  ChatArtifactEditIntent,
  ChatArtifactValidationResult,
  ChatArtifactCandidateSummary,
  ChatArtifactCandidateConvergenceTrace,
  ChatArtifactWorkerRole,
  ChatArtifactWorkItemStatus,
  ChatArtifactWorkItem,
  ChatArtifactSwarmPlan,
  ChatArtifactSwarmExecutionSummary,
  ChatArtifactWorkerReceipt,
  ChatArtifactPatchReceipt,
  ChatArtifactMergeReceipt,
  ChatArtifactVerificationReceipt,
  ChatArtifactRuntimePreviewSnapshot,
  ArtifactOperatorRunMode,
  ChatArtifactOperatorRunMode,
  ArtifactOperatorRunStatus,
  ChatArtifactOperatorRunStatus,
  ArtifactOperatorPhase,
  ChatArtifactOperatorPhase,
  ChatArtifactOperatorPreview,
  ArtifactSourceReference,
  ChatArtifactSourceReference,
  ArtifactSourcePack,
  ChatArtifactSourcePack,
  ArtifactFileRef,
  ChatArtifactFileRef,
  ArtifactVerificationRef,
  ChatArtifactVerificationRef,
  ArtifactVerificationOutcome,
  ChatArtifactVerificationOutcome,
  ArtifactOperatorStep,
  ChatArtifactOperatorStep,
  ArtifactOperatorRun,
  ChatArtifactOperatorRun,
  ChatArtifactRuntimeEventType,
  ChatArtifactRuntimeStepId,
  ChatArtifactRuntimeStepKind,
  ChatArtifactRuntimeEventKind,
  ChatArtifactRuntimeEventStatus,
  ChatArtifactMaterializationContract,
  ChatBuildReceipt,
  ChatCodeWorkerLease,
  ChatOutcomeKind,
  ChatArtifactClass,
  ChatArtifactDeliverableShape,
  ChatRendererKind,
  ChatPresentationSurface,
  ChatArtifactPersistenceMode,
  ChatExecutionSubstrate,
  ChatArtifactTabKind,
  ChatArtifactFileRole,
  ChatArtifactVerificationStatus,
  ChatArtifactLifecycleState,
  ChatOutcomeArtifactScope,
  ChatOutcomeArtifactVerificationRequest,
  ChatOutcomeArtifactRequest,
  ChatOutcomeRequest,
  ChatOutcomePlanningPayload,
  ChatArtifactManifestTab,
  ChatArtifactManifestFile,
  ChatArtifactManifestVerification,
  ChatRetainedWidgetState,
  ChatArtifactManifestStorage,
  ChatArtifactManifest,
  ChatVerifiedReply,
  ChatRendererSession,
  ChatArtifactRevision,
  ChatArtifactSession,
  BuildArtifactSession,
} from "./chat-artifacts";

export type {
  AtlasEdge,
  AtlasNode,
  AtlasNeighborhood,
  SkillMacroStepView,
  SkillBenchmarkView,
  SkillDetailView,
  SubstrateProofReceipt,
  SubstrateProofView,
  ActiveContextSnapshot,
  BenchmarkTraceArtifactLink,
  BenchmarkTraceSpan,
  BenchmarkTraceLane,
  BenchmarkTraceBookmark,
  BenchmarkTraceReplay,
  BenchmarkTraceMetric,
  BenchmarkTraceLinks,
  BenchmarkTraceSummary,
  BenchmarkTraceCaseView,
  BenchmarkTraceFeed,
  AtlasSearchResult,
  ContextAtlasLens,
  ContextAtlasMode,
  ContextAtlasFocusRequest,
} from "./atlas";

export type {
  NotificationAction,
  NotificationDeliveryState,
  NotificationPrivacy,
  NotificationSource,
  NotificationPolicyRefs,
  NotificationTarget,
  InterventionRecord,
  AssistantNotificationRecord,
} from "./notifications";

export type {
  ResetAutopilotDataResult,
} from "./app";

export type {
  AgentStatus,
  GateInfo,
  PiiTargetServiceCall,
  PiiTargetCloudInference,
  PiiTargetAction,
  PiiTarget,
  PiiReviewInfo,
  Receipt,
  CredentialRequest,
  ClarificationOption,
  ClarificationRequest,
  SessionChecklistItem,
  SessionBackgroundTaskRecord,
  SessionFileContext,
  PolicyContext,
  SwarmAgent,
  AgentTask,
  AgentTaskModelInput,
  WalletConnectorAuthRecordView,
  WalletConnectorAuthGetResult,
} from "./session";

export type {
  DetectorPolicyConfig,
  AssistantAttentionGlobalPolicy,
  ConnectorAttentionPolicy,
  AssistantAttentionPolicy,
  AssistantAttentionProfile,
  AssistantUserProfile,
  KnowledgeCollectionSourceRecord,
  KnowledgeCollectionEntryRecord,
  KnowledgeCollectionRecord,
  KnowledgeCollectionEntryContent,
  KnowledgeCollectionSearchHit,
  SkillSourceDiscoveredSkill,
  SkillSourceRecord,
} from "./knowledge";

export type {
  CapabilityAuthorityDescriptor,
  CapabilityLeaseDescriptor,
  CapabilityRegistryEntry,
  CapabilityRegistrySummary,
  ExtensionContributionRecord,
  ExtensionManifestRecord,
  CapabilityRegistrySnapshot,
} from "./capabilities";

export type {
  LocalEngineCapabilityFamily,
  LocalEngineControlAction,
  LocalEngineActivityRecord,
  LocalEngineJobRecord,
  LocalEngineModelRecord,
  LocalEngineBackendRecord,
  LocalEngineGalleryEntryPreview,
  LocalEngineGalleryCatalogRecord,
  LocalEngineWorkerCompletionContract,
  LocalEngineWorkerWorkflowRecord,
  LocalEngineWorkerTemplateRecord,
  LocalEngineAgentPlaybookStepRecord,
  LocalEngineAgentPlaybookRecord,
  LocalEngineParentPlaybookReceiptRecord,
  LocalEngineParentPlaybookStepRunRecord,
  LocalEngineParentPlaybookRunRecord,
  LocalEngineRuntimeProfile,
  LocalEngineStorageConfig,
  LocalEngineWatchdogConfig,
  LocalEngineMemoryConfig,
  LocalEngineBackendPolicyConfig,
  LocalEngineResponseConfig,
  LocalEngineApiConfig,
  LocalEngineLauncherConfig,
  LocalEngineGallerySource,
  LocalEngineEnvironmentBinding,
  LocalEngineControlPlane,
  LocalEngineConfigMigrationRecord,
  LocalEngineStagedOperation,
  LocalEngineManagedSettingsChannelRecord,
  LocalEngineManagedSettingsSnapshot,
  LocalEngineSnapshot,
} from "./local-engine";

export type {
  SessionSummary,
  SessionMemoryClass,
  SessionCompactionMode,
  SessionCompactionPolicy,
  SessionCompactionDisposition,
  SessionCompactionResumeSafetyStatus,
  SessionCompactionResumeSafetyReceipt,
  SessionCompactionMemoryItem,
  SessionCompactionPruneDecision,
  SessionCompactionCarryForwardState,
  SessionCompactionPreview,
  SessionCompactionRecord,
  SessionCompactionRecommendation,
  SessionDurabilityPortfolio,
  SessionCompactionSnapshot,
  TeamMemoryScopeKind,
  TeamMemorySyncStatus,
  TeamMemoryRedactionSummary,
  TeamMemorySyncEntry,
  TeamMemorySyncSnapshot,
  SessionRewindCandidate,
  SessionRewindSnapshot,
  SessionHookReceiptSummary,
  SessionHookRecord,
  SessionHookSnapshot,
  SessionBranchRecord,
  SessionWorktreeRecord,
  SessionBranchSnapshot,
  SessionRemoteEnvBinding,
  SessionRemoteEnvSnapshot,
  SessionServerSessionRecord,
  SessionServerSnapshot,
} from "./session-continuity";

export type {
  VoiceInputTranscriptionResult,
} from "./voice";

export type {
  SessionPluginRecord,
  SessionPluginLifecycleReceipt,
  SessionPluginCatalogChannelRecord,
  SessionPluginSnapshot,
  SessionPluginCatalogSourceRecord,
} from "./plugins";

export type {
  AssistantWorkbenchActivityRecord,
  TraceBundleStats,
  TraceBundleArtifactPayloadEntry,
  EvidenceTier,
  TraceAuthority,
  CanonicalTraceBundle,
  OperatorInterventionType,
  OperatorIntervention,
  TraceBundleDiffStat,
  TraceBundleDiffSection,
  TraceBundleDiffResult,
  MutationLogEntry,
} from "./traces";

export type {
  ActivityKind,
  ActivityEventRef,
  ActivitySummary,
  ActivityGroup,
  ToolActivityKind,
  ToolActivityStatus,
  ToolActivityRow,
  ToolActivityGroupPresentation,
  ChatContractScalar,
  ChatContractValue,
  ChatContractSchemaVersion,
  ChatContractOutcomeStatus,
  ChatContractOutcome,
  ChatContractResultColumn,
  ChatContractAction,
  ChatContractResultRow,
  ChatContractInterpretation,
  ChatContractEnvelopeV1,
  ChatContractValidationIssue,
  AnswerPresentation,
  SourceDomainPreview,
  SourceSearchRow,
  SourceBrowseRow,
  SourceSummary,
  ThoughtAgentKind,
  ThoughtAgentSummary,
  ThoughtSummary,
  ExecutionMomentKind,
  ExecutionMomentStatus,
  ExecutionMoment,
  PlanRouteFamily,
  PlanLaneFamily,
  PlanSourceFamily,
  PlanClarificationMode,
  PlanFallbackMode,
  PlanRiskSensitivity,
  PlanWorkStatus,
  PlanLaneTransitionKind,
  PlanRouteTopology,
  PlanPlannerAuthority,
  PlanVerifierState,
  PlanVerifierRole,
  PlanVerifierOutcome,
  PlanApprovalState,
  PlanComputerUsePerceptionSummary,
  PlanResearchVerificationSummary,
  PlanArtifactGenerationSummary,
  PlanCodingVerificationSummary,
  PlanArtifactQualitySummary,
  PlanPatchSynthesisSummary,
  PlanComputerUseVerificationSummary,
  PlanComputerUseRecoverySummary,
  PlanArtifactRepairSummary,
  PlanSelectedSkill,
  PlanOutputIntent,
  PlanEffectiveToolSurfaceSummary,
  PlanLaneFrameSummary,
  PlanSourceSelectionSummary,
  PlanClarificationPolicySummary,
  PlanFallbackPolicySummary,
  PlanPresentationPolicySummary,
  PlanTransformationPolicySummary,
  PlanRiskProfileSummary,
  PlanVerificationContractSummary,
  PlanSourceRankingEntrySummary,
  PlanWidgetStateBindingSummary,
  PlanRetainedWidgetStateSummary,
  PlanPolicyContractSummary,
  PlanDomainPolicyBundleSummary,
  PlanWeatherRequestFrameSummary,
  PlanSportsRequestFrameSummary,
  PlanPlacesRequestFrameSummary,
  PlanRecipeRequestFrameSummary,
  PlanMessageComposeRequestFrameSummary,
  PlanUserInputRequestFrameSummary,
  PlanNormalizedRequestFrameSummary,
  PlanRetainedLaneStateSummary,
  PlanLaneTransitionSummary,
  PlanObjectiveStateSummary,
  PlanTaskUnitStateSummary,
  PlanCheckpointStateSummary,
  PlanCompletionInvariantSummary,
  PlanOrchestrationStateSummary,
  PlanRouteDecisionSummary,
  PlanSummary,
  ArtifactHubViewKey,
  RunPresentation,
  ExportBundleManifest,
} from "./chat";

export { normalizeAgentTaskModel } from "./session";
