export interface SessionPluginRecord {
  pluginId: string;
  entryId?: string | null;
  label: string;
  description?: string | null;
  version?: string | null;
  sourceEnabled: boolean;
  enabled: boolean;
  statusLabel: string;
  sourceLabel: string;
  sourceKind: string;
  sourceUri?: string | null;
  category?: string | null;
  marketplaceDisplayName?: string | null;
  marketplaceInstallationPolicy?: string | null;
  marketplaceAuthenticationPolicy?: string | null;
  marketplaceProducts: string[];
  authenticityState: string;
  authenticityLabel: string;
  authenticityDetail: string;
  operatorReviewState: string;
  operatorReviewLabel: string;
  operatorReviewReason: string;
  catalogStatus: string;
  catalogStatusLabel: string;
  catalogStatusDetail: string;
  catalogIssuedAtMs?: number | null;
  catalogExpiresAtMs?: number | null;
  catalogRefreshedAtMs?: number | null;
  catalogRefreshSource?: string | null;
  catalogChannel?: string | null;
  catalogSourceId?: string | null;
  catalogSourceLabel?: string | null;
  catalogSourceUri?: string | null;
  marketplacePackageUrl?: string | null;
  catalogRefreshBundleId?: string | null;
  catalogRefreshBundleLabel?: string | null;
  catalogRefreshBundleIssuedAtMs?: number | null;
  catalogRefreshBundleExpiresAtMs?: number | null;
  catalogRefreshAvailableVersion?: string | null;
  catalogRefreshError?: string | null;
  lastCatalogRefreshAtMs?: number | null;
  verificationError?: string | null;
  verificationAlgorithm?: string | null;
  publisherLabel?: string | null;
  publisherId?: string | null;
  signerIdentity?: string | null;
  signingKeyId?: string | null;
  verificationTimestampMs?: number | null;
  verificationSource?: string | null;
  verifiedDigestSha256?: string | null;
  publisherTrustState?: string | null;
  publisherTrustLabel?: string | null;
  publisherTrustDetail?: string | null;
  publisherTrustSource?: string | null;
  publisherRootId?: string | null;
  publisherRootLabel?: string | null;
  authorityBundleId?: string | null;
  authorityBundleLabel?: string | null;
  authorityBundleIssuedAtMs?: number | null;
  authorityTrustBundleId?: string | null;
  authorityTrustBundleLabel?: string | null;
  authorityTrustBundleIssuedAtMs?: number | null;
  authorityTrustBundleExpiresAtMs?: number | null;
  authorityTrustBundleStatus?: string | null;
  authorityTrustIssuerId?: string | null;
  authorityTrustIssuerLabel?: string | null;
  authorityId?: string | null;
  authorityLabel?: string | null;
  publisherStatementIssuedAtMs?: number | null;
  publisherRevokedAtMs?: number | null;
  trustScoreLabel?: string | null;
  trustScoreSource?: string | null;
  trustRecommendation?: string | null;
  updateSeverity?: string | null;
  updateSeverityLabel?: string | null;
  updateDetail?: string | null;
  requestedCapabilities: string[];
  trustPosture: string;
  governedProfile: string;
  authorityTierLabel: string;
  availabilityLabel: string;
  sessionScopeLabel: string;
  reloadable: boolean;
  reloadabilityLabel: string;
  contributionCount: number;
  hookContributionCount: number;
  filesystemSkillCount: number;
  capabilityCount: number;
  runtimeTrustState: string;
  runtimeTrustLabel: string;
  runtimeLoadState: string;
  runtimeLoadLabel: string;
  runtimeStatusDetail: string;
  loadError?: string | null;
  lastTrustedAtMs?: number | null;
  lastReloadedAtMs?: number | null;
  lastInstalledAtMs?: number | null;
  lastUpdatedAtMs?: number | null;
  lastRemovedAtMs?: number | null;
  trustRemembered: boolean;
  packageManaged: boolean;
  packageInstallState: string;
  packageInstallLabel: string;
  packageInstallDetail: string;
  packageInstallSource?: string | null;
  packageInstallSourceLabel?: string | null;
  packageRootPath?: string | null;
  packageManifestPath?: string | null;
  installedVersion?: string | null;
  availableVersion?: string | null;
  updateAvailable: boolean;
  packageError?: string | null;
  whyAvailable: string;
}

export interface SessionPluginLifecycleReceipt {
  receiptId: string;
  timestampMs: number;
  pluginId: string;
  pluginLabel: string;
  action: string;
  status: string;
  summary: string;
}

export interface SessionPluginCatalogChannelRecord {
  catalogId: string;
  label: string;
  sourceUri: string;
  refreshSource?: string | null;
  channel?: string | null;
  status: string;
  statusLabel: string;
  statusDetail: string;
  issuedAtMs?: number | null;
  expiresAtMs?: number | null;
  refreshedAtMs?: number | null;
  pluginCount: number;
  validPluginCount: number;
  invalidPluginCount: number;
  refreshBundleCount: number;
  refreshError?: string | null;
  conformanceStatus: string;
  conformanceLabel: string;
  conformanceError?: string | null;
}

export interface SessionPluginSnapshot {
  generatedAtMs: number;
  sessionId?: string | null;
  workspaceRoot?: string | null;
  pluginCount: number;
  enabledPluginCount: number;
  disabledPluginCount: number;
  trustedPluginCount: number;
  untrustedPluginCount: number;
  blockedPluginCount: number;
  reloadablePluginCount: number;
  managedPackageCount: number;
  updateAvailableCount: number;
  installablePackageCount: number;
  verifiedPluginCount: number;
  unverifiedPluginCount: number;
  signatureMismatchPluginCount: number;
  recommendedPluginCount: number;
  reviewRequiredPluginCount: number;
  staleCatalogCount: number;
  expiredCatalogCount: number;
  criticalUpdateCount: number;
  refreshAvailableCount: number;
  refreshFailedCount: number;
  catalogChannelCount: number;
  nonconformantChannelCount: number;
  catalogSourceCount: number;
  localCatalogSourceCount: number;
  remoteCatalogSourceCount: number;
  failedCatalogSourceCount: number;
  nonconformantSourceCount: number;
  hookContributionCount: number;
  filesystemSkillCount: number;
  recentReceiptCount: number;
  recentReceipts: SessionPluginLifecycleReceipt[];
  catalogSources: SessionPluginCatalogSourceRecord[];
  catalogChannels: SessionPluginCatalogChannelRecord[];
  plugins: SessionPluginRecord[];
}

export interface SessionPluginCatalogSourceRecord {
  sourceId: string;
  label: string;
  sourceUri: string;
  transportKind: string;
  channel?: string | null;
  authorityBundleId?: string | null;
  authorityBundleLabel?: string | null;
  status: string;
  statusLabel: string;
  statusDetail: string;
  lastSuccessfulRefreshAtMs?: number | null;
  lastFailedRefreshAtMs?: number | null;
  refreshError?: string | null;
  conformanceStatus: string;
  conformanceLabel: string;
  conformanceError?: string | null;
  catalogCount: number;
  validCatalogCount: number;
  invalidCatalogCount: number;
}
