use super::build_session_hook_snapshot;
use crate::kernel::connectors::{ShieldApprovalHookReceipt, ShieldRememberedApprovalSnapshot};
use crate::models::{
    CapabilityAuthorityDescriptor, CapabilityLeaseDescriptor, CapabilityRegistryEntry,
    CapabilityRegistrySnapshot, CapabilityRegistrySummary, ExtensionContributionRecord,
    ExtensionManifestRecord, LocalEngineApiConfig, LocalEngineBackendPolicyConfig,
    LocalEngineControlPlane, LocalEngineMemoryConfig, LocalEngineResponseConfig,
    LocalEngineRuntimeProfile, LocalEngineSnapshot, LocalEngineStorageConfig,
    LocalEngineWatchdogConfig, SkillSourceDiscoveredSkill,
};

fn empty_local_engine_snapshot() -> LocalEngineSnapshot {
    LocalEngineSnapshot {
        generated_at_ms: 0,
        total_native_tools: 0,
        pending_control_count: 0,
        pending_approval_count: 0,
        active_issue_count: 0,
        capabilities: Vec::new(),
        compatibility_routes: Vec::new(),
        pending_controls: Vec::new(),
        jobs: Vec::new(),
        recent_activity: Vec::new(),
        registry_models: Vec::new(),
        managed_backends: Vec::new(),
        gallery_catalogs: Vec::new(),
        worker_templates: Vec::new(),
        agent_playbooks: Vec::new(),
        parent_playbook_runs: Vec::new(),
        control_plane_schema_version: 1,
        control_plane_profile_id: "test".to_string(),
        control_plane_migrations: Vec::new(),
        control_plane: LocalEngineControlPlane {
            runtime: LocalEngineRuntimeProfile {
                mode: "local".to_string(),
                endpoint: "http://127.0.0.1:11434/v1".to_string(),
                default_model: "none".to_string(),
                baseline_role: "operator".to_string(),
                kernel_authority: "contained_local".to_string(),
            },
            storage: LocalEngineStorageConfig {
                models_path: ".".to_string(),
                backends_path: ".".to_string(),
                artifacts_path: ".".to_string(),
                cache_path: ".".to_string(),
            },
            watchdog: LocalEngineWatchdogConfig {
                enabled: false,
                idle_check_enabled: false,
                idle_timeout: "0s".to_string(),
                busy_check_enabled: false,
                busy_timeout: "0s".to_string(),
                check_interval: "0s".to_string(),
                force_eviction_when_busy: false,
                lru_eviction_max_retries: 0,
                lru_eviction_retry_interval: "0s".to_string(),
            },
            memory: LocalEngineMemoryConfig {
                reclaimer_enabled: false,
                threshold_percent: 0,
                prefer_gpu: false,
                target_resource: "cpu".to_string(),
            },
            backend_policy: LocalEngineBackendPolicyConfig {
                max_concurrency: 1,
                max_queued_requests: 1,
                parallel_backend_loads: 1,
                allow_parallel_requests: false,
                health_probe_interval: "0s".to_string(),
                log_level: "info".to_string(),
                auto_shutdown_on_idle: false,
            },
            responses: LocalEngineResponseConfig {
                retain_receipts_days: 1,
                persist_artifacts: false,
                allow_streaming: false,
                store_request_previews: false,
            },
            api: LocalEngineApiConfig {
                bind_address: "127.0.0.1:0".to_string(),
                remote_access_enabled: false,
                expose_compat_routes: false,
                cors_mode: "off".to_string(),
                auth_mode: "none".to_string(),
            },
            launcher: Default::default(),
            galleries: Vec::new(),
            environment: Vec::new(),
            notes: Vec::new(),
        },
        managed_settings: crate::models::LocalEngineManagedSettingsSnapshot {
            sync_status: "local_only".to_string(),
            summary: "No managed settings active.".to_string(),
            ..Default::default()
        },
        staged_operations: Vec::new(),
    }
}

#[test]
fn session_hook_snapshot_collects_manifest_hooks_and_recent_receipts() {
    let mut local_engine = empty_local_engine_snapshot();
    local_engine
        .recent_activity
        .push(crate::models::LocalEngineActivityRecord {
            event_id: "evt-1".to_string(),
            session_id: "session-123".to_string(),
            family: "workers".to_string(),
            title: "Hook worker evaluated".to_string(),
            tool_name: "hook_worker".to_string(),
            timestamp_ms: 42,
            success: true,
            operation: Some("hook_eval".to_string()),
            subject_kind: Some("hook".to_string()),
            subject_id: Some("hook://alpha".to_string()),
            backend_id: None,
            error_class: None,
        });

    let snapshot = CapabilityRegistrySnapshot {
        generated_at_ms: 1,
        summary: CapabilityRegistrySummary {
            generated_at_ms: 1,
            total_entries: 1,
            connector_count: 0,
            connected_connector_count: 0,
            runtime_skill_count: 0,
            tracked_source_count: 1,
            filesystem_skill_count: 0,
            extension_count: 1,
            model_count: 0,
            backend_count: 0,
            native_family_count: 0,
            pending_engine_control_count: 0,
            active_issue_count: 0,
            authoritative_source_count: 1,
        },
        entries: vec![CapabilityRegistryEntry {
            entry_id: "extension:manifest:alpha".to_string(),
            kind: "extension".to_string(),
            label: "Alpha Hooks".to_string(),
            summary: "Alpha summary".to_string(),
            source_kind: "tracked_source".to_string(),
            source_label: "Workspace source".to_string(),
            source_uri: Some("/workspace/plugin".to_string()),
            trust_posture: "local_only".to_string(),
            governed_profile: Some("automation_bridge".to_string()),
            availability: "ready".to_string(),
            status_label: "Ready".to_string(),
            why_selectable: "Selectable".to_string(),
            governing_family_id: None,
            related_governing_entry_ids: Vec::new(),
            governing_family_hints: Vec::new(),
            runtime_target: Some("runtime_bridge".to_string()),
            lease_mode: Some("governed_extension".to_string()),
            authority: CapabilityAuthorityDescriptor {
                tier_id: "automation".to_string(),
                tier_label: "Automation bridge".to_string(),
                governed_profile_id: Some("automation_bridge".to_string()),
                governed_profile_label: Some("Automation bridge".to_string()),
                summary: "summary".to_string(),
                detail: "detail".to_string(),
                signals: Vec::new(),
            },
            lease: CapabilityLeaseDescriptor {
                availability: "ready".to_string(),
                availability_label: "Ready".to_string(),
                runtime_target_id: Some("runtime_bridge".to_string()),
                runtime_target_label: Some("Runtime bridge".to_string()),
                mode_id: Some("governed_extension".to_string()),
                mode_label: Some("Governed extension".to_string()),
                summary: "summary".to_string(),
                detail: "detail".to_string(),
                requires_auth: false,
                signals: Vec::new(),
            },
        }],
        connectors: Vec::new(),
        skill_catalog: Vec::new(),
        skill_sources: Vec::new(),
        extension_manifests: vec![ExtensionManifestRecord {
            extension_id: "manifest:alpha".to_string(),
            manifest_kind: "codex_plugin".to_string(),
            manifest_path: "/workspace/plugin/.codex-plugin/plugin.json".to_string(),
            root_path: "/workspace/plugin".to_string(),
            source_label: "Workspace source".to_string(),
            source_uri: "/workspace/plugin".to_string(),
            source_kind: "tracked_source".to_string(),
            enabled: true,
            name: "alpha".to_string(),
            display_name: Some("Alpha Hooks".to_string()),
            version: None,
            description: None,
            developer_name: None,
            author_name: None,
            author_email: None,
            author_url: None,
            category: None,
            trust_posture: "local_only".to_string(),
            governed_profile: "automation_bridge".to_string(),
            homepage: None,
            repository: None,
            license: None,
            keywords: Vec::new(),
            capabilities: Vec::new(),
            default_prompts: Vec::new(),
            contributions: vec![ExtensionContributionRecord {
                kind: "hooks".to_string(),
                label: "Hooks".to_string(),
                path: Some("hooks/main.ts".to_string()),
                item_count: Some(1),
                detail: Some("Runtime automation hooks".to_string()),
            }],
            filesystem_skills: Vec::<SkillSourceDiscoveredSkill>::new(),
            marketplace_name: None,
            marketplace_display_name: None,
            marketplace_category: None,
            marketplace_installation_policy: None,
            marketplace_authentication_policy: None,
            marketplace_products: Vec::new(),
            marketplace_available_version: None,
            marketplace_catalog_issued_at_ms: None,
            marketplace_catalog_expires_at_ms: None,
            marketplace_catalog_refreshed_at_ms: None,
            marketplace_catalog_refresh_source: None,
            marketplace_catalog_channel: None,
            marketplace_catalog_source_id: None,
            marketplace_catalog_source_label: None,
            marketplace_catalog_source_uri: None,
            marketplace_package_url: None,
            marketplace_catalog_refresh_bundle_id: None,
            marketplace_catalog_refresh_bundle_label: None,
            marketplace_catalog_refresh_bundle_issued_at_ms: None,
            marketplace_catalog_refresh_bundle_expires_at_ms: None,
            marketplace_catalog_refresh_available_version: None,
            marketplace_verification_status: None,
            marketplace_signature_algorithm: None,
            marketplace_signer_identity: None,
            marketplace_publisher_id: None,
            marketplace_signing_key_id: None,
            marketplace_publisher_label: None,
            marketplace_publisher_trust_status: None,
            marketplace_publisher_trust_source: None,
            marketplace_publisher_root_id: None,
            marketplace_publisher_root_label: None,
            marketplace_authority_bundle_id: None,
            marketplace_authority_bundle_label: None,
            marketplace_authority_bundle_issued_at_ms: None,
            marketplace_authority_trust_bundle_id: None,
            marketplace_authority_trust_bundle_label: None,
            marketplace_authority_trust_bundle_issued_at_ms: None,
            marketplace_authority_trust_bundle_expires_at_ms: None,
            marketplace_authority_trust_bundle_status: None,
            marketplace_authority_trust_issuer_id: None,
            marketplace_authority_trust_issuer_label: None,
            marketplace_authority_id: None,
            marketplace_authority_label: None,
            marketplace_publisher_statement_issued_at_ms: None,
            marketplace_publisher_trust_detail: None,
            marketplace_publisher_revoked_at_ms: None,
            marketplace_verification_error: None,
            marketplace_verified_at_ms: None,
            marketplace_verification_source: None,
            marketplace_verified_digest_sha256: None,
            marketplace_trust_score_label: None,
            marketplace_trust_score_source: None,
            marketplace_trust_recommendation: None,
        }],
        local_engine,
    };

    let hook_snapshot = build_session_hook_snapshot(
        snapshot,
        ShieldRememberedApprovalSnapshot {
            generated_at_ms: 1,
            active_decision_count: 0,
            recent_receipt_count: 1,
            decisions: Vec::new(),
            recent_receipts: vec![ShieldApprovalHookReceipt {
                receipt_id: "approval-1".to_string(),
                timestamp_ms: 84,
                hook_kind: "pre_run_approval_hook".to_string(),
                status: "matched".to_string(),
                summary: "Used remembered approval for Mail read.".to_string(),
                connector_id: "mail.primary".to_string(),
                action_id: "mail.read_latest".to_string(),
                decision_id: Some("decision-1".to_string()),
            }],
        },
        Some("session-123".to_string()),
        Some("/workspace".to_string()),
    );

    assert_eq!(hook_snapshot.active_hook_count, 1);
    assert_eq!(hook_snapshot.runtime_receipt_count, 1);
    assert_eq!(hook_snapshot.approval_receipt_count, 1);
    assert_eq!(hook_snapshot.hooks.len(), 1);
    assert_eq!(
        hook_snapshot.hooks[0].authority_tier_label,
        "Automation bridge"
    );
    assert_eq!(
        hook_snapshot.hooks[0].session_scope_label,
        "Matches current workspace"
    );
    assert_eq!(
        hook_snapshot.recent_receipts[0].tool_name,
        "mail.primary · mail.read_latest"
    );
    assert_eq!(hook_snapshot.recent_receipts[1].tool_name, "hook_worker");
}
