// Parity — opened states of Settings surface dialogs, ported bit-for-bit from
// the IOI demo reference's LIVE DOM captures: exact element tree, classes,
// verbatim SVG paths and copy. Each export returns the converted role="dialog"
// element (content-only, data-state="open"; no outer positioning).

import type { CSSProperties } from "react";

const ChevronDownGlyph = () => (
  <svg aria-hidden="true" width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8 10L12 14L16 10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" /></svg>
);
const CloseGlyph = () => (
  <svg aria-hidden="true" width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.75 7.75L16.25 16.25M16.25 7.75L7.75 16.25" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" /></svg>
);
const InfoGlyph = () => (
  <svg className="text-content-info shrink-0" aria-hidden="true" width="16px" height="16px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10.75 11H12L12 16.25M21.25 12C21.25 17.1086 17.1086 21.25 12 21.25C6.89137 21.25 2.75 17.1086 2.75 12C2.75 6.89137 6.89137 2.75 12 2.75C17.1086 2.75 21.25 6.89137 21.25 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" /><path d="M11.5 7.375H11.375V7.5V8.5V8.625H11.5H12.5H12.625V8.5V7.5V7.375H12.5H11.5Z" fill="currentColor" stroke="currentColor" strokeWidth="0.25" /></svg>
);
const ExternalLinkGlyph = () => (
  <svg aria-hidden="true" width="16px" height="16px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M18.25 14V20.25H3.75V5.75H9.25M13.75 3.75H20.25V10.25M11 13L19.5 4.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" /></svg>
);

const hiddenSelectStyle: CSSProperties = { border: "0px", clip: "rect(0px, 0px, 0px, 0px)", clipPath: "inset(50%)", height: "1px", margin: "-1px", overflow: "hidden", padding: "0px", position: "absolute", width: "1px", whiteSpace: "nowrap" };

const hiddenCheckboxStyle: CSSProperties = { transform: "translateX(-100%)", position: "absolute", pointerEvents: "none", opacity: 0, margin: "0px", width: "16px", height: "16px" };

export function AddCreditsDialog() {
  return (
    <div role="dialog" id="radix-:r1k:" aria-describedby="radix-:r1m:" aria-labelledby="radix-:r1l:" data-state="open" className="relative flex max-h-[90%] w-full flex-col overflow-x-auto p-6 rounded-xl border border-border-base bg-surface-secondary shadow-modal duration-200 @container data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 max-w-md" data-track-location="billing_modal" tabIndex={-1} style={{ pointerEvents: "auto" }}>
      <header className="mb-6 flex flex-col gap-1.5 text-left">
        <h2 id="radix-:r1l:" className="text-lg font-semibold leading-none tracking-tight text-content-primary">Add Credits</h2>
        <p id="radix-:r1m:" className="m-0 p-0 text-base text-content-secondary">Add OCUs to continue using Hypervisor. This one-time purchase is available immediately and won't change your subscription.</p>
      </header>
      <div className="overflow-x-visible px-1 text-base py-1.5 text-content-muted flex flex-col gap-6">
        <div className="flex flex-col gap-2">
          <label htmlFor="amount-select" className="text-md font-medium text-content-primary">Select amount</label>
          <div className="relative w-full">
            <span className="sr-only">Select</span>
            <div aria-hidden="true" data-react-aria-prevent-focus="true" data-a11y-ignore="aria-hidden-focus" data-testid="hidden-select-container" style={hiddenSelectStyle}>
              <label>Select<select tabIndex={-1}><option></option><option value="40">40 OCUs – $10</option><option value="100">100 OCUs – $25</option><option value="200">200 OCUs – $50</option><option value="400">400 OCUs – $100</option><option value="1000">1000 OCUs – $250</option><option value="2000">2000 OCUs – $500</option><option value="4000">4000 OCUs – $1000</option><option value="8000">8000 OCUs – $2000</option></select></label>
            </div>
            <button type="button" tabIndex={0} data-react-aria-pressable="true" id="amount-select" aria-label="Select" aria-labelledby="react-aria2806682864-:r22: amount-select" aria-haspopup="listbox" className="flex w-full items-center justify-between gap-2 text-base text-content-primary outline-none disabled:cursor-not-allowed disabled:opacity-50 h-9 px-3 rounded-lg border border-border-input-default bg-surface-input transition-all duration-150 ease-out focus:border-border-input-active focus:ring-4 focus:ring-ring-default focus:ring-offset-0 aria-expanded:border-border-input-active aria-expanded:ring-4 aria-expanded:ring-ring-default aria-expanded:ring-offset-0">
              <span id="react-aria2806682864-:r22:" className="truncate">100 OCUs – $25</span>
              <ChevronDownGlyph />
            </button>
          </div>
        </div>
      </div>
      <footer className="flex gap-2 sm:flex-row mt-6 flex-row justify-between">
        <button className="select-none inline-flex items-center font-medium justify-center whitespace-nowrap transition-colors rounded-lg disabled:text-content-tertiary disabled:pointer-events-none disabled:shadow-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-offset-1 focus-visible:animate-focus-pulse motion-reduce:animate-none active:outline-0 focus:ring-0 bg-surface-button-clear hover:bg-surface-button-clear-accent data-[state=open]:bg-surface-button-clear-accent border border-border-base text-content-primary hover:text-content-accent data-[state=open]:text-content-accent disabled:border-opacity-1 focus-visible:outline-border-brand gap-2 px-4 py-2 h-9 text-base" type="button"><span className="truncate">Cancel</span></button>
        <button className="select-none inline-flex items-center font-medium justify-center whitespace-nowrap transition-colors rounded-lg border-0 disabled:border-opacity-0 disabled:pointer-events-none disabled:shadow-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-offset-1 focus-visible:animate-focus-pulse motion-reduce:animate-none active:outline-0 focus:ring-0 bg-surface-button-primary text-content-primary-inverted hover:bg-surface-button-primary-accent disabled:opacity-50 disabled:bg-surface-primary-inverted disabled:text-content-primary-inverted focus-visible:outline-border-brand gap-2 px-4 py-2 h-9 text-base" data-tracking-id="continue-to-confirmation"><span className="truncate">Continue</span></button>
      </footer>
      <button className="select-none inline-flex items-center font-medium justify-center whitespace-nowrap transition-colors rounded-lg border-0 disabled:border-opacity-0 disabled:pointer-events-none disabled:shadow-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-offset-1 focus-visible:animate-focus-pulse motion-reduce:animate-none active:outline-0 focus:ring-0 bg-surface-button-clear hover:bg-surface-button-clear-accent hover:text-content-accent data-[state=open]:bg-surface-button-clear-accent data-[state=open]:text-content-accent disabled:opacity-50 disabled:text-content-primary focus-visible:outline-border-brand gap-2 h-8 text-base absolute right-4 top-4 aspect-square p-0 text-content-muted" aria-label="Close" type="button">
        <CloseGlyph />
      </button>
    </div>
  );
}

export function ConnectIntegrationDialog() {
  return (
    <div role="dialog" id="radix-:r2f:" aria-describedby="radix-:r2h:" aria-labelledby="radix-:r2g:" data-state="open" className="relative flex max-h-[90%] w-full max-w-lg flex-col overflow-x-auto p-6 rounded-xl border border-border-base bg-surface-secondary shadow-modal duration-200 @container data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95" data-track-location="integration_config_modal" tabIndex={-1} style={{ pointerEvents: "auto" }}>
      <header className="mb-6 flex flex-col gap-1.5 text-left">
        <h2 id="radix-:r2g:" className="text-lg font-semibold leading-none tracking-tight text-content-primary">Add MCP Integration</h2>
        <p id="radix-:r2h:" className="m-0 p-0 text-base text-content-secondary">Connect an MCP server to make it available to your organization.</p>
      </header>
      <form>
        <div className="overflow-x-visible px-1 text-base py-1.5 text-content-muted">
          <div className="flex flex-col gap-4">
            <div className="group flex flex-col gap-1" data-testid="custom-integration-name-field">
              <label className="text-base font-normal text-content-primary peer-disabled:cursor-text peer-disabled:opacity-70 flex flex-col gap-1">Name<span className="font-normal"><input className="p-0 outline-none file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-content-muted text-content-primary flex items-center gap-2 h-9 w-full max-w-[600px] px-3 py-2 rounded-lg border border-border-light text-base disabled:cursor-text focus-within:ring-4 focus-within:ring-ring-default focus-visible:ring-4 focus-visible:ring-ring-default group-data-[state=error]:border-border-error group-data-[state=error]:ring-ring-destructive disabled:bg-inherit bg-surface-input [&amp;[readonly]]:border-border-subtle [&amp;[readonly]]:bg-transparent data-[readonly]:border-border-subtle data-[readonly]:bg-transparent" placeholder="e.g. Hex, Sentry" data-testid="custom-integration-name-input" defaultValue="" /></span></label>
            </div>
            <div className="group flex flex-col gap-1" data-testid="custom-integration-mcp-url-field">
              <label className="text-base font-normal text-content-primary peer-disabled:cursor-text peer-disabled:opacity-70 flex flex-col gap-1">MCP URL<span className="font-normal"><input className="p-0 outline-none file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-content-muted text-content-primary flex items-center gap-2 h-9 w-full max-w-[600px] px-3 py-2 rounded-lg border border-border-light text-base disabled:cursor-text focus-within:ring-4 focus-within:ring-ring-default focus-visible:ring-4 focus-visible:ring-ring-default group-data-[state=error]:border-border-error group-data-[state=error]:ring-ring-destructive disabled:bg-inherit bg-surface-input [&amp;[readonly]]:border-border-subtle [&amp;[readonly]]:bg-transparent data-[readonly]:border-border-subtle data-[readonly]:bg-transparent" placeholder="e.g. https://hex.tech/mcp/sse" data-testid="custom-integration-mcp-url-input" defaultValue="" /></span></label><span className="text-sm text-content-secondary">The MCP server endpoint URL</span>
            </div>
            <div className="flex flex-col gap-1">
              <label className="text-base font-normal text-content-primary peer-disabled:cursor-text peer-disabled:opacity-70" id=":r2d:">OAuth setup</label>
              <div dir="ltr" data-orientation="horizontal" className="@container">
                <div role="tablist" aria-orientation="horizontal" className="scrollbar-hide flex min-h-9 flex-col justify-stretch gap-0.5 overflow-x-auto rounded-lg border border-transparent bg-surface-button-tab-base p-[3px] @md:flex-row @md:justify-between dark:border-border-subtle" aria-labelledby=":r2d:" tabIndex={0} data-orientation="horizontal" style={{ outline: "none" }}>
                  <button type="button" role="tab" aria-selected="true" aria-controls="radix-:r2u:-content-dcr" data-state="active" id="radix-:r2u:-trigger-dcr" className="inline-flex flex-row h-7 items-center @md:justify-center gap-2 overflow-hidden rounded-md border-transparent px-1.5 py-1 text-base text-content-strong text-left @md:text-center min-w-0 flex-shrink flex-grow hover:text-content-primary data-[state=active]:bg-surface-button-tab-primary data-[state=active]:border-transparent data-[state=active]:text-content-primary disabled:opacity-50 disabled:hover:text-content-strong" tabIndex={-1} data-orientation="horizontal" data-radix-collection-item=""><span className="truncate">Automatic (DCR)</span></button>
                  <button type="button" role="tab" aria-selected="false" aria-controls="radix-:r2u:-content-manual" data-state="inactive" id="radix-:r2u:-trigger-manual" className="inline-flex flex-row h-7 items-center @md:justify-center gap-2 overflow-hidden rounded-md border-transparent px-1.5 py-1 text-base text-content-strong text-left @md:text-center min-w-0 flex-shrink flex-grow hover:text-content-primary data-[state=active]:bg-surface-button-tab-primary data-[state=active]:border-transparent data-[state=active]:text-content-primary disabled:opacity-50 disabled:hover:text-content-strong" tabIndex={-1} data-orientation="horizontal" data-radix-collection-item=""><span className="truncate">Manual</span></button>
                </div>
              </div>
            </div>
            <div data-testid="banner" className="flex items-center gap-2 rounded-lg text-base border px-3 py-2 shadow-sm bg-surface-banner-info-subtle text-content-info border-border-info justify-center">
              <div className="flex min-w-0 flex-1 gap-2 pr-2 items-start">
                <span className="flex h-[18px] shrink-0 items-center"><InfoGlyph /></span>
                <div data-testid="banner-text" className="min-w-0 [overflow-wrap:anywhere]">The MCP server must support RFC 7591 OAuth 2.0 Dynamic Client Registration (DCR).</div>
              </div>
              <div className="shrink-0">
                <a className="inline-flex items-center gap-1 text-sm font-medium text-content-primary" target="_blank" rel="noreferrer" href="https://ona.com/docs/ona/mcp#custom-organization-mcp-integrations">Learn more<ExternalLinkGlyph /></a>
              </div>
            </div>
            <div className="group flex flex-col gap-1" data-testid="custom-integration-description-field">
              <label className="text-base font-normal text-content-primary peer-disabled:cursor-text peer-disabled:opacity-70 flex flex-col gap-1">Description<span className="font-normal"><input className="p-0 outline-none file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-content-muted text-content-primary flex items-center gap-2 h-9 w-full max-w-[600px] px-3 py-2 rounded-lg border border-border-light text-base disabled:cursor-text focus-within:ring-4 focus-within:ring-ring-default focus-visible:ring-4 focus-visible:ring-ring-default group-data-[state=error]:border-border-error group-data-[state=error]:ring-ring-destructive disabled:bg-inherit bg-surface-input [&amp;[readonly]]:border-border-subtle [&amp;[readonly]]:bg-transparent data-[readonly]:border-border-subtle data-[readonly]:bg-transparent" placeholder="A short description of this integration" data-testid="custom-integration-description-input" defaultValue="" /></span></label><span className="text-sm text-content-secondary">Optional</span>
            </div>
            <div className="group flex flex-col gap-1">
              <label className="text-base font-normal text-content-primary peer-disabled:cursor-text peer-disabled:opacity-70 flex flex-col gap-1">Categories<span className="font-normal"><div className="flex flex-col gap-1">
                <div className="group flex flex-col gap-1" data-testid="category-checkbox-source-control"><label className="flex max-w-lg cursor-pointer items-center justify-start space-x-2" htmlFor=":r31:"><button type="button" role="checkbox" aria-checked="false" data-state="unchecked" value="on" className="size-4 rounded flex items-center justify-center outline-none transition-opacity duration-100 focus-visible:ring-4 focus-visible:ring-ring-default data-[state=checked]:border-0 data-[state=checked]:bg-content-brand data-[state=checked]:hover:opacity-80 data-[state=checked]:disabled:opacity-40 data-[state=indeterminate]:border-0 data-[state=indeterminate]:bg-surface-brand data-[state=indeterminate]:hover:opacity-80 data-[state=indeterminate]:disabled:opacity-40 ona-theme:data-[state=indeterminate]:bg-content-brand data-[state=unchecked]:border data-[state=unchecked]:border-border-input-default data-[state=unchecked]:bg-transparent data-[state=unchecked]:hover:bg-surface-secondary data-[state=unchecked]:disabled:bg-surface-secondary shrink-0" id=":r31:"><span className="flex size-3 items-center justify-center"></span></button><input type="checkbox" aria-hidden="true" tabIndex={-1} value="on" style={hiddenCheckboxStyle} /><div className="flex flex-col"><div className="cursor-pointer select-none text-base font-normal text-content-primary">Source control</div></div></label></div>
                <div className="group flex flex-col gap-1" data-testid="category-checkbox-communication"><label className="flex max-w-lg cursor-pointer items-center justify-start space-x-2" htmlFor=":r32:"><button type="button" role="checkbox" aria-checked="false" data-state="unchecked" value="on" className="size-4 rounded flex items-center justify-center outline-none transition-opacity duration-100 focus-visible:ring-4 focus-visible:ring-ring-default data-[state=checked]:border-0 data-[state=checked]:bg-content-brand data-[state=checked]:hover:opacity-80 data-[state=checked]:disabled:opacity-40 data-[state=indeterminate]:border-0 data-[state=indeterminate]:bg-surface-brand data-[state=indeterminate]:hover:opacity-80 data-[state=indeterminate]:disabled:opacity-40 ona-theme:data-[state=indeterminate]:bg-content-brand data-[state=unchecked]:border data-[state=unchecked]:border-border-input-default data-[state=unchecked]:bg-transparent data-[state=unchecked]:hover:bg-surface-secondary data-[state=unchecked]:disabled:bg-surface-secondary shrink-0" id=":r32:"><span className="flex size-3 items-center justify-center"></span></button><input type="checkbox" aria-hidden="true" tabIndex={-1} value="on" style={hiddenCheckboxStyle} /><div className="flex flex-col"><div className="cursor-pointer select-none text-base font-normal text-content-primary">Communication</div></div></label></div>
                <div className="group flex flex-col gap-1" data-testid="category-checkbox-project-management"><label className="flex max-w-lg cursor-pointer items-center justify-start space-x-2" htmlFor=":r33:"><button type="button" role="checkbox" aria-checked="false" data-state="unchecked" value="on" className="size-4 rounded flex items-center justify-center outline-none transition-opacity duration-100 focus-visible:ring-4 focus-visible:ring-ring-default data-[state=checked]:border-0 data-[state=checked]:bg-content-brand data-[state=checked]:hover:opacity-80 data-[state=checked]:disabled:opacity-40 data-[state=indeterminate]:border-0 data-[state=indeterminate]:bg-surface-brand data-[state=indeterminate]:hover:opacity-80 data-[state=indeterminate]:disabled:opacity-40 ona-theme:data-[state=indeterminate]:bg-content-brand data-[state=unchecked]:border data-[state=unchecked]:border-border-input-default data-[state=unchecked]:bg-transparent data-[state=unchecked]:hover:bg-surface-secondary data-[state=unchecked]:disabled:bg-surface-secondary shrink-0" id=":r33:"><span className="flex size-3 items-center justify-center"></span></button><input type="checkbox" aria-hidden="true" tabIndex={-1} value="on" style={hiddenCheckboxStyle} /><div className="flex flex-col"><div className="cursor-pointer select-none text-base font-normal text-content-primary">Project management</div></div></label></div>
                <div className="group flex flex-col gap-1" data-testid="category-checkbox-observability"><label className="flex max-w-lg cursor-pointer items-center justify-start space-x-2" htmlFor=":r34:"><button type="button" role="checkbox" aria-checked="false" data-state="unchecked" value="on" className="size-4 rounded flex items-center justify-center outline-none transition-opacity duration-100 focus-visible:ring-4 focus-visible:ring-ring-default data-[state=checked]:border-0 data-[state=checked]:bg-content-brand data-[state=checked]:hover:opacity-80 data-[state=checked]:disabled:opacity-40 data-[state=indeterminate]:border-0 data-[state=indeterminate]:bg-surface-brand data-[state=indeterminate]:hover:opacity-80 data-[state=indeterminate]:disabled:opacity-40 ona-theme:data-[state=indeterminate]:bg-content-brand data-[state=unchecked]:border data-[state=unchecked]:border-border-input-default data-[state=unchecked]:bg-transparent data-[state=unchecked]:hover:bg-surface-secondary data-[state=unchecked]:disabled:bg-surface-secondary shrink-0" id=":r34:"><span className="flex size-3 items-center justify-center"></span></button><input type="checkbox" aria-hidden="true" tabIndex={-1} value="on" style={hiddenCheckboxStyle} /><div className="flex flex-col"><div className="cursor-pointer select-none text-base font-normal text-content-primary">Observability</div></div></label></div>
                <div className="group flex flex-col gap-1" data-testid="category-checkbox-data-analytics"><label className="flex max-w-lg cursor-pointer items-center justify-start space-x-2" htmlFor=":r35:"><button type="button" role="checkbox" aria-checked="false" data-state="unchecked" value="on" className="size-4 rounded flex items-center justify-center outline-none transition-opacity duration-100 focus-visible:ring-4 focus-visible:ring-ring-default data-[state=checked]:border-0 data-[state=checked]:bg-content-brand data-[state=checked]:hover:opacity-80 data-[state=checked]:disabled:opacity-40 data-[state=indeterminate]:border-0 data-[state=indeterminate]:bg-surface-brand data-[state=indeterminate]:hover:opacity-80 data-[state=indeterminate]:disabled:opacity-40 ona-theme:data-[state=indeterminate]:bg-content-brand data-[state=unchecked]:border data-[state=unchecked]:border-border-input-default data-[state=unchecked]:bg-transparent data-[state=unchecked]:hover:bg-surface-secondary data-[state=unchecked]:disabled:bg-surface-secondary shrink-0" id=":r35:"><span className="flex size-3 items-center justify-center"></span></button><input type="checkbox" aria-hidden="true" tabIndex={-1} value="on" style={hiddenCheckboxStyle} /><div className="flex flex-col"><div className="cursor-pointer select-none text-base font-normal text-content-primary">Data &amp; analytics</div></div></label></div>
                <div className="group flex flex-col gap-1" data-testid="category-checkbox-knowledge"><label className="flex max-w-lg cursor-pointer items-center justify-start space-x-2" htmlFor=":r36:"><button type="button" role="checkbox" aria-checked="false" data-state="unchecked" value="on" className="size-4 rounded flex items-center justify-center outline-none transition-opacity duration-100 focus-visible:ring-4 focus-visible:ring-ring-default data-[state=checked]:border-0 data-[state=checked]:bg-content-brand data-[state=checked]:hover:opacity-80 data-[state=checked]:disabled:opacity-40 data-[state=indeterminate]:border-0 data-[state=indeterminate]:bg-surface-brand data-[state=indeterminate]:hover:opacity-80 data-[state=indeterminate]:disabled:opacity-40 ona-theme:data-[state=indeterminate]:bg-content-brand data-[state=unchecked]:border data-[state=unchecked]:border-border-input-default data-[state=unchecked]:bg-transparent data-[state=unchecked]:hover:bg-surface-secondary data-[state=unchecked]:disabled:bg-surface-secondary shrink-0" id=":r36:"><span className="flex size-3 items-center justify-center"></span></button><input type="checkbox" aria-hidden="true" tabIndex={-1} value="on" style={hiddenCheckboxStyle} /><div className="flex flex-col"><div className="cursor-pointer select-none text-base font-normal text-content-primary">Knowledge</div></div></label></div>
                <div className="group flex flex-col gap-1" data-testid="category-checkbox-ai"><label className="flex max-w-lg cursor-pointer items-center justify-start space-x-2" htmlFor=":r37:"><button type="button" role="checkbox" aria-checked="false" data-state="unchecked" value="on" className="size-4 rounded flex items-center justify-center outline-none transition-opacity duration-100 focus-visible:ring-4 focus-visible:ring-ring-default data-[state=checked]:border-0 data-[state=checked]:bg-content-brand data-[state=checked]:hover:opacity-80 data-[state=checked]:disabled:opacity-40 data-[state=indeterminate]:border-0 data-[state=indeterminate]:bg-surface-brand data-[state=indeterminate]:hover:opacity-80 data-[state=indeterminate]:disabled:opacity-40 ona-theme:data-[state=indeterminate]:bg-content-brand data-[state=unchecked]:border data-[state=unchecked]:border-border-input-default data-[state=unchecked]:bg-transparent data-[state=unchecked]:hover:bg-surface-secondary data-[state=unchecked]:disabled:bg-surface-secondary shrink-0" id=":r37:"><span className="flex size-3 items-center justify-center"></span></button><input type="checkbox" aria-hidden="true" tabIndex={-1} value="on" style={hiddenCheckboxStyle} /><div className="flex flex-col"><div className="cursor-pointer select-none text-base font-normal text-content-primary">AI</div></div></label></div>
                <div className="group flex flex-col gap-1" data-testid="category-checkbox-automation-triggers"><label className="flex max-w-lg cursor-pointer items-center justify-start space-x-2" htmlFor=":r38:"><button type="button" role="checkbox" aria-checked="false" data-state="unchecked" value="on" className="size-4 rounded flex items-center justify-center outline-none transition-opacity duration-100 focus-visible:ring-4 focus-visible:ring-ring-default data-[state=checked]:border-0 data-[state=checked]:bg-content-brand data-[state=checked]:hover:opacity-80 data-[state=checked]:disabled:opacity-40 data-[state=indeterminate]:border-0 data-[state=indeterminate]:bg-surface-brand data-[state=indeterminate]:hover:opacity-80 data-[state=indeterminate]:disabled:opacity-40 ona-theme:data-[state=indeterminate]:bg-content-brand data-[state=unchecked]:border data-[state=unchecked]:border-border-input-default data-[state=unchecked]:bg-transparent data-[state=unchecked]:hover:bg-surface-secondary data-[state=unchecked]:disabled:bg-surface-secondary shrink-0" id=":r38:"><span className="flex size-3 items-center justify-center"></span></button><input type="checkbox" aria-hidden="true" tabIndex={-1} value="on" style={hiddenCheckboxStyle} /><div className="flex flex-col"><div className="cursor-pointer select-none text-base font-normal text-content-primary">Automation triggers</div></div></label></div>
              </div></span></label><span className="text-sm text-content-secondary">Select at least one</span>
            </div>
          </div>
        </div>
        <footer className="flex gap-2 sm:flex-row mt-6 flex-row justify-between">
          <button className="select-none inline-flex items-center font-medium justify-center whitespace-nowrap transition-colors rounded-lg disabled:text-content-tertiary disabled:pointer-events-none disabled:shadow-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-offset-1 focus-visible:animate-focus-pulse motion-reduce:animate-none active:outline-0 focus:ring-0 bg-surface-button-clear hover:bg-surface-button-clear-accent data-[state=open]:bg-surface-button-clear-accent border border-border-base text-content-primary hover:text-content-accent data-[state=open]:text-content-accent disabled:border-opacity-1 focus-visible:outline-border-brand gap-2 px-4 py-2 h-9 text-base" type="button" data-tracking-id="create-custom-integration-cancel"><span className="truncate">Cancel</span></button>
          <button className="select-none inline-flex items-center font-medium justify-center whitespace-nowrap transition-colors rounded-lg border-0 disabled:border-opacity-0 disabled:pointer-events-none disabled:shadow-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-offset-1 focus-visible:animate-focus-pulse motion-reduce:animate-none active:outline-0 focus:ring-0 bg-surface-button-primary text-content-primary-inverted hover:bg-surface-button-primary-accent disabled:opacity-50 disabled:bg-surface-primary-inverted disabled:text-content-primary-inverted focus-visible:outline-border-brand gap-2 px-4 py-2 h-9 text-base" aria-busy="false" type="submit" data-tracking-id="create-custom-integration-submit"><span className="truncate">Create</span></button>
        </footer>
      </form>
      <button className="select-none inline-flex items-center font-medium justify-center whitespace-nowrap transition-colors rounded-lg border-0 disabled:border-opacity-0 disabled:pointer-events-none disabled:shadow-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-offset-1 focus-visible:animate-focus-pulse motion-reduce:animate-none active:outline-0 focus:ring-0 bg-surface-button-clear hover:bg-surface-button-clear-accent hover:text-content-accent data-[state=open]:bg-surface-button-clear-accent data-[state=open]:text-content-accent disabled:opacity-50 disabled:text-content-primary focus-visible:outline-border-brand gap-2 h-8 text-base absolute right-4 top-4 aspect-square p-0 text-content-muted" aria-label="Close" type="button">
        <CloseGlyph />
      </button>
    </div>
  );
}
