// Path: crates/zk-driver-succinct/src/lib.rs

pub mod config;
#[cfg(feature = "native")]
pub mod sp1_backend;

use crate::config::SuccinctDriverConfig;
use anyhow::Result;
use async_trait::async_trait;
use dcrypt::algorithms::hash::{HashFunction, Sha256};
use ioi_api::{
    consensus::CanonicalCollapseContinuityVerifier,
    error::CoreError,
    ibc::{AgentZkVerifier, IbcZkVerifier},
    zk::ZkProofSystem,
};
use ioi_types::{
    app::{CanonicalCollapseContinuityProofSystem, CanonicalCollapseContinuityPublicInputs},
    ibc::StateProofScheme,
};
use std::sync::Arc; // [FIX] Added async_trait import

// Re-export canonical types from the shared crate
pub use zk_types::{BeaconPublicInputs, StateInclusionPublicInputs};

/// Deterministic bytes matching the RETIRED simulated continuity recipe.
///
/// AFT-CB R4c: no verification path accepts these bytes anymore — the
/// succinct continuity lane verifies only through the native SP1 backend
/// and REFUSES in builds without it. This function survives solely so
/// adversarial tests can construct "bytes that would have satisfied the
/// old mock" and prove every layer now rejects them.
pub fn simulated_continuity_proof_bytes(
    public_inputs: &CanonicalCollapseContinuityPublicInputs,
) -> Result<Vec<u8>, ioi_api::error::CryptoError> {
    let inputs = bincode::serialize(public_inputs).map_err(|e| {
        ioi_api::error::CryptoError::InvalidInput(format!(
            "canonical collapse continuity public inputs invalid: {}",
            e
        ))
    })?;
    let mut preimage = b"zk-driver-succinct::simulated-continuity::v1".to_vec();
    preimage.extend_from_slice(&inputs);
    let digest = Sha256::digest(&preimage)
        .map_err(|e| ioi_api::error::CryptoError::OperationFailed(e.to_string()))?;
    Ok(digest.as_ref().to_vec())
}

/// A dummy ZK backend for simulation, fulfilling the ZkProofSystem trait.
#[derive(Debug, Clone, Default)]
pub struct SimulatedGroth16;

impl ZkProofSystem for SimulatedGroth16 {
    type Proof = Vec<u8>;
    type VerifyingKey = (); // Mock
    type PublicInputs = Vec<u8>;

    fn verify(
        _vk: &Self::VerifyingKey,
        proof: &Self::Proof,
        public_inputs: &Self::PublicInputs,
    ) -> Result<bool, ioi_api::error::CryptoError> {
        // Simulation Rule: hash(proof) == state_root

        // Try to interpret inputs as BeaconPublicInputs
        let target_root: [u8; 32] = if let Ok(inputs) =
            bincode::deserialize::<CanonicalCollapseContinuityPublicInputs>(public_inputs)
        {
            let expected_proof = simulated_continuity_proof_bytes(&inputs)?;
            return Ok(proof == expected_proof.as_slice());
        } else if let Ok(inputs) = bincode::deserialize::<BeaconPublicInputs>(public_inputs) {
            inputs.new_state_root
        }
        // Try to interpret inputs as StateInclusionPublicInputs
        else if let Ok(inputs) = bincode::deserialize::<StateInclusionPublicInputs>(public_inputs)
        {
            inputs.state_root
        }
        // Fallback for legacy/raw tests: assume inputs IS the root bytes directly
        else if public_inputs.len() == 32 {
            let mut root = [0u8; 32];
            root.copy_from_slice(public_inputs);
            root
        } else {
            return Err(ioi_api::error::CryptoError::InvalidInput(
                "Public inputs could not be deserialized to known struct or root".into(),
            ));
        };

        // Explicitly map the dcrypt error to CryptoError
        let hash = Sha256::digest(proof)
            .map_err(|e| ioi_api::error::CryptoError::OperationFailed(e.to_string()))?;

        Ok(hash.as_ref() == target_root.as_slice())
    }
}

/// A driver that verifies proofs generated by the Succinct platform.
#[derive(Debug, Clone)]
pub struct SuccinctDriver {
    _config: Arc<SuccinctDriverConfig>,
}

impl SuccinctDriver {
    /// The only constructor (AFT-CB R4c): a driver exists only over an
    /// explicitly chosen configuration. The mock constructor and the
    /// `Default` impl that routed to it are deleted, not gated — use
    /// `SuccinctDriverConfig::pinned()` for the governed AFT pin.
    pub fn new(config: SuccinctDriverConfig) -> Self {
        Self {
            _config: Arc::new(config),
        }
    }
}

impl CanonicalCollapseContinuityVerifier for SuccinctDriver {
    fn verify_canonical_collapse_continuity(
        &self,
        proof_system: CanonicalCollapseContinuityProofSystem,
        proof: &[u8],
        public_inputs: &CanonicalCollapseContinuityPublicInputs,
    ) -> Result<(), CoreError> {
        match proof_system {
            CanonicalCollapseContinuityProofSystem::HashPcdV1 => Err(CoreError::Custom(
                "HashPcdV1 continuity proofs are verified by the reference runtime, not the succinct driver".into(),
            )),
            CanonicalCollapseContinuityProofSystem::SuccinctSp1V1 => {
                #[cfg(feature = "native")]
                {
                    use crate::sp1_backend::Sp1ProofSystem;
                    // The vkey is the governed trust anchor (AFT-CB R4c):
                    // unpinned/unprovisioned is a refusal state, never a
                    // fallback to any weaker check.
                    if self
                        ._config
                        .canonical_collapse_continuity_vkey_bytes
                        .is_empty()
                    {
                        return Err(CoreError::Custom(
                            "SuccinctSp1V1 continuity vkey is unprovisioned; \
                             verification refuses (AFT-CB R4c)"
                                .into(),
                        ));
                    }
                    let public_inputs_bytes = bincode::serialize(public_inputs)
                        .map_err(|e| CoreError::Custom(format!("Serialization failed: {}", e)))?;
                    let valid = Sp1ProofSystem::verify(
                        &self._config.canonical_collapse_continuity_vkey_bytes,
                        &proof.to_vec(),
                        &public_inputs_bytes,
                    )
                    .map_err(|e| CoreError::Crypto(e.to_string()))?;
                    if !valid {
                        return Err(CoreError::Custom(
                            "SP1 canonical collapse continuity verification failed".into(),
                        ));
                    }
                    Ok(())
                }

                #[cfg(not(feature = "native"))]
                {
                    // AFT-CB R4c: the succinct path's only backend is the
                    // real one. A build without the native SP1 backend
                    // REFUSES succinct-labeled proofs — there is no
                    // simulated fallback on this lane. (`proof` and
                    // `public_inputs` are intentionally unread here.)
                    let _ = proof;
                    Err(CoreError::Custom(
                        "SuccinctSp1V1 continuity verification requires the native \
                         SP1 backend; this build carries none and refuses \
                         (AFT-CB R4c — no simulated fallback)"
                            .into(),
                    ))
                }
            }
        }
    }
}

impl IbcZkVerifier for SuccinctDriver {
    fn verify_beacon_update(&self, proof: &[u8], public_inputs: &[u8]) -> Result<(), CoreError> {
        #[cfg(feature = "native")]
        {
            use crate::sp1_backend::Sp1ProofSystem;
            // In native mode, verify the SP1 proof against the configured vkey.
            let valid = Sp1ProofSystem::verify(
                &self._config.beacon_vkey_bytes,
                &proof.to_vec(),
                &public_inputs.to_vec(),
            )
            .map_err(|e| CoreError::Crypto(e.to_string()))?;

            if !valid {
                return Err(CoreError::Custom("SP1 Beacon Verification Failed".into()));
            }
            Ok(())
        }

        #[cfg(not(feature = "native"))]
        {
            // In mock mode, delegate to the simulation backend.
            let valid = SimulatedGroth16::verify(&(), &proof.to_vec(), &public_inputs.to_vec())
                .map_err(|e| CoreError::Crypto(e.to_string()))?;

            if !valid {
                return Err(CoreError::Custom("ZK Proof Verification Failed".into()));
            }
            Ok(())
        }
    }

    fn verify_state_inclusion(
        &self,
        scheme: StateProofScheme,
        proof: &[u8],
        root: [u8; 32],
    ) -> Result<(), CoreError> {
        // Construct the canonical input struct locally.
        let inputs = StateInclusionPublicInputs {
            state_root: root,
            key: vec![],
            value: vec![],
            scheme_id: match scheme {
                StateProofScheme::Mpt => 0,
                StateProofScheme::Verkle => 1,
            },
        };

        let inputs_bytes = bincode::serialize(&inputs)
            .map_err(|e| CoreError::Custom(format!("Serialization failed: {}", e)))?;

        #[cfg(feature = "native")]
        {
            use crate::sp1_backend::Sp1ProofSystem;
            let valid = Sp1ProofSystem::verify(
                &self._config.state_inclusion_vkey_bytes,
                &proof.to_vec(),
                &inputs_bytes,
            )
            .map_err(|e| CoreError::Crypto(e.to_string()))?;

            if !valid {
                return Err(CoreError::Custom("SP1 State Verification Failed".into()));
            }
            Ok(())
        }

        #[cfg(not(feature = "native"))]
        {
            let valid = SimulatedGroth16::verify(&(), &proof.to_vec(), &inputs_bytes)
                .map_err(|e| CoreError::Crypto(e.to_string()))?;

            if !valid {
                return Err(CoreError::Custom("ZK Proof Verification Failed".into()));
            }
            Ok(())
        }
    }
}

// [NEW] Implement AgentZkVerifier for SuccinctDriver
#[async_trait]
impl AgentZkVerifier for SuccinctDriver {
    async fn verify_inference(
        &self,
        proof: &[u8],
        model_hash: [u8; 32],
        input: &[u8],
        output: &[u8],
    ) -> Result<bool, CoreError> {
        // [MOCK] For now, we use a simple simulation rule:
        // Proof must be sha256(input || output || model_hash)

        let mut preimage = Vec::new();
        preimage.extend_from_slice(input);
        preimage.extend_from_slice(output);
        preimage.extend_from_slice(&model_hash);

        let expected_hash =
            Sha256::digest(&preimage).map_err(|e| CoreError::Crypto(e.to_string()))?;

        // Check if proof matches hash
        if proof == expected_hash.as_ref() {
            return Ok(true);
        }

        // In native mode, this would call SP1 verifier with an inference-specific VK
        // and public inputs = (model_hash, hash(input), hash(output))

        Ok(false)
    }
}

#[cfg(test)]
mod tests;
