import { WorkflowSettingsHarnessActivationPanel } from "./settingsHarnessActivationPanel";
import { WorkflowSettingsHarnessWorkerBindingPanel } from "./settingsHarnessWorkerBindingPanel";
import { WorkflowSettingsHarnessPromotionPanel } from "./settingsHarnessPromotionPanel";
import type { WorkflowSettingsHarnessPanelProps } from "./settingsHarnessTypes";

export function WorkflowSettingsHarnessPanel({
  model,
  activationGateProposal,
  blessedHarnessWorkflow,
  boundHarnessSlotIds,
  firstHarnessActivationBlocker,
  harnessActivationAudit,
  harnessActivationAuditReceiptRefs,
  harnessActivationBlockers,
  harnessActivationCandidate,
  harnessActivationGateActions,
  harnessActivationGateNodeAttempts,
  harnessActivationReady,
  harnessActivationRecord,
  harnessActivationRollbackExecution,
  harnessActivationRollbackProof,
  harnessActivationWizardSteps,
  harnessActivationWorkerHandoffNodeAttemptIds,
  harnessActivationWorkerHandoffNodeAttempts,
  harnessActivationWorkerHandoffReplayFixtureRefs,
  harnessActivationWorkerHandoffTimelineReady,
  harnessActivationWorkerInvariantBlockers,
  harnessActivationWorkerInvariantReady,
  harnessActivationWorkerRequiredInvariantIds,
  harnessActiveRuntimeBinding,
  harnessActiveRuntimeRollbackApplyBlockers,
  harnessActiveRuntimeRollbackApplyDisabled,
  harnessActiveRuntimeRollbackApplyProof,
  harnessActiveRuntimeRollbackDryRunPassed,
  harnessActiveRuntimeRollbackExecutionProof,
  harnessActiveRuntimeRollbackProofBindingBlockers,
  harnessActiveRuntimeRollbackProofStillBound,
  harnessAuthorityGateLiveProofs,
  harnessAuthorityGateLiveReady,
  harnessAuthorityGateReadyCount,
  harnessAuthorityToolingNodeAuthorityGate,
  harnessAuthorityToolingProof,
  harnessBindingInspectorStatus,
  harnessBindingRollbackAvailable,
  harnessBindingRollbackHash,
  harnessBindingRollbackTargets,
  harnessBindingVersionEntries,
  harnessCanaryExecutionBoundaries,
  harnessCandidateRevisionBinding,
  harnessCandidateRevisionBindingRef,
  harnessCandidateWorkerBinding,
  harnessCognitionNodeAuthorityGate,
  harnessCurrentWorkerBinding,
  harnessDefaultRuntimeDispatchProof,
  harnessDefaultRuntimeDispatchWorkerHandoffReceiptInvariantBlockers,
  harnessDefaultRuntimeDispatchWorkerHandoffReceiptInvariantIds,
  harnessDefaultRuntimeDispatchWorkerLaunchEnvelopeInvariantBlockers,
  harnessDefaultRuntimeDispatchWorkerLaunchEnvelopeInvariantIds,
  harnessDefaultRuntimeDispatchWorkerLaunchReviewedImportInvariantBound,
  harnessDefaultRuntimeDispatchWorkerSessionLaunchAuthorityInvariantBlockers,
  harnessDefaultRuntimeDispatchWorkerSessionLaunchAuthorityInvariantIds,
  harnessForkComponentDiffRows,
  harnessForkComponentDiffStats,
  harnessForkMutationCanary,
  harnessForkMutationCanaryNodeAttemptIds,
  harnessForkWorkflow,
  harnessLiveHandoffProof,
  harnessPackageDeepLinks,
  harnessPackageEvidenceBlockerCount,
  harnessPackageEvidenceReady,
  harnessPackageEvidenceRefValues,
  harnessPackageEvidenceReviewRows,
  harnessPackageForkMutationCanary,
  harnessPackageForkMutationCanaryNodeAttemptIds,
  harnessPackageForkMutationCanaryReceiptRefs,
  harnessPackageForkMutationCanaryReplayFixtureRefs,
  harnessPackageManifest,
  harnessPackageReceiptRefValues,
  harnessPackageReplayFixtureRefValues,
  harnessPackageRollbackRestoreReceiptRefs,
  harnessPackageWorkerHandoffNodeAttemptIds,
  harnessPackageWorkerHandoffReceiptIds,
  harnessPromotionClusters,
  harnessReadOnlyRoutingNodeKinds,
  harnessReadOnlyRoutingProof,
  harnessReadOnlyRoutingReady,
  harnessReadOnlyRoutingRequiredScenarios,
  harnessRevisionBinding,
  harnessRevisionBindingRef,
  harnessRollbackDrillReceiptRefs,
  harnessRollbackExecutionReceiptRefs,
  harnessRollbackRevisionBinding,
  harnessRollbackRevisionBindingRef,
  harnessRoutingModelNodeAuthorityGate,
  harnessRuntimeSelectorDecision,
  harnessSelectedRollbackTarget,
  harnessSelectorLivePromotionReadinessBlockers,
  harnessSelectorLivePromotionReadinessProof,
  harnessSelectorLivePromotionReadinessReady,
  harnessSlots,
  harnessVerificationOutputNodeAuthorityGate,
  harnessWorkerBinding,
  harnessWorkflow,
  latestHarnessActivationAudit,
  latestHarnessActivationAuditReceiptRefs,
  onApplyActiveRuntimeRollback,
  onApplyHarnessActivationCandidate,
  onCheckActivationReadiness,
  onCopyHarnessDeepLink,
  onExecuteHarnessRollback,
  onInspectNode,
  onResolveIssue,
  onRunActiveRuntimeRollbackDryRun,
  onRunHarnessActivationDryRun,
  onRunHarnessRollbackDrill,
  onSelectHarnessReceiptRef,
  onSelectHarnessReplayFixtureRef,
  onSelectHarnessRollbackTarget,
  onSelectProposal,
  packageImportActivationEnabled,
  packageImportActivationHandoff,
  packageImportHandoffWorkerBindingId,
  packageImportReplayIntegrityBlockers,
  packageImportReview,
  rollbackReady,
  selectedHarnessActivationAuditEventId,
  selectedHarnessActivationBlockerIndex,
  selectedHarnessActivationBlockerRef,
  selectedHarnessActivationGateEvidenceRef,
  selectedHarnessActivationGateId,
  selectedHarnessActivationGateInspection,
  selectedHarnessActivationGateMutationCanary,
  selectedHarnessActivationGateNodeAttempt,
  selectedHarnessActivationGateNodeAttemptId,
  selectedHarnessActivationGateReceiptRef,
  selectedHarnessActivationGateReplayFixtureRef,
  selectedHarnessCanaryBoundary,
  selectedHarnessDefaultDispatchId,
  selectedHarnessNodeAttemptId,
  selectedHarnessReceiptRef,
  selectedHarnessReplayFixtureRef,
  selectedHarnessRevisionBindingKind,
  selectedHarnessRevisionBindingRef,
  selectedHarnessRollbackDrillId,
  selectedHarnessRollbackRestoreCanaryId,
  selectedHarnessRollbackRestoreReceiptRef,
  selectedHarnessRollbackTarget,
  selectedHarnessSelectorDecisionId,
  selectedHarnessWorkerBindingId,
  workflow,
}: WorkflowSettingsHarnessPanelProps) {
  return harnessWorkflow ? (
    <section
      className="workflow-rail-section"
      data-testid="workflow-settings-harness-summary"
    >
      <h4>Harness</h4>
      <dl className="workflow-rail-stats">
        <div>
          <dt>Template</dt>
          <dd>{model.templateLabel}</dd>
        </div>
        <div>
          <dt>Activation</dt>
          <dd>{model.activationLabel}</dd>
        </div>
        <div>
          <dt>Mode</dt>
          <dd>{model.modeLabel}</dd>
        </div>
        <div>
          <dt>Components</dt>
          <dd>{model.componentCount}</dd>
        </div>
        <div>
          <dt>Live-ready</dt>
          <dd>{model.liveReadyLabel}</dd>
        </div>
        <div>
          <dt>Gated clusters</dt>
          <dd>{model.gatedClustersLabel}</dd>
        </div>
        <div data-testid="workflow-harness-authority-gate-status">
          <dt>Authority gates</dt>
          <dd>
            {harnessAuthorityGateReadyCount}/
            {harnessAuthorityGateLiveProofs.length}
          </dd>
        </div>
        <div>
          <dt>Slots</dt>
          <dd>
            {
              harnessSlots.filter((slot) =>
                boundHarnessSlotIds.has(slot.slotId),
              ).length
            }
            /{harnessSlots.length}
          </dd>
        </div>
      </dl>
      <WorkflowSettingsHarnessWorkerBindingPanel
        harnessActivationAudit={harnessActivationAudit}
        harnessActivationAuditReceiptRefs={harnessActivationAuditReceiptRefs}
        harnessActivationCandidate={harnessActivationCandidate}
        harnessActivationRecord={harnessActivationRecord}
        harnessActivationRollbackExecution={harnessActivationRollbackExecution}
        harnessActivationRollbackProof={harnessActivationRollbackProof}
        latestHarnessActivationAudit={latestHarnessActivationAudit}
        latestHarnessActivationAuditReceiptRefs={
          latestHarnessActivationAuditReceiptRefs
        }
        selectedHarnessActivationAuditEventId={
          selectedHarnessActivationAuditEventId
        }
        harnessActiveRuntimeBinding={harnessActiveRuntimeBinding}
        harnessActiveRuntimeRollbackApplyBlockers={
          harnessActiveRuntimeRollbackApplyBlockers
        }
        harnessActiveRuntimeRollbackApplyDisabled={
          harnessActiveRuntimeRollbackApplyDisabled
        }
        harnessActiveRuntimeRollbackApplyProof={
          harnessActiveRuntimeRollbackApplyProof
        }
        harnessActiveRuntimeRollbackDryRunPassed={
          harnessActiveRuntimeRollbackDryRunPassed
        }
        harnessActiveRuntimeRollbackExecutionProof={
          harnessActiveRuntimeRollbackExecutionProof
        }
        harnessActiveRuntimeRollbackProofBindingBlockers={
          harnessActiveRuntimeRollbackProofBindingBlockers
        }
        harnessActiveRuntimeRollbackProofStillBound={
          harnessActiveRuntimeRollbackProofStillBound
        }
        harnessBindingRollbackAvailable={harnessBindingRollbackAvailable}
        harnessBindingRollbackHash={harnessBindingRollbackHash}
        harnessBindingRollbackTargets={harnessBindingRollbackTargets}
        harnessRollbackDrillReceiptRefs={harnessRollbackDrillReceiptRefs}
        harnessRollbackExecutionReceiptRefs={
          harnessRollbackExecutionReceiptRefs
        }
        harnessRollbackRevisionBinding={harnessRollbackRevisionBinding}
        harnessRollbackRevisionBindingRef={harnessRollbackRevisionBindingRef}
        harnessSelectedRollbackTarget={harnessSelectedRollbackTarget}
        selectedHarnessRollbackTarget={selectedHarnessRollbackTarget}
        harnessBindingInspectorStatus={harnessBindingInspectorStatus}
        harnessBindingVersionEntries={harnessBindingVersionEntries}
        harnessCandidateRevisionBinding={harnessCandidateRevisionBinding}
        harnessCandidateRevisionBindingRef={harnessCandidateRevisionBindingRef}
        harnessCandidateWorkerBinding={harnessCandidateWorkerBinding}
        harnessCurrentWorkerBinding={harnessCurrentWorkerBinding}
        harnessRevisionBinding={harnessRevisionBinding}
        harnessRevisionBindingRef={harnessRevisionBindingRef}
        harnessWorkerBinding={harnessWorkerBinding}
        selectedHarnessDefaultDispatchId={selectedHarnessDefaultDispatchId}
        selectedHarnessNodeAttemptId={selectedHarnessNodeAttemptId}
        selectedHarnessReceiptRef={selectedHarnessReceiptRef}
        selectedHarnessReplayFixtureRef={selectedHarnessReplayFixtureRef}
        selectedHarnessRevisionBindingKind={selectedHarnessRevisionBindingKind}
        selectedHarnessRevisionBindingRef={selectedHarnessRevisionBindingRef}
        selectedHarnessSelectorDecisionId={selectedHarnessSelectorDecisionId}
        selectedHarnessWorkerBindingId={selectedHarnessWorkerBindingId}
        harnessForkWorkflow={harnessForkWorkflow}
        onApplyActiveRuntimeRollback={onApplyActiveRuntimeRollback}
        onApplyHarnessActivationCandidate={onApplyHarnessActivationCandidate}
        onCheckActivationReadiness={onCheckActivationReadiness}
        onCopyHarnessDeepLink={onCopyHarnessDeepLink}
        onExecuteHarnessRollback={onExecuteHarnessRollback}
        onRunActiveRuntimeRollbackDryRun={onRunActiveRuntimeRollbackDryRun}
        onRunHarnessActivationDryRun={onRunHarnessActivationDryRun}
        onRunHarnessRollbackDrill={onRunHarnessRollbackDrill}
        onSelectHarnessReceiptRef={onSelectHarnessReceiptRef}
        onSelectHarnessReplayFixtureRef={onSelectHarnessReplayFixtureRef}
        onSelectHarnessRollbackTarget={onSelectHarnessRollbackTarget}
        workflow={workflow}
      />
      <WorkflowSettingsHarnessActivationPanel
        activationGateProposal={activationGateProposal}
        blessedHarnessWorkflow={blessedHarnessWorkflow}
        firstHarnessActivationBlocker={firstHarnessActivationBlocker}
        harnessActivationBlockers={harnessActivationBlockers}
        harnessActivationCandidate={harnessActivationCandidate}
        harnessActivationGateActions={harnessActivationGateActions}
        harnessActivationGateNodeAttempts={harnessActivationGateNodeAttempts}
        harnessActivationReady={harnessActivationReady}
        harnessActivationRecord={harnessActivationRecord}
        harnessActivationWizardSteps={harnessActivationWizardSteps}
        harnessActivationWorkerHandoffNodeAttemptIds={
          harnessActivationWorkerHandoffNodeAttemptIds
        }
        harnessActivationWorkerHandoffNodeAttempts={
          harnessActivationWorkerHandoffNodeAttempts
        }
        harnessActivationWorkerHandoffReplayFixtureRefs={
          harnessActivationWorkerHandoffReplayFixtureRefs
        }
        harnessActivationWorkerHandoffTimelineReady={
          harnessActivationWorkerHandoffTimelineReady
        }
        harnessActivationWorkerInvariantBlockers={
          harnessActivationWorkerInvariantBlockers
        }
        harnessActivationWorkerInvariantReady={
          harnessActivationWorkerInvariantReady
        }
        harnessActivationWorkerRequiredInvariantIds={
          harnessActivationWorkerRequiredInvariantIds
        }
        packageImportActivationEnabled={packageImportActivationEnabled}
        packageImportActivationHandoff={packageImportActivationHandoff}
        packageImportHandoffWorkerBindingId={
          packageImportHandoffWorkerBindingId
        }
        packageImportReplayIntegrityBlockers={
          packageImportReplayIntegrityBlockers
        }
        packageImportReview={packageImportReview}
        selectedHarnessActivationGateEvidenceRef={
          selectedHarnessActivationGateEvidenceRef
        }
        selectedHarnessActivationGateId={selectedHarnessActivationGateId}
        selectedHarnessActivationGateInspection={
          selectedHarnessActivationGateInspection
        }
        selectedHarnessActivationGateMutationCanary={
          selectedHarnessActivationGateMutationCanary
        }
        selectedHarnessActivationGateNodeAttempt={
          selectedHarnessActivationGateNodeAttempt
        }
        selectedHarnessActivationGateNodeAttemptId={
          selectedHarnessActivationGateNodeAttemptId
        }
        selectedHarnessActivationGateReceiptRef={
          selectedHarnessActivationGateReceiptRef
        }
        selectedHarnessActivationGateReplayFixtureRef={
          selectedHarnessActivationGateReplayFixtureRef
        }
        harnessPackageDeepLinks={harnessPackageDeepLinks}
        harnessPackageEvidenceBlockerCount={harnessPackageEvidenceBlockerCount}
        harnessPackageEvidenceReady={harnessPackageEvidenceReady}
        harnessPackageEvidenceRefValues={harnessPackageEvidenceRefValues}
        harnessPackageEvidenceReviewRows={harnessPackageEvidenceReviewRows}
        harnessPackageForkMutationCanary={harnessPackageForkMutationCanary}
        harnessPackageForkMutationCanaryNodeAttemptIds={
          harnessPackageForkMutationCanaryNodeAttemptIds
        }
        harnessPackageForkMutationCanaryReceiptRefs={
          harnessPackageForkMutationCanaryReceiptRefs
        }
        harnessPackageForkMutationCanaryReplayFixtureRefs={
          harnessPackageForkMutationCanaryReplayFixtureRefs
        }
        harnessPackageManifest={harnessPackageManifest}
        harnessPackageReceiptRefValues={harnessPackageReceiptRefValues}
        harnessPackageReplayFixtureRefValues={
          harnessPackageReplayFixtureRefValues
        }
        harnessPackageRollbackRestoreReceiptRefs={
          harnessPackageRollbackRestoreReceiptRefs
        }
        harnessPackageWorkerHandoffNodeAttemptIds={
          harnessPackageWorkerHandoffNodeAttemptIds
        }
        harnessPackageWorkerHandoffReceiptIds={
          harnessPackageWorkerHandoffReceiptIds
        }
        rollbackReady={rollbackReady}
        selectedHarnessCanaryBoundary={selectedHarnessCanaryBoundary}
        selectedHarnessRollbackDrillId={selectedHarnessRollbackDrillId}
        selectedHarnessRollbackRestoreCanaryId={
          selectedHarnessRollbackRestoreCanaryId
        }
        selectedHarnessRollbackRestoreReceiptRef={
          selectedHarnessRollbackRestoreReceiptRef
        }
        harnessWorkerBinding={harnessWorkerBinding}
        selectedHarnessNodeAttemptId={selectedHarnessNodeAttemptId}
        selectedHarnessReceiptRef={selectedHarnessReceiptRef}
        selectedHarnessReplayFixtureRef={selectedHarnessReplayFixtureRef}
        harnessForkMutationCanary={harnessForkMutationCanary}
        harnessForkMutationCanaryNodeAttemptIds={
          harnessForkMutationCanaryNodeAttemptIds
        }
        harnessForkWorkflow={harnessForkWorkflow}
        onApplyHarnessActivationCandidate={onApplyHarnessActivationCandidate}
        onCheckActivationReadiness={onCheckActivationReadiness}
        onCopyHarnessDeepLink={onCopyHarnessDeepLink}
        onResolveIssue={onResolveIssue}
        onRunHarnessActivationDryRun={onRunHarnessActivationDryRun}
        onSelectHarnessReceiptRef={onSelectHarnessReceiptRef}
        onSelectHarnessReplayFixtureRef={onSelectHarnessReplayFixtureRef}
        onSelectProposal={onSelectProposal}
        workflow={workflow}
      />
      <WorkflowSettingsHarnessPromotionPanel
        boundHarnessSlotIds={boundHarnessSlotIds}
        harnessActivationRecord={harnessActivationRecord}
        selectedHarnessActivationBlockerIndex={
          selectedHarnessActivationBlockerIndex
        }
        selectedHarnessActivationBlockerRef={
          selectedHarnessActivationBlockerRef
        }
        selectedHarnessActivationGateReceiptRef={
          selectedHarnessActivationGateReceiptRef
        }
        selectedHarnessActivationGateReplayFixtureRef={
          selectedHarnessActivationGateReplayFixtureRef
        }
        harnessAuthorityGateLiveProofs={harnessAuthorityGateLiveProofs}
        harnessAuthorityGateLiveReady={harnessAuthorityGateLiveReady}
        harnessAuthorityGateReadyCount={harnessAuthorityGateReadyCount}
        harnessAuthorityToolingNodeAuthorityGate={
          harnessAuthorityToolingNodeAuthorityGate
        }
        harnessAuthorityToolingProof={harnessAuthorityToolingProof}
        harnessCognitionNodeAuthorityGate={harnessCognitionNodeAuthorityGate}
        harnessForkComponentDiffRows={harnessForkComponentDiffRows}
        harnessForkComponentDiffStats={harnessForkComponentDiffStats}
        harnessForkMutationCanary={harnessForkMutationCanary}
        harnessForkMutationCanaryNodeAttemptIds={
          harnessForkMutationCanaryNodeAttemptIds
        }
        harnessForkWorkflow={harnessForkWorkflow}
        harnessLiveHandoffProof={harnessLiveHandoffProof}
        harnessPromotionClusters={harnessPromotionClusters}
        harnessReadOnlyRoutingNodeKinds={harnessReadOnlyRoutingNodeKinds}
        harnessReadOnlyRoutingProof={harnessReadOnlyRoutingProof}
        harnessReadOnlyRoutingReady={harnessReadOnlyRoutingReady}
        harnessReadOnlyRoutingRequiredScenarios={
          harnessReadOnlyRoutingRequiredScenarios
        }
        harnessRoutingModelNodeAuthorityGate={
          harnessRoutingModelNodeAuthorityGate
        }
        harnessRuntimeSelectorDecision={harnessRuntimeSelectorDecision}
        harnessSelectorLivePromotionReadinessBlockers={
          harnessSelectorLivePromotionReadinessBlockers
        }
        harnessSelectorLivePromotionReadinessProof={
          harnessSelectorLivePromotionReadinessProof
        }
        harnessSelectorLivePromotionReadinessReady={
          harnessSelectorLivePromotionReadinessReady
        }
        harnessSlots={harnessSlots}
        harnessVerificationOutputNodeAuthorityGate={
          harnessVerificationOutputNodeAuthorityGate
        }
        harnessCanaryExecutionBoundaries={harnessCanaryExecutionBoundaries}
        selectedHarnessCanaryBoundary={selectedHarnessCanaryBoundary}
        selectedHarnessRollbackDrillId={selectedHarnessRollbackDrillId}
        harnessDefaultRuntimeDispatchProof={harnessDefaultRuntimeDispatchProof}
        harnessDefaultRuntimeDispatchWorkerHandoffReceiptInvariantBlockers={
          harnessDefaultRuntimeDispatchWorkerHandoffReceiptInvariantBlockers
        }
        harnessDefaultRuntimeDispatchWorkerHandoffReceiptInvariantIds={
          harnessDefaultRuntimeDispatchWorkerHandoffReceiptInvariantIds
        }
        harnessDefaultRuntimeDispatchWorkerLaunchEnvelopeInvariantBlockers={
          harnessDefaultRuntimeDispatchWorkerLaunchEnvelopeInvariantBlockers
        }
        harnessDefaultRuntimeDispatchWorkerLaunchEnvelopeInvariantIds={
          harnessDefaultRuntimeDispatchWorkerLaunchEnvelopeInvariantIds
        }
        harnessDefaultRuntimeDispatchWorkerLaunchReviewedImportInvariantBound={
          harnessDefaultRuntimeDispatchWorkerLaunchReviewedImportInvariantBound
        }
        harnessDefaultRuntimeDispatchWorkerSessionLaunchAuthorityInvariantBlockers={
          harnessDefaultRuntimeDispatchWorkerSessionLaunchAuthorityInvariantBlockers
        }
        harnessDefaultRuntimeDispatchWorkerSessionLaunchAuthorityInvariantIds={
          harnessDefaultRuntimeDispatchWorkerSessionLaunchAuthorityInvariantIds
        }
        selectedHarnessReceiptRef={selectedHarnessReceiptRef}
        selectedHarnessReplayFixtureRef={selectedHarnessReplayFixtureRef}
        onCopyHarnessDeepLink={onCopyHarnessDeepLink}
        onInspectNode={onInspectNode}
        onSelectHarnessReceiptRef={onSelectHarnessReceiptRef}
        onSelectHarnessReplayFixtureRef={onSelectHarnessReplayFixtureRef}
        workflow={workflow}
      />
    </section>
  ) : null;
}
