// The differential-case array's TYPE-CHECKING SCALE, exercised against the real compiler and the
// real generated projection.
//
// WHY THIS EXISTS. `ARCHITECTURE_CONTRACT_DIFFERENTIAL_CASES` in the generated TypeScript projection
// carries one entry per registered fixture and per registered mutation, so it grows with the corpus.
// Emitted as a bare array literal, TypeScript infers the whole literal first — widening every object
// to its own type, with `value_json` in particular becoming a distinct and very large string literal
// type — and then checks that union against the variable's annotation. Past a threshold that
// inference exceeds the compiler's union-complexity limit and the build dies with TS2590 on the
// array expression, which reads like a defect in the generated file rather than a scale limit in how
// it was emitted. Registering four contract families was enough to cross it: `npm run build:workbench`
// stopped compiling.
//
// The generator now wraps each entry in an identity annotated at the element type, so no
// cross-element union is ever formed. That fix is invisible to every other check here:
// `check:architecture-contracts` compares generated bytes and never type-checks them, and the
// workbench build type-checks only the emitted form — which passes, and would go on passing if the
// generator silently reverted while the corpus happened to be small enough. So the fix would stop
// being tested by anything.
//
// HOW THIS AVOIDS PROVING NOTHING. A synthetic corpus does not reproduce the limit: four thousand
// short synthetic entries type-check fine, because the driver is the WIDTH of the real `value_json`
// literals rather than the entry count. So this test does not invent a corpus. It reads the REAL
// generated projection, reconstructs the bare-array form of its own differential-case block, and
// type-checks BOTH. Only the pair is evidence: the bare form must FAIL (otherwise the emitted form's
// success says nothing about the limit) and the emitted form must PASS.

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const TSC = path.join(ROOT, "node_modules", "typescript", "bin", "tsc");
const PROJECTION = path.join(
  ROOT,
  "packages/hypervisor-workbench/src/runtime/generated/architecture-contracts.ts",
);
const MARKER = "export const ARCHITECTURE_CONTRACT_DIFFERENTIAL_CASES";

/// Split the projection around its differential-case block.
function projectionParts() {
  const text = fs.readFileSync(PROJECTION, "utf8");
  const start = text.indexOf(MARKER);
  assert.notEqual(start, -1, "the projection declares the differential-case array");
  const end = text.indexOf("\n];", start) + 3;
  return { text, start, end, block: text.slice(start, end) };
}

/// Type-check one standalone source with the same strictness the workbench build uses.
function typeCheck(source, label) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ioi-ts-scale-"));
  try {
    const file = path.join(dir, "projection.ts");
    fs.writeFileSync(file, source);
    const result = spawnSync(
      process.execPath,
      [TSC, "--noEmit", "--strict", "--target", "ES2020", "--skipLibCheck", file],
      { encoding: "utf8", maxBuffer: 1 << 28 },
    );
    return {
      status: result.status,
      output: `${result.stdout ?? ""}${result.stderr ?? ""}`.replaceAll(file, label),
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

test("the generator emits the identity-helper form, and the checked-in projection carries it", () => {
  const generator = fs.readFileSync(
    path.join(ROOT, "scripts/generate-architecture-contracts.mjs"),
    "utf8",
  );
  assert.match(
    generator,
    /const differentialCase = \(\s*entry: ArchitectureContractDifferentialCase,?\s*\): ArchitectureContractDifferentialCase => entry;/u,
    "the generator declares the annotated identity",
  );
  assert.match(
    generator,
    /differentialCase\(" \+ JSON\.stringify\(entry\) \+ "\),/u,
    "and wraps every emitted entry in it",
  );
  const { block } = projectionParts();
  const wrapped = block.split("differentialCase(").length - 1;
  assert.ok(
    wrapped > 0,
    "the checked-in projection carries the wrapped form rather than a stale bare array",
  );
});

test("the bare array literal reproduces TS2590 on the REAL corpus, so the emitted form's success is about the limit", () => {
  assert.ok(fs.existsSync(TSC), "typescript is installed; this test drives the real compiler");
  const { text, start, end, block } = projectionParts();
  const entries = [...block.matchAll(/differentialCase\((\{.*?\})\),\n/gu)].map((match) => match[1]);
  assert.ok(entries.length > 500, `recovered a real corpus, not a handful: ${entries.length}`);
  const bare = [
    `export const ARCHITECTURE_CONTRACT_DIFFERENTIAL_CASES: ReadonlyArray<ArchitectureContractDifferentialCase> = [`,
    `  ${entries.join(",\n  ")}`,
    `];`,
  ].join("\n");
  // The identity is dropped with the wrapping, so the unused-local rule does not mask the real error.
  const source = `${text.slice(0, start)}${bare}${text.slice(end)}`.replace(
    /const differentialCase = \([\s\S]*?=> entry;\n/u,
    "",
  );
  const result = typeCheck(source, "bare-array-projection.ts");
  assert.notEqual(
    result.status,
    0,
    `the un-annotated form must FAIL at the real corpus size (${entries.length} entries), or this test proves nothing about the limit`,
  );
  assert.match(
    result.output,
    /TS2590/u,
    `and it must fail with the union-complexity limit specifically: ${result.output.slice(0, 400)}`,
  );
});

test("the emitted identity-helper form type-checks the same corpus cleanly", () => {
  const { text } = projectionParts();
  const result = typeCheck(text, "emitted-projection.ts");
  assert.equal(
    result.status,
    0,
    `the emitted form must type-check: ${result.output.slice(0, 800)}`,
  );
});
