pub(crate) use super::support::{
    append_pending_web_success_fallback, append_pending_web_success_from_bundle,
    candidate_source_hints_from_bundle,
    constraint_grounded_probe_query_with_hints_and_locality_hint, constraint_grounded_search_limit,
    effective_locality_scope_hint, is_citable_web_url, is_human_challenge_error,
    is_multi_item_listing_url, is_news_feed_wrapper_url, is_search_hub_url,
    mark_pending_web_attempted, mark_pending_web_blocked, merge_pending_search_completion,
    parse_web_evidence_bundle, pre_read_candidate_plan_from_bundle_with_locality_hint,
    query_is_generic_headline_collection, query_requires_runtime_locality_scope,
    queue_web_read_from_pipeline, queue_web_search_from_pipeline, remaining_pending_web_candidates,
    render_mailbox_access_limited_reply, select_web_pipeline_query_contract, source_host,
    synthesize_web_pipeline_reply, synthesize_web_pipeline_reply_hybrid,
    url_structurally_equivalent, web_pipeline_can_queue_probe_search_latency_aware,
    web_pipeline_grounded_probe_attempt_available, web_pipeline_min_sources, web_pipeline_now_ms,
    WebPipelineCompletionReason, WEB_PIPELINE_BUDGET_MS, WEB_PIPELINE_SEARCH_LIMIT,
};
