pub(crate) use super::support::{
    append_final_web_completion_receipts,
    append_final_web_completion_receipts_with_rendered_summary,
    append_pending_web_success_fallback, append_pending_web_success_from_bundle,
    build_query_constraint_projection, candidate_constraint_compatibility,
    candidate_source_hints_from_bundle, candidate_time_sensitive_resolvable_payload,
    collect_projection_candidate_urls_with_locality_hint, compatibility_passes_projection,
    constraint_grounded_probe_query_with_hints_and_locality_hint, constraint_grounded_search_limit,
    constraint_grounded_search_query,
    constraint_grounded_search_query_with_contract_and_hints_and_locality_hint,
    constraint_grounded_search_query_with_hints_and_locality_hint, effective_locality_scope_hint,
    excerpt_has_query_grounding_signal_with_contract, explicit_query_scope_hint,
    final_web_completion_contract_ready, final_web_completion_facts,
    final_web_completion_facts_with_rendered_summary, is_citable_web_url, is_human_challenge_error,
    is_multi_item_listing_url, is_query_stopword, is_search_hub_url,
    local_business_entity_discovery_query_contract, local_business_search_entity_anchor_tokens,
    local_business_search_entity_anchor_tokens_with_contract, mark_pending_web_attempted,
    mark_pending_web_blocked, merge_pending_search_completion, metric_axis_search_phrase,
    next_pending_web_candidate, parse_web_evidence_bundle,
    pre_read_candidate_plan_from_bundle_with_contract_and_locality_hint,
    pre_read_candidate_plan_from_bundle_with_locality_hint,
    preferred_pre_read_action_count_with_locality_hint, prefers_single_fact_snapshot,
    projection_candidate_url_allowed, projection_candidate_url_allowed_with_projection,
    query_contains_structured_search_operators, query_is_generic_headline_collection,
    query_metric_axes, query_prefers_document_briefing_layout,
    query_prefers_multi_item_cardinality, query_requests_comparison,
    query_requires_local_business_entity_diversity, query_requires_runtime_locality_scope,
    queue_web_read_from_pipeline, queue_web_search_from_pipeline, remaining_pending_web_candidates,
    render_mailbox_access_limited_reply, required_citations_per_story,
    required_distinct_domain_floor, required_story_count,
    resolved_query_contract_with_locality_hint, retrieval_affordances_with_locality_hint,
    retrieval_contract_min_sources,
    retrieval_contract_requires_document_briefing_identifier_evidence,
    select_final_web_summary_from_candidates, select_web_pipeline_query_contract,
    selected_source_quality_metrics_with_locality_hint,
    semantic_retrieval_query_contract_with_locality_hint,
    source_has_briefing_standard_identifier_signal,
    source_has_document_briefing_authority_alignment_with_contract,
    source_has_grounded_primary_authority, source_has_human_challenge_signal,
    source_has_public_authority_host, source_host,
    source_matches_local_business_search_entity_anchor, synthesize_web_pipeline_reply,
    synthesize_web_pipeline_reply_hybrid, url_structurally_equivalent,
    web_pipeline_can_queue_probe_search_latency_aware, web_pipeline_completion_reason,
    web_pipeline_grounded_probe_attempt_available, web_pipeline_min_sources, web_pipeline_now_ms,
    FinalWebSummaryCandidate, RetrievalAffordanceKind, WebPipelineCompletionReason,
    WEB_PIPELINE_BUDGET_MS, WEB_PIPELINE_SEARCH_LIMIT,
};
