use super::super::types::{AllowedToolProfile, ComputerUseCase, LocalJudge, RecipeId, TaskSet};

pub fn cases() -> Vec<ComputerUseCase> {
    vec![
        ComputerUseCase {
            id: "miniwob_click_option_core".to_string(),
            env_id: "click-option".to_string(),
            seed: 201,
            task_set: TaskSet::Core,
            max_steps: 10,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ClickOption,
        },
        ComputerUseCase {
            id: "miniwob_click_checkboxes_core".to_string(),
            env_id: "click-checkboxes".to_string(),
            seed: 202,
            task_set: TaskSet::Core,
            max_steps: 14,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 0.5,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ClickCheckboxes,
        },
        ComputerUseCase {
            id: "miniwob_click_checkboxes_transfer_core".to_string(),
            env_id: "click-checkboxes-transfer".to_string(),
            seed: 203,
            task_set: TaskSet::Core,
            max_steps: 16,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 0.5,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ClickCheckboxesTransfer,
        },
        ComputerUseCase {
            id: "miniwob_enter_password_core".to_string(),
            env_id: "enter-password".to_string(),
            seed: 204,
            task_set: TaskSet::Core,
            max_steps: 12,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::EnterPassword,
        },
        ComputerUseCase {
            id: "miniwob_login_user_core".to_string(),
            env_id: "login-user".to_string(),
            seed: 205,
            task_set: TaskSet::Core,
            max_steps: 12,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::LoginUser,
        },
        ComputerUseCase {
            id: "miniwob_focus_text_2_core".to_string(),
            env_id: "focus-text-2".to_string(),
            seed: 206,
            task_set: TaskSet::Core,
            max_steps: 8,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::FocusText2,
        },
        ComputerUseCase {
            id: "miniwob_enter_text_2_core".to_string(),
            env_id: "enter-text-2".to_string(),
            seed: 207,
            task_set: TaskSet::Core,
            max_steps: 12,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::EnterText2,
        },
        ComputerUseCase {
            id: "miniwob_click_button_sequence_core".to_string(),
            env_id: "click-button-sequence".to_string(),
            seed: 208,
            task_set: TaskSet::Core,
            max_steps: 8,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ClickButtonSequence,
        },
        ComputerUseCase {
            id: "miniwob_click_collapsible_core".to_string(),
            env_id: "click-collapsible".to_string(),
            seed: 209,
            task_set: TaskSet::Core,
            max_steps: 10,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ClickCollapsible,
        },
    ]
}
