use super::super::types::{AllowedToolProfile, ComputerUseCase, LocalJudge, RecipeId, TaskSet};

pub fn cases() -> Vec<ComputerUseCase> {
    vec![
        ComputerUseCase {
            id: "miniwob_click_button_smoke".to_string(),
            env_id: "click-button".to_string(),
            seed: 101,
            task_set: TaskSet::Smoke,
            max_steps: 8,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ClickButton,
        },
        ComputerUseCase {
            id: "miniwob_click_link_smoke".to_string(),
            env_id: "click-link".to_string(),
            seed: 102,
            task_set: TaskSet::Smoke,
            max_steps: 8,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ClickLink,
        },
        ComputerUseCase {
            id: "miniwob_enter_text_smoke".to_string(),
            env_id: "enter-text".to_string(),
            seed: 103,
            task_set: TaskSet::Smoke,
            max_steps: 10,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::EnterText,
        },
        ComputerUseCase {
            id: "miniwob_focus_text_smoke".to_string(),
            env_id: "focus-text".to_string(),
            seed: 104,
            task_set: TaskSet::Smoke,
            max_steps: 6,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::FocusText,
        },
        ComputerUseCase {
            id: "miniwob_choose_list_smoke".to_string(),
            env_id: "choose-list".to_string(),
            seed: 105,
            task_set: TaskSet::Smoke,
            max_steps: 10,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCoreWithSelect,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ChooseList,
        },
        ComputerUseCase {
            id: "miniwob_click_tab_smoke".to_string(),
            env_id: "click-tab".to_string(),
            seed: 106,
            task_set: TaskSet::Smoke,
            max_steps: 8,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ClickTab,
        },
        ComputerUseCase {
            id: "miniwob_use_autocomplete_smoke".to_string(),
            env_id: "use-autocomplete-nodelay".to_string(),
            seed: 107,
            task_set: TaskSet::Smoke,
            max_steps: 12,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::UseAutocomplete,
        },
        ComputerUseCase {
            id: "miniwob_scroll_text_direction_smoke".to_string(),
            env_id: "scroll-text-2".to_string(),
            seed: 108,
            task_set: TaskSet::Smoke,
            max_steps: 10,
            timeout_seconds: 20,
            allowed_tool_profile: AllowedToolProfile::BrowserCore,
            expected_reward_floor: 1.0,
            expected_pass: true,
            local_judge: LocalJudge::MiniwobReward,
            recipe: RecipeId::ScrollText2,
        },
    ]
}
