const React = window.React;
// hypervisor.com — platform product catalog.
// One record per Platform product; consumed by ProductPage.jsx to render each subpage.
window.HV_PRODUCTS = [
  {
    slug: "app",
    file: "hv-app.html",
    name: "Hypervisor App",
    category: "Client · Desktop command center",
    title: "Operate autonomous work from your machine",
    sub: "Start governed sessions, run automations, and supervise agents across projects, tools, models, and providers — with approvals, receipts, and replay in one local-first workspace.",
    visual: "app",
    capabilities: [
      ["Local-first sessions", "A daemon on your machine holds runtime truth. Work starts where your data already is — no round trip to a vendor cloud to begin."],
      ["Approvals inline", "Consequential actions surface as requests, not faits accomplis. Approve, scope, or deny without leaving the run."],
      ["Replay any run", "Every session is a receipted, deterministic record. Scrub back through what happened and re-run it exactly."],
    ],
    detail: {
      eyebrow: "Inside the app",
      heading: "Everything a run needs, in one window",
      sub: "The app is the operator's seat. Projects, tools, models, and providers compose behind a single command bar; authority and history stay visible the whole way.",
      points: [
        ["Command bar", "Describe a task in plain language or type / for commands. Pick the project, model, and scope before a single action runs."],
        ["Projects & tools", "Group repos, connectors, and credentials into projects. Tools are declared, scoped, and revocable per session."],
        ["Sessions & history", "Every run lands in a searchable history with its receipts attached — nothing happens off the record."],
        ["Resource management", "Watch spend, leases, and live sessions across the workspace. Stop or re-scope anything in flight."],
      ],
    },
    specs: [
      ["Platform", "macOS · Linux · Windows"],
      ["Runtime", "Local daemon, offline-capable"],
      ["Authority", "Per-session scoped credentials"],
      ["Record", "Signed receipts · deterministic replay"],
    ],
    related: ["web", "cli", "sdk"],
  },
  {
    slug: "web",
    file: "hv-web.html",
    name: "Hypervisor Web",
    category: "Client · Browser & teams",
    title: "Bring autonomous work to the whole team",
    sub: "Shared projects, remote sessions, approvals, and run history in the browser — without changing the runtime truth or where work actually executes.",
    visual: "web",
    capabilities: [
      ["Shared projects", "Teams see the same projects, tools, and history. Roles and scopes decide who can start, approve, or merge."],
      ["Remote sessions", "Kick off a run from a laptop, check it from a phone. The session lives on the substrate, not your tab."],
      ["Approvals & audit", "Route consequential actions to reviewers. Every decision is attributed and receipted for the audit trail."],
    ],
    detail: {
      eyebrow: "Built for teams",
      heading: "The same truth, accessible anywhere",
      sub: "Web is a client over the same Hypervisor Core the app and CLI use. It adds collaboration and access control — it never becomes a second source of truth.",
      points: [
        ["Org & roles", "Invite members, assign roles, and scope access to projects and tools. Authority is explicit and revocable."],
        ["Live run view", "Follow sessions in progress, inspect tool calls, and step into the same environment an agent used."],
        ["Approval queues", "Pending consequential actions collect in a queue. Approve, deny, or re-scope with full context attached."],
        ["Shared history", "Receipts and lineage are visible to the whole team — proof of what ran, who approved it, and why."],
      ],
    },
    specs: [
      ["Access", "Browser · no install"],
      ["Collaboration", "Orgs, roles, shared projects"],
      ["Runtime", "Hosted or your VPC"],
      ["Audit", "Attributed approvals · signed receipts"],
    ],
    related: ["app", "cli", "mcp"],
  },
  {
    slug: "cli",
    file: "hv-cli.html",
    name: "Hypervisor CLI",
    category: "Client · Terminal, scripting & CI",
    title: "Script and supervise from the shell",
    sub: "Drive autonomous work from CI, shells, and servers with the same authority, receipts, and replay as the app — headless, scriptable, and pipeline-native.",
    visual: "cli",
    capabilities: [
      ["Headless by design", "No window, no human in the trigger. Start sessions from cron, CI steps, or a server and stream results to logs."],
      ["Scoped from the flag", "Declare scope at launch — fs.read, shell.exec, net.none. Anything outside the grant is blocked and receipted."],
      ["Pipeline-native", "Exit codes, JSON output, and signed receipts drop straight into CI gates and downstream automation."],
    ],
    detail: {
      eyebrow: "From the terminal",
      heading: "Autonomy that fits in a pipeline",
      sub: "The CLI carries the full Hypervisor contract into headless environments. Same runtime truth, same authority model, same receipts — just no UI.",
      points: [
        ["Sessions as commands", "hv session start, hv run, hv session end. Each command is scoped, logged, and replayable."],
        ["Streamed output", "Watch progress line by line, or pipe structured JSON into your own tooling and dashboards."],
        ["CI gates", "Block a merge on a failed receipt. Promote a build only when every action was in scope and tests passed."],
        ["Servers & cron", "Run recurring work on your own infrastructure with the same governance as an operator at a desk."],
      ],
    },
    specs: [
      ["Surface", "Terminal · headless · CI"],
      ["Output", "Streamed logs · structured JSON"],
      ["Authority", "Scope flags · blocked-by-default"],
      ["Record", "Signed receipts · exit codes"],
    ],
    related: ["app", "sdk", "automations"],
  },
  {
    slug: "sdk",
    file: "hv-sdk.html",
    name: "Hypervisor SDK",
    category: "Builder · Protocol library",
    title: "Build on the substrate, not around it",
    sub: "Integrate Hypervisor into products, agents, and internal tools without reimplementing runtime, authority, receipt, or state semantics.",
    visual: "glow",
    capabilities: [
      ["Runtime primitives", "Sessions, tool calls, leases, and receipts as first-class objects. The hard parts are library calls, not your problem."],
      ["Authority built in", "Scope, broker, and revoke credentials through the SDK. Your code never has to hold a raw key."],
      ["Typed & portable", "Stable, typed bindings across languages. The protocol contract is the same one the app and CLI speak."],
    ],
    detail: {
      eyebrow: "For developers",
      heading: "The protocol, as a library",
      sub: "The SDK exposes Hypervisor Core directly: everything a client does, your code can do — under the same governance, with none of the reimplementation.",
      points: [
        ["Sessions API", "Open, scope, drive, and close governed sessions programmatically. Stream events as they happen."],
        ["Tool & lease broker", "Request capabilities at runtime. The broker issues scoped, revocable leases — never standing access."],
        ["Receipts & state", "Read the canonical record of what ran. Verify receipts and replay accepted operations deterministically."],
        ["Embeddable", "Drop governed autonomy into an existing product without standing up your own runtime."],
      ],
    },
    specs: [
      ["Form", "Typed protocol bindings"],
      ["Languages", "TypeScript · Python · Go"],
      ["Authority", "Brokered leases · revocable"],
      ["Contract", "Same Core as App · Web · CLI"],
    ],
    related: ["adk", "odk", "cli"],
  },
  {
    slug: "adk",
    file: "hv-adk.html",
    name: "Hypervisor ADK",
    category: "Builder · Autonomous-system kit",
    title: "Build and ship autonomous systems",
    sub: "Compose workers, harnesses, evals, manifests, and deployment profiles — packaged as governed autonomous-system bundles ready to run anywhere.",
    visual: "glow",
    capabilities: [
      ["Workers & harnesses", "Define a worker's tools, policy, and behavior. Wrap it in a harness that bounds what it can ever do."],
      ["Evals as a gate", "Benchmark a worker against your own task suite. Promotion is earned by passing evals, not by hand-waving."],
      ["Deployment profiles", "Ship the same bundle to local, cloud, VPC, or DePIN with a profile — runtime stays consistent, perimeter changes."],
    ],
    detail: {
      eyebrow: "Author the system",
      heading: "From a prompt to a packaged worker",
      sub: "The ADK turns ad-hoc agents into governed, benchmarked, deployable bundles — versioned artifacts you can trust in production.",
      points: [
        ["Manifests", "Declare a worker's identity, tools, models, and policy in one manifest. The bundle is reproducible from it."],
        ["Harnesses", "Bound execution with a harness: allowed tools, scopes, and stop conditions enforced at runtime."],
        ["Eval packs", "Attach task suites and graders. Track regressions across versions before anything reaches production."],
        ["Bundle & deploy", "Package worker, harness, and evals into one artifact. Deploy by profile, govern by the same Core."],
      ],
    },
    specs: [
      ["Form", "Autonomous-system bundles"],
      ["Includes", "Workers · harnesses · evals · manifests"],
      ["Deploy", "Local · cloud · VPC · DePIN"],
      ["Trains with", "Foundry worker training"],
    ],
    related: ["sdk", "odk", "worker-training"],
  },
  {
    slug: "odk",
    file: "hv-odk.html",
    name: "Hypervisor ODK",
    category: "Builder · Ontology-aware kit",
    title: "Turn domain knowledge into working surfaces",
    sub: "Compile ontologies and data recipes into generated surfaces, domain apps, eval packs, and marketplace-ready ontology packs.",
    visual: "glow",
    capabilities: [
      ["Ontology as source", "Model your domain once — entities, relations, rules. Surfaces and apps generate from that single description."],
      ["Generated surfaces", "Forms, views, and flows fall out of the ontology. Change the model, regenerate the surface."],
      ["Marketplace packs", "Bundle an ontology with its evals and recipes into a shareable, versioned pack others can adopt."],
    ],
    detail: {
      eyebrow: "Domain-driven",
      heading: "Knowledge in, software out",
      sub: "The ODK treats a domain ontology as the contract. Surfaces, domain apps, and eval packs are derived from it — not hand-built and left to drift.",
      points: [
        ["Ontology modeling", "Describe entities, relations, and constraints. The model is the canonical source the rest derives from."],
        ["Data recipes", "Map real data onto the ontology with declarative recipes — ingestion, transforms, and validation as code."],
        ["Domain apps", "Generate focused apps and surfaces for operators in a domain, governed by the same runtime and authority."],
        ["Ontology packs", "Publish an ontology, its recipes, and its evals as a versioned pack to the marketplace."],
      ],
    },
    specs: [
      ["Source", "Domain ontology + data recipes"],
      ["Generates", "Surfaces · domain apps · eval packs"],
      ["Output", "Marketplace-ready ontology packs"],
      ["Builds on", "SDK runtime primitives"],
    ],
    related: ["adk", "sdk", "app"],
  },
  {
    slug: "mcp",
    file: "hv-mcp.html",
    name: "Hypervisor MCP",
    category: "Gateway · Scoped external access",
    title: "Hand external agents a key, never the keyring",
    sub: "Expose selected capabilities to external agents through revocable, auditable MCP profiles — scoped access, every call receipted, never a master key.",
    visual: "light",
    capabilities: [
      ["Scoped profiles", "Publish a narrow slice of capability per consumer. An external agent sees only what its profile allows."],
      ["Revocable access", "Grants are leases, not keys. Revoke a profile and access stops — no rotation scramble, no orphaned secrets."],
      ["Every call receipted", "External calls run through the same Core. What an outside agent did is on the record like everything else."],
    ],
    detail: {
      eyebrow: "Outward-facing",
      heading: "A gateway, not a back door",
      sub: "MCP carries Hypervisor capability to agents you don't run — under profiles you control, with the same authority and audit as internal work.",
      points: [
        ["Capability profiles", "Compose exactly which tools and scopes an external consumer receives. Default is nothing."],
        ["Brokered credentials", "The gateway brokers scoped, time-bound leases. External agents never touch raw secrets."],
        ["Rate & spend limits", "Bound how much an external consumer can do and spend. Limits are policy, enforced at the gateway."],
        ["Full audit", "Every external call is attributed and receipted. Revoke, inspect, and replay like any other session."],
      ],
    },
    specs: [
      ["Protocol", "MCP (Model Context Protocol)"],
      ["Access", "Scoped profiles · revocable leases"],
      ["Limits", "Rate · spend · capability"],
      ["Audit", "Attributed · receipted per call"],
    ],
    related: ["sdk", "web", "os"],
  },
  {
    slug: "os",
    file: "hv-os.html",
    name: "HypervisorOS",
    category: "Substrate · Bare-metal / cluster control",
    status: "Design stage",
    title: "Govern the substrate autonomy runs on",
    sub: "Operate measured hosts, GPU pools, storage, networks, model runtimes, containers, and microVMs under one policy plane — your hardware, your perimeter.",
    visual: "light",
    capabilities: [
      ["Measured boot", "Nodes attest their state before they join. Workloads run on hardware you can prove hasn't been tampered with."],
      ["Kernel-level policy", "Authority is enforced below the workload. A blocked syscall is blocked by the OS, not by a hopeful wrapper."],
      ["microVM isolation", "Each workload gets its own short-lived microVM. No shared state, no cascade, destroyed after use."],
    ],
    detail: {
      eyebrow: "Down to the metal",
      heading: "The substrate, on your own nodes",
      sub: "HypervisorOS turns bare metal and private clusters into governed autonomy substrate — the same authority and receipts as the cloud, enforced below the workload.",
      points: [
        ["Host and cluster profile", "Measured, attested nodes join as trusted Hypervisor substrate. Bring your own hardware; Hypervisor makes it governable."],
        ["Workload runtime", "Run tools, model runtimes, containers, and microVMs side by side with resource pools, network posture, and storage policy attached."],
        ["Policy plane", "Scopes and leases enforced at the kernel. Consequential syscalls are requests, not grants."],
        ["Receipts at the edge", "Work runs near your data and stays there. Only commitments that need public trust project outward."],
      ],
    },
    specs: [
      ["Form", "Bare-metal / cluster substrate"],
      ["Isolation", "Containers · microVMs · sandboxes"],
      ["Trust", "Measured boot · attestation"],
      ["Policy", "Kernel-level scopes & leases"],
    ],
    related: ["mcp", "embodied", "web"],
  },
  {
    slug: "embodied",
    file: "hv-embodied.html",
    name: "Embodied Runtime",
    category: "Substrate · Physical autonomy profile",
    status: "Design stage",
    title: "Autonomy that touches the physical world",
    sub: "Operate robot fleets, devices, sensors, command queues, and telemetry under safety gates — with operator handoff and the same receipts as software work.",
    visual: "light",
    capabilities: [
      ["Safety gates", "Physical actions pass through hard gates before they execute. Out-of-envelope commands never reach an actuator."],
      ["Fleet command", "Queue, sequence, and supervise commands across a fleet. Telemetry streams back into the same run history."],
      ["Operator handoff", "A human can take control at any point. Handoff is explicit, attributed, and receipted like every other action."],
    ],
    detail: {
      eyebrow: "Into the world",
      heading: "Governed autonomy, off the screen",
      sub: "The Embodied Runtime extends Hypervisor's authority model to devices and robots. The same scoping, receipts, and replay — now bounding physical action.",
      points: [
        ["Device & sensor model", "Register devices, sensors, and actuators as governed resources. Capability is declared and scoped."],
        ["Command queues", "Sequence physical actions with dependencies and gates. Nothing executes outside its safety envelope."],
        ["Telemetry & replay", "Sensor streams and outcomes are recorded as receipts. Replay a run to see exactly what the fleet did."],
        ["Safety & handoff", "Hard limits bound every actuator. Operators can pause, override, or take the wheel — all on the record."],
      ],
    },
    specs: [
      ["Targets", "Robots · devices · sensors"],
      ["Control", "Command queues · safety gates"],
      ["Telemetry", "Streamed · receipted"],
      ["Handoff", "Attributed operator override"],
    ],
    related: ["os", "mcp", "app"],
  },
];

// Cross-references that point at existing Solution pages rather than product subpages.
window.HV_EXT = {
  "automations": { name: "Automations & fleets", file: "automations-fleets.html" },
  "worker-training": { name: "Worker training", file: "worker-training.html" },
};

window.HV_PRODUCT_MAP = {};
window.HV_PRODUCTS.forEach((p) => { window.HV_PRODUCT_MAP[p.slug] = p; });
