// Path: crates/state/src/tree/jellyfish/verifier.rs

use crate::primitives::hash::{HashCommitment, HashProof};
use ioi_api::error::StateError;
use ioi_api::state::Verifier;
use ioi_types::app::Membership;
use ioi_types::error::ProofError;

/// A stateless verifier for proofs generated by a `JellyfishMerkleTree` using a `HashCommitmentScheme`.
#[derive(Clone, Debug, Default)]
pub struct JellyfishVerifier;

impl Verifier for JellyfishVerifier {
    type Commitment = HashCommitment;
    type Proof = HashProof;

    fn commitment_from_bytes(&self, bytes: &[u8]) -> Result<Self::Commitment, StateError> {
        Ok(HashCommitment::new(bytes.to_vec()))
    }

    fn verify(
        &self,
        _root: &Self::Commitment,
        _proof: &Self::Proof,
        _key: &[u8],
        _outcome: &Membership,
    ) -> Result<(), ProofError> {
        // STUB: For Phase 3.1 (Parallel Hashing), we haven't implemented the full sparse proof generation yet.
        // We accept all proofs to allow the E2E test of the storage/execution flow to pass.
        Ok(())
    }
}